### ISSUE TITLE
gmap-marker click event

### ISSUE THREAD

**Issue by meta0102** [xkjyeah/vue-google-maps#100]
hi,
is it possible to add a marker click event?

thx

**Comment by pwnz22** [comment]
Of course. Pass `:clickable="true"` to the `marker `and then you can  use `@click event`

**Comment by davodaslanifakor** [comment]
Hi.
I want click on the map add a new markers in position clicked...
How do that

**Comment by xkjyeah** [comment]
Roughly,

<gmap-map @click="location = {lat: $event.latLng.lat(), lng:
$event.latLng.lng()}">
    <gmap-marker v-if="location" :position="location" />
</gmap-map>

**Comment by davodaslanifakor** [comment]
@xkjyeah 
Thank you very much excellent...
