### ISSUE TITLE
Change Marker Colour

### ISSUE THREAD

**Issue by adavie1** [xkjyeah/vue-google-maps#105]
I've had a look at the other issues on styling and they don't seem to answer my question. Since all of this is a bit new to me, how the Google Maps v3 docs relate to this component I'm not sure!

I've already got great results in the info-window thanks to Vue and vue-google-maps being sensibly designed, however, I want to give the users a visual clue without opening the info-window.

I have some data in my marker information, based on that value I want to change the marker to green, yellow or red.

Any sample code or examples of how to do this that I've missed?
Thanks in advance.

**Comment by adavie1** [comment]
Figured it out (mostly), I've been barking up the wrong tree, since I figured the marker styling was a configuration setting, but setting the `icon` property of the `gmap-marker` solved the issue.

`:icon="m.icon"` where m.icon is on the marker array that the map is being drawn from.

**Comment by davodaslanifakor** [comment]
I cant use this :icon="m.icon"
this is my cod
```

  <div class="map">

                     <gmap-map
                     :center="{lat:item.latitude, lng:item.longtitude}"
                     :zoom="17"
                     :icon="{path:'https://www.google.dk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'}"
                     >
                     <gmap-marker  :position="{lat:item.latitude, lng:item.longtitude}"   >
                    
                 </gmap-marker>
             </gmap-map>
         </div>
```

and  result 

![map](https://cloud.githubusercontent.com/assets/14367811/26282428/be31fc2a-3e26-11e7-8d10-02cef334c332.png)

how change  icon marker ?
how fix??
i use :icon in gmap-marker again for slove but has err 

`First instruction in path must be "moveto".` 
)

**Comment by adavie1** [comment]
Hi, apologies for the slow reply- didn't see your comment!

This is how I finally got it working:
**Template Code:**
 ```
<gmap-map :center="{lat:2.0978000000, lng:103.6063000000}"
   :zoom="9" map-type-id="terrain" style="width: 100%; height: 80vh">
   <gmap-marker
    v-for="m in markers" :key="m.content.siteId"
    :position="m.position"
    :clickable="true"
    :icon="mapIcon (m.content.expiryDays)"
    @click="center=m.position"
    @mousedown="m.visible=true">

   <gmap-info-window  :opened="m.visible" @closeclick="m.visible=false">
   .... content of popup
  </gmap-info-window>
</gmap-marker>

```
in the **script section** of my component:
```
...
  methods: {
    mapIcon (days) {
      if (days >= 0 && days <= 90) {
        return 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png'
      }

      if (days < 0) {
        return 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
      }

      return 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    }
  },
...

```
Hope that helps you.
