### ISSUE TITLE
Issues in IE11

### ISSUE THREAD

**Issue by OlegIvaniv** [xkjyeah/vue-google-maps#106]
Hello,

first I want to say that I love the work you did here with this package!

Nonetheless we're having issues when using it on IE11. It seems like like there are some problem with promises and they are not being resolved. 

In IE11 it crashes here:
`var loaded = exports.loaded = new _promise2.default(function (resolve, reject) {
  // eslint-disable-line no-unused-vars
  window['vueGoogleMapsInit'] = resolve;
});` in **vue2-google-maps/dist/manager.js** and the promise is never resolved.

**Comment by xkjyeah** [comment]
Could you help debug the issue by checking the following

1) Can you check if the SCRIPT tag for Google Maps API has been added to
the DOM?
2) Did you run Vue.load(VueGoogleMaps, {load: {key: YOUR_KEY}})?

If anything, do you have a minimal JS fiddle that demonstrates the issue?

**Comment by OlegIvaniv** [comment]
Thanks for such a quick reply! 
It works just fine in chrome and all other browsers.

The authentication script is being added but not "executed" since not even window.google or just google doesn't exist in global scope

**Comment by GMSteuart** [comment]
@OlegIvaniv you might need to add in a promise library to resolve some issues with IE. Maybe trye adding
`import 'es6-promise/auto';`
https://www.npmjs.com/package/es6-promise

**Comment by OlegIvaniv** [comment]
I tried that but I also think that there is already polyfill in place inside the vue-google-maps package

**Comment by XStepien** [comment]
@OlegIvaniv, i had the same issue, just add "babel-polyfill" and now it's working !

**Comment by shlima** [comment]
+1 

```
Promise is undefined
```

**Comment by shlima** [comment]
I fixed this issue with the following:

```
import 'es6-promise/auto';
import 'es6-object-assign/auto';
```

But map position/zoom does not work in IE 11

**Comment by scamartist26** [comment]
I'm having issues on IE11 as well, however I am using browsersatck and cannot exactly debug very well. Has there been any traction with a solution?

**Comment by GMSteuart** [comment]
@scamartist26 are your issues with promises or something else?

**Comment by scamartist26** [comment]
I had a syntax error in my template causing other issues on top of this. I solved the `Promise` and `Object.assign` issues with the solution provided by @shlima above. I am NOT seeing any issues with zoom as he said.
