### ISSUE TITLE
Add autocomplete to map

### ISSUE THREAD

**Issue by jsgv** [xkjyeah/vue-google-maps#107]
I have looked at the examples, but I can't see how to do it.
I want to add the autocomplete input inside the map.  

![image](https://cloud.githubusercontent.com/assets/2798097/25641548/863ba0e6-2f49-11e7-8498-fae7916dade8.png)

As it looks in the documentation as well:
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

Thanks

**Comment by xkjyeah** [comment]
It's not exactly the same, but you can study how the blue infobars are implemented [here](http://xkjyeah.github.io/vue-google-maps/info-bar.html)

**Comment by Squidies** [comment]
I would also like to see an example how to to accomplish this.

> It's not exactly the same, but you can study how the blue infobars are implemented here

I have studied the example and still do not understand how to accomplish autocomplete search like the original question asks. 

Please show a working solution as you have demonstrated with "PlaceInput" found here http://xkjyeah.github.io/vue-google-maps/all-components.html

**Comment by xkjyeah** [comment]
PlaceInput should be considered deprecated. You should use the Autocomplete
component.

What you can do is something along the lines of:
<GmapMap>
<div slot="visible">
<div style="top: 0; right: 0; width: calc(100% - 100px); position:
absolute; z-index: 100">
<GmapAutocomplete />
</div>
</div>
</GmapMap>

**Comment by xkjyeah** [comment]
And the answer to your original question about native Google Maps controls,
no, it's not supported. I'm happy to accept a PR that fixes it though.
Sorry!

**Comment by Squidies** [comment]
My apologies, after I posted that question I realized I was asking a different question than the original post. I've since resolved my issue. Thank you.
