### ISSUE TITLE
Hidden map starts empty - How to reinitialize the map?

### ISSUE THREAD

**Issue by norotico** [xkjyeah/vue-google-maps#108]
There's a known "bug" in the original gmaps lib that makes the map start empty (100% grey) if its wrapper element is hidden at the moment of initialization. The solution being to reinitialize the map, as demonstrated in this [fiddle](https://jsfiddle.net/wvbdnb8o/187/).

So how can I reboot the map programmatically?

**Comment by MauroB45** [comment]
Hi @norotico 

You can use `Vue.$gmapDefaultResizeBus.$emit('resize')`

**Comment by petegore** [comment]
Where do you put this call ?

**Comment by MauroB45** [comment]
you can put this call on mounted

```
import Vue from 'vue'

// your component
export default {
   name: 'YourComponent',
   ...
   mounted () {
      Vue.$gmapDefaultResizeBus.$emit('resize')
   }
}
```
