### ISSUE TITLE
Why there is no center?

### ISSUE THREAD

**Issue by godbug** [xkjyeah/vue-google-maps#11]
When I enter and select a new address in `PlaceInput`, the map is not centered.

![image](https://cloud.githubusercontent.com/assets/23079142/20892205/2da14500-bb48-11e6-99c5-6a6315c2f032.png)

**Comment by xkjyeah** [comment]
Do you mean that the map is not centred to the selected place? You need to
listen for the place_changed event and then set the map centre whenever the
event is fired

**Comment by godbug** [comment]
OK, I'll try it with place_changed, thanks.
