### ISSUE TITLE
Newbie Question: Get Marker Position After Dragend Event

### ISSUE THREAD

**Issue by bendo01** [xkjyeah/vue-google-maps#111]
```
<gmap-map :center="center" :zoom="zoom" map-type-id="terrain">
  <gmap-marker 
     v-for="marker in markers"
     :position="position"
     :clickable="true"
     :draggable="true"
     @click="center=position"
     @dragend="getMarkerPosition(marker)">
   </gmap-marker>
</gmap-map>
```
```
getMarkerPosition (marker) { console.log(marker.latLng); }
```
the console output is undefined
my question is how to get market lat and lng after dragend event ?

**Comment by xkjyeah** [comment]
`@dragend="getMarkerPosition($event.latLng)"`

**Comment by guyver-dash** [comment]
@xkjyeah I've got this in my console.log. How can I get the `a` and `b`? Thanks for creating this.

![capture](https://user-images.githubusercontent.com/10149942/27575372-23e67d6a-5b4c-11e7-857f-3e5180ecdf2e.PNG)

**Comment by xkjyeah** [comment]
Latlng.lat(), latlng.lng()

**Comment by guyver-dash** [comment]
Thanks, it works like a charm...

**Comment by DelfsEngineering** [comment]
@xkjyeah What if I need to update my `markers` array, how will I know what marker to update, of can I just refresh the whole array with some type of `getMarkersArray() ` like function?

**Comment by supermavster** [comment]
Thanks @xkjyeah, in conclusion: 

The 'HTML':

```vue
<p>Coords: {{ markerSelected }}</p>
<GmapMarker
      :position="marker"
      :clickable="true"
      :draggable="true"
      @dragend="getMarkerPosition($event)"
  />
```
And the Data:
```vue
export default {
  data () {
    return {
      marker: { lat: XXXX, lng: XXX },
      markerSelected: {}
    }
}
```
And the methods: 

```vue
methods: {
      getMarkerPosition (event) {
            this.markerSelected = {
                  lat: event.latLng.lat(),
                  lng: event.latLng.lng()
            }
      }
}
```

**Comment by mahmoudhaggag641** [comment]
How get address name of this?
