### ISSUE TITLE
Newbie question: reactvity on lat/lng

### ISSUE THREAD

**Issue by adavie1** [xkjyeah/vue-google-maps#112]
Hi, I've looked around the issues, but I can't seem to find what I'm doing wrong. This is my code:

```
              <gmap-map :center="{lat:site.latitude, lng:site.longitude}"
              :zoom="15" map-type-id="terrain" style="width: 100%; height: 321px">
              <gmap-marker :position="{lat:site.latitude, lng:site.longitude}"
              :clickable="true" :draggable="true"
              @click="center={lat:site.latitude, lng:site.longitude}">
              </gmap-marker>
             </gmap-map>
```
However, when I change the `site.lattitude` or `site.longitude` values in an input, the map position, marker etc. don't change.

What am I missing?
Thanks in advance.

**Comment by xkjyeah** [comment]
You have to show us your code, bro.

**Comment by adavie1** [comment]
Ha ha ha!  That's all the code there is! Oops! I need to implment some methods?

I guess I assumed that would be handled in the component.

Thanks for taking the trouble to answer such mundane questions.

**Comment by xkjyeah** [comment]
I need to see the Javascript part of it. For reactivity to work in Vue, you
need to predefine the `site` attribute in the `data` section.

**Comment by adavie1** [comment]
Here you go:

```
  data () {
    return {
      site: {
        .... Removed items for clarity
        country: 'Malaysia',
        localCouncil: '',
        latitude: 1.5505000000,
        longitude: 103.4010200000,
        .... more data items below.
```
That's what I have.
Is the issue with the way I'm handling the numeric values? In my other code, I treat them as text and then use Number(...) to convert.

However, here, because I have a numeric input, I'm treating them as the default JavaScript number type.

**Comment by xkjyeah** [comment]
Might be the &lt;input> acting up.

Are you using v-model? Have you tried:
```vue
<input type="number" :value="v" @input="v = parseFloat($event.target.value)" />
```

**Comment by adavie1** [comment]
I'm using the element-ui el-input component. Let me see if I can do that. I'll replace `Number(...)` with `parseFloat`.

Yes, I'm using the `:model` value for the inputs.

**Comment by xkjyeah** [comment]
Note that for custom components (i.e. including element-ui el-input) you should instead write:
```js
v = parseFloat($event)
```

**Comment by adavie1** [comment]
Thanks, but I'm not clear where to put that code... I do apologise for the simple questions, I'm picking all this up in bits and pieces. Thanks for your patience.

It's the $event part that I don't follow.

Won't this acheive the same result: `"{lat: parseFloat(site.latitude), lng: parseFloat(site.longitude)}"`

**Comment by xkjyeah** [comment]
Both will work. Except:

```vue
<el-input type="number" :value="v" @input="v = parseFloat($event)" />
```

will ensure that the latitude is always a number

**Comment by adavie1** [comment]
Issue was on my side- I'd wrapped the el-input inside another component, didn't notice until much later that the values weren't being updated.  Using standard el-inputs works.

```
<gmap-map id="newSiteMap" :center="{lat: Number(site.latitude), lng: Number(site.longitude)}"
     :zoom="10" map-type-id="terrain" style="width: 100%; height: 321px">
     <gmap-marker :position="{lat: Number(site.latitude), lng: Number(site.longitude)}" :draggable="false">
      </gmap-marker>
</gmap-map>
```

This code works perfectly.
