### ISSUE TITLE
css source maps being injected into <head>

### ISSUE THREAD

**Issue by magicspon** [xkjyeah/vue-google-maps#113]
Hello,

After compiling my vue app in production mode, i've noticed that vue google maps is injecting a load of source map stuff into my <head>

any thoughts on removing this?

```
<style type="text/css">
.vue-map-container {
  position: relative;
}
.vue-map-container .vue-map {
  left: 0; right: 0; top: 0; bottom: 0;
  position: absolute;
}
.vue-map-hidden {
  display: none;
}

/*# sourceURL=/Users/XXXXX/websites/XXXXXX/node_modules/vue2-google-maps/dist/components/map.vue?e1f76d12 */
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjoz.....*/</style>
```

**Comment by xkjyeah** [comment]
Where would you prefer it to be injected?

This is the default behaviour of the vue-loader in webpack.

**Comment by xkjyeah** [comment]
Oh sorry, I read that wrong. Let me check it again.

**Comment by xkjyeah** [comment]
I'm not entirely sure this is a vue Google maps issue. The source maps you show here were generated based on the paths in your system, so it seems that you forgot to turn off source maps in webpack.

**Comment by magicspon** [comment]
Yup... right you are...
