### ISSUE TITLE
Centering the map doesn't work when updating inner properties

### ISSUE THREAD

**Issue by asselin** [xkjyeah/vue-google-maps#116]
Because of the call to `latlngChangedHandler()` in the watch for `center`, setting the `center` prop is always ignored.  Removing the call to `latlngChangedHandler()` fixes the problem.

If a demo is required, please let me know.

**Comment by xkjyeah** [comment]
Yes, please provide a demo

**Comment by asselin** [comment]
I started with the test-map-center example, and found that my description is a bit wrong.

This works:

```
          changeCenter() {
            this.changingCenter = {
              lat: 1.38 + Math.random() * 0.3,
              lng: 103.8 + Math.random() * 0.1
            };
          },
```

This fails on 2.3.2 and 2.1.6:

```
          changeCenter() {
            this.changingCenter.lat = 1.38 + Math.random() * 0.3;
            this.changingCenter.lng = 103.8 + Math.random() * 0.1;
          },
```

I'll update the issue description to more clearly reflect the real problem.

**Comment by xkjyeah** [comment]
Do you have the context? I'm interested in the data() section

**Comment by asselin** [comment]
@xkjyeah Sorry for not being clear above--- I was able to make a failing example by taking your test-map-center example, and changing the `changeCenter` like above.  I left everything else exactly the same in the example.

**Comment by asselin** [comment]
Looks like this behavior of Vue is by design.  See the Note under https://vuejs.org/v2/api/#vm-watch

> Note: when mutating (rather than replacing) an Object or an Array, the old value will be the same as new value because they reference the same Object/Array. Vue doesn’t keep a copy of the pre-mutate value.

**Comment by asselin** [comment]
@xkjyeah Ping. Were you able to repro, or do you want me to setup a github repo with test case?  Do you want a PR that removes that call to `latlngChangedHandler`?

**Comment by xkjyeah** [comment]
Hi Andre,

Thanks for helping. I'm happy to merge in a PR that removes
latlngChangedHandler.

Thanks!

**Comment by xkjyeah** [comment]
Thanks for reporting the issue and submitting the PR!
http://xkjyeah.github.io/vue-google-maps/test-map-center-twoway.html
