### ISSUE TITLE
maptypeid_change event is not triggered the first time

### ISSUE THREAD

**Issue by Kasheftin** [xkjyeah/vue-google-maps#117]
How to reproduce:

* Go to the repo's example http://xkjyeah.github.io/vue-google-maps/all-components.html;
* Notice that the map type is "terrain";
* Click on the "satellite" button at the top left corner of the map;
* Map appearance changes, but the "map type" selector at the Map Information tab leaves "terrain". `@maptypeid_change` event is not triggered;
* All consequent maptypeid_change events runs successfully, the error appears only the first time after page load.

**Comment by xkjyeah** [comment]
This should be fixed now! If it isn't reopen the issue.

Thanks for reporting! Sorry for the delay in fixing -- I'm not using this package actively at work, so it's hard to justify working on it on weekdays.

Example: http://xkjyeah.github.io/vue-google-maps/maptypeid.html
