### ISSUE TITLE
Ability to disable the default Google Map UI and set specific control options?

### ISSUE THREAD

**Issue by Squidies** [xkjyeah/vue-google-maps#120]
My apologies if this is documented somewhere else, but is there a way to disable the default Google Map UI and add/disable specific control options? 

https://developers.google.com/maps/documentation/javascript/examples/control-disableUI

https://developers.google.com/maps/documentation/javascript/examples/control-options

**Comment by FPierre** [comment]
The following code make the job:

```js
<gmap-map :center=' { lat: 0, lng: 0 }' :zoom='6' :options='{ fullscreenControl: false, mapTypeControl: false }'></gmap-map>
```

**Comment by Squidies** [comment]
Awesome! Works great. Thank you so much. Sorry again, I'm still learning how Vue and components and everything work and are put together.
