### ISSUE TITLE
Custom marker label color

### ISSUE THREAD

**Issue by AdamSweeneyCreative** [xkjyeah/vue-google-maps#122]
Is it possible to customize the color of a marker label? Using the Google Maps API, you can set the label as an object like so:

label: {
    text: 'A',
    color: 'white',
  }

But vue2-google-maps only accepts a string, so it appears you can only edit the text, but not the text color.

**Comment by xkjyeah** [comment]
Actually there isn't a type specification on the marker label (https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/components/marker.js#L32)

Could you try passing in an object and see if it works? Thanks

**Comment by sweeneycreative** [comment]
Ah yes, it works, thank you!

**Comment by PedroTiagoSimao** [comment]
Hi!

Shouldn't this set the markers label?

```
markers: [{
            position: {
              lat: 39.365620,
              lng: -9.218909
            },
            label: "1",
            infoText: 'Marker #1'
          },
```

Thanks!

**Comment by pakcybershagufta** [comment]
> Hi!
> 
> Shouldn't this set the markers label?
> 
> ```
> markers: [{
>             position: {
>               lat: 39.365620,
>               lng: -9.218909
>             },
>             label: "1",
>             infoText: 'Marker #1'
>           },
> ```
> 
> Thanks!

Thank you so much.it work(Y)cheers

**Comment by Arslan038** [comment]
How we can change label background-color and its position. Label is in center by default ? I want to move it on top with some background and border-radius. I am using vue2-google-maps.

Thanks
