### ISSUE TITLE
Two-way binding in map center does not work

### ISSUE THREAD

**Issue by Kasheftin** [xkjyeah/vue-google-maps#126]
Just take a look at this example: http://xkjyeah.github.io/vue-google-maps/all-components.html
If we drag the map around, `Map center latitude` and `Map center longitude` input values change consequently.
But if we change input values, map does not  change it's center, although updateMapCenter event triggers and component's center variable changes.

**Comment by xkjyeah** [comment]
Fixed in http://xkjyeah.github.io/vue-google-maps/test-map-center-twoway.html (v0.7.7)

`npm install vue2-google-maps@latest` to get it.
