### ISSUE TITLE
Single infowindow for multiple markers?

### ISSUE THREAD

**Issue by ashtonlance** [xkjyeah/vue-google-maps#127]
Hi,

I know that there's an example in which you are using 1 infowindow for 3 markers. I'd like to do something similar but for a dynamic amount of markers - my markers are being pulled from a database that are user-submitted.

Do you have some example code to show how this could be done?

**Comment by xkjyeah** [comment]
```html
<gmap-infowindow :position="selectedMarker.latlng"
    v-if="selectedMarker">
       {{selectedMarker.someData}}
</gmap-infowindow>
<gmap-marker v-for="marker in markers" @click="selectedMarker = marker" :position="marker.latlng" />
```

**Comment by ashtonlance** [comment]
Aha! This worked perfectly. 

Thanks!
