### ISSUE TITLE
How to automatically center the map when there are multiple marker?

### ISSUE THREAD

**Issue by godbug** [xkjyeah/vue-google-maps#13]
The answer should be to see the use of `fitBounds`, but I do not know how to use the Vue components.

http://stackoverflow.com/questions/15719951/google-maps-api-v3-auto-center-map-with-multiple-markers

Can you add an example?

**Comment by xkjyeah** [comment]
Hi, here's an example:

http://xkjyeah.github.io/vue-google-maps/basic-map-functions.html

You can just view the source code!

**Comment by godbug** [comment]
@xkjyeah Thank you so much!

**Comment by fuoridallarete** [comment]
This doesn't work for me.
