### ISSUE TITLE
How can i use google.maps.Geocode ?

### ISSUE THREAD

**Issue by mdeprezzo** [xkjyeah/vue-google-maps#132]
Hi guys,
i'm using this package, to rendering map by address. But i'm not able to use geocode, because inside my component, google is undefined ? But if i remember, the libraries that i need to use must be loaded during the installing right ? What am i missing ?

**Comment by xkjyeah** [comment]
1. When you load the library:
```js
Vue.use(VueGoogleMaps, { load: {key: <KEY>, libraries: <geocode library here> }})
```

2. Before calling the geocode library, wait for it to load:
```js
VueGoogleMaps.loaded().then(() => { google.maps.{...} })
```

**Comment by mdeprezzo** [comment]
I see this error right now, after using the code above:

> WEBPACK_IMPORTED_MODULE_1_vue2_google_maps__.loaded is not a function

**Comment by xkjyeah** [comment]
oops, sorry, drop the brackets after loaded.

`VueGoogleMaps.loaded.then(...)`

**Comment by mdeprezzo** [comment]
Oh right now works fine, and i forgot, i'm sorry, that i can use also 

`this.$refs.gmap.$mapCreated.then(() => {`

thanks for this porting man :dancing_men:

**Comment by guyver-dash** [comment]
@mdeprezzo @xkjyeah I'm already on this code `this.$refs.gmap.$mapCreated.then(() => {
            console.log(google.maps)
          })` I can console.log the result. See screen shot  but I don't know how to do a request will I used `axios`? If you can give me simple example that would really help. Thanks.

![capture](https://user-images.githubusercontent.com/10149942/27893433-3b0aa014-6238-11e7-81f3-e16f8d6c5b4c.PNG)

**Comment by guyver-dash** [comment]
I found this example... 
```
this.$refs.gmap.$mapCreated.then(() => {
            var geocoder = new google.maps.Geocoder();

             var address = "Dublin";

              geocoder.geocode( { 'address': address}, function(results, status) {

                if (status == google.maps.GeocoderStatus.OK) {
                  var latitude = results[0].geometry.location.lat();
                  var longitude = results[0].geometry.location.lng();

                  console.log(latitude)
                  // initialize(latitude,longitude);

                          } 

                  });
          })
```

**Comment by notflip** [comment]
> I found this example...
> 
> ```
> this.$refs.gmap.$mapCreated.then(() => {
>             var geocoder = new google.maps.Geocoder();
> 
>              var address = "Dublin";
> 
>               geocoder.geocode( { 'address': address}, function(results, status) {
> 
>                 if (status == google.maps.GeocoderStatus.OK) {
>                   var latitude = results[0].geometry.location.lat();
>                   var longitude = results[0].geometry.location.lng();
> 
>                   console.log(latitude)
>                   // initialize(latitude,longitude);
> 
>                           } 
> 
>                   });
>           })
> ```

Note that $mapCreated has been renamed to $mapPromise

**Comment by websitevirtuoso** [comment]
I could make it work
```
this.$gmapApiPromiseLazy().then(() => {
            const geocoder = new google.maps.Geocoder()

            const address = 'Dublin'

            geocoder.geocode({ address }, function (results, status) {
              if (status === 'OK') {
                const latitude = results[0].geometry.location.lat()
                const longitude = results[0].geometry.location.lng()

                console.log(latitude)
                console.log(longitude)
                // initialize(latitude,longitude);
              }
            })
          })
```

**Comment by RobbeR** [comment]
Old and closed issue, but helped me a lot. Here's my working solution with Vue3:

```<template>
  <div class="w-full relative">
    <GMapMap
      ref="myMap"
      class="rounded-lg overflow-hidden"
      :center="{lat: 0, lng: 0}"
      :zoom="12"
      :options="{
        zoomControl: false,
        mapTypeControl: false,
        scaleControl: false,
        streetViewControl: false,
        rotateControl: false,
        fullscreenControl: false,
      }"
      map-type-id="roadmap"
      style="width: 100%; height: 200px"
    />
  </div>
</template>

<script setup>
  import { ref, onMounted, defineProps, reactive, watch } from 'vue'
  import silverMapStyle from '@/misc/mapStyles/silver.json'
  const myMap = ref(null)

  const props = defineProps({
    location: {
      type: String,
      required: true
    }
  })

  const state = reactive({
    location: props.location ? props.location : null,
    mapObject: null
  })

  function geocodeAndPositionMap() {
    if(!state.location || !state.mapObject) return;

    var geocoder = new window.google.maps.Geocoder();
    const address = props.location
    geocoder.geocode({ address }, function (results, status) {
      if (status === 'OK') {
        const latitude = results[0].geometry.location.lat()
        const longitude = results[0].geometry.location.lng()
        state.mapObject.setCenter(new window.google.maps.LatLng(latitude, longitude))
      }
    })
  }

  onMounted(() => {
    myMap.value.$mapPromise.then((gmap) => {
      state.mapObject = gmap
      gmap.setOptions({ styles: silverMapStyle });
      geocodeAndPositionMap()
    })
  })

  watch(() => props.location, () => {
    geocodeAndPositionMap()
  })
</script>```
