### ISSUE TITLE
Variable API Key? Or set API key from Vue instance?

### ISSUE THREAD

**Issue by admcfajn** [xkjyeah/vue-google-maps#135]
My goal is to dynamically set the API key used by VueGoogleMaps.

VueGoogleMaps currently loads with a static-key in main.js

I would like to set the key from elsewhere in the app. To avoid calling google-maps api every time the app loads.

Using webkit 2, I have a main.js which is basically a config file and instantiates Vue on my main controller App.vue 

Using vue-loader: https://github.com/vuejs/vue-loader

Currently, in main.js I have the following:

    Vue.use(VueGoogleMaps, {
      load: {
        key: 'mySecretKey',
      },
    });

    new Vue({
      el: '#app',
      template: '<App/>',
      components: { App },
      router,
    });

Any help is much appreciated.

I'm looking for a way to set the key from within my Vue instance. 

Or, load VueGoogleMaps from within my Vue instance. 

Either would suffice, I just need to avoid calling google-maps api every time the app is loaded.

**Comment by admcfajn** [comment]
Closing this Question, because I think I can install a different way as explained in the parent-repo's documentation: https://github.com/GuillaumeLeclerc/vue-google-maps#installation

**Comment by notflip** [comment]
Found a way to do it.

Install the plugin without specifying options

```
Vue.use(VueGoogleMaps);
```

In your component

```
beforeMount () {
    VueGoogleMaps.loadGmapApi({
      key: 'your-g-api-key,
      libraries: 'places'
    })
  },
```

**Comment by admcfajn** [comment]
Very similar to the route I took, yes! :)

**Comment by admcfajn** [comment]
Hi @notflip thanks for asking! I was able to come to a similar solution. 

I ended up using `Vue.use( VueGoogleMaps, { load: { key: 'your-g-api-key' } } );` to get the ball rolling. 

& then from my components I could use... 
`import { loaded } from 'vue2-google-maps';` 
& then: 
`settings = new Vue({` as an event-bus 
& finally: 
`loaded.then(() => { settings.this = { that: 'the other thing' }` to modify props in a child component. 

Thanks for reviving this thread, I'd been meaning to followup on it :)

**Comment by kdamiani** [comment]
Hi @admcfajn 
thanks for opening this topic! I have the same problem right now, would it be possible to post the whole example of your working code here? 

thank you

many greetings
kevin

**Comment by eliecer2000** [comment]
Thanks, I had the same problem and I solved it like this:

app.js

```
// Import Vue
import Vue from 'vue';
import * as VueGoogleMaps from 'vue2-google-maps';

// do not place any value - it will give you the error that the component is already loaded
Vue.use(VueGoogleMaps) 
// Init App
new Vue({
  el: '#app',
  // Register App Component
  components: {
    app: App
  },
  render: h => h(App)
})
```
map.vue

```
<template>
  <page>
    <GmapMap
      :options="{
      }"
      ref="mapa"
      :center="center"
      :zoom="zoom"
      map-type-id="roadmap"
      style="width: 100%; height: 500px;"
    >
    </GmapMap>
  </page>
</template>
<script>
import _ from "lodash";
import { loadGmapApi, gmapApi } from "vue2-google-maps";

export default {
  components: {
  },
  data() {
    return {
      center: {
        lat: 0,
        lng: 0
      },
      zoom: 18,
    };
  },
  computed: {
    google: gmapApi,
  },
  beforeMount() { 
    loadGmapApi({
        key: "<api key code>",
        libraries: "places",
        region: "pa",
        language: "es"

    });
  },
};
</script>
<style>
</style>

```

Thanks for the help.
