### ISSUE TITLE
Possible to add OverlayView ?

### ISSUE THREAD

**Issue by mickspecial** [xkjyeah/vue-google-maps#136]
Wanting to add some animations to my icons 

https://www.sitepoint.com/animated-google-map-markers-css-javascript/

How can I implement this ?

```
var myoverlay = new google.maps.OverlayView();
    myoverlay.draw = function () {
        this.getPanes().markerLayer.id='markerLayer';
    };
myoverlay.setMap(map);
```

Thanks

**Comment by xkjyeah** [comment]
Similar to
https://github.com/xkjyeah/vue-google-maps/blob/vue2/examples/overlay.html

(View source to see how it's implemented)

And when you've implemented it, feel free to make a PR with the new
component :)

**Comment by KaisNeffati** [comment]
Hello  @xkjyeah 
Please , could you specify how to use the overlay in case of using a vue2 component !!

```
<template>
 <gmap-map ref="map"
                    :center="{lat:36.804449, lng:10.182280}"
                    :zoom="15"
                    map-type-id="roadmap"
                    style="width: 33%; height: 79%; position: fixed"
          >
            <ground-overlay v-if="mapLoaded" source="/statics/Profile_avatar_placeholder_large.png" :bounds="{
            north: 1.502,
            south: 1.185,
            east: 104.0262,
            west: 103.5998}" :opacity="0.5">
            </ground-overlay>
          </gmap-map></template>
<script>
export default {
  data () {
    return {}
  }
}
</script>

<style>
</style>
```

Thanks

**Comment by sdzhurova** [comment]
> 103.5998

Hello @KaisNeffati

Did you find a solution on how to use **ground-overlay** inside a  **gmap-map** with vue2-google-maps.

I am trying to implemented in my Vue project but get the error:
> Unknown custom element: <ground-overlay> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I tried everything but The overlay is not visible, just my map.

Thanks

**Comment by KaisNeffati** [comment]
Hello @sdzhurova ,

Unfortunately , I think there is no way to do it using ground-overlay as i know !!
As a workaround you can try this: 

1. Download any svg you'd like to work with
2. Include your Dom in the svg file
3.  Create a vue component and add the svg code into the template :
`<template><svg ...>..<yourDom (id or class='domId') >...</yourDom>.</svg></template>`
4.  Use the identifier to controle yourDom object
5.  Include your component anywhere 

Thanks

**Comment by tsworman** [comment]
@sdzhurova You need to make the ground-overlay component available by creating it within your current component.

```

    <GmapMap ref="map"
      :center="{lat:42.300857, lng:-83.698202}"
      :options=this.mapOptions
      class="google-map"
      id="map"
    >
    <ground-overlay
        source="https://i.imgur.com/Jyech6X.png" 
        :bounds="{
          north: 42.30283061090956,
          south: 42.29889440158543,
          east: -83.69653444907374,
          west: -83.70049861111448
        }" 
      :opacity=".6">
    </ground-overlay>
    </GmapMap>

import { MapElementFactory } from 'vue2-google-maps'

var Vue = require('vue').default
Vue.component('ground-overlay', MapElementFactory({
        mappedProps: {
          'opacity': {}
        },
        props: {
          'source': {type: String},
          'bounds': {type: Object},
        },
        events: ['click', 'dblclick'],
        name: 'groundOverlay',
        ctr: () => google.maps.GroundOverlay,
        ctrArgs: (options, {source, bounds}) => [source, bounds, options],
      }))

```

After that the component is available and at runtime it appears as a child (through the inspector) of the gmap-map and renders properly.

**Comment by eregnier** [comment]
Hey guys. Try this component https://github.com/eregnier/vue2-gmap-custom-marker
Hope this help

**Comment by HelloLogan** [comment]
Add this into main.js
```
import * as VueGoogleMaps from 'vue2-google-maps'

Vue.component('ground-overlay', VueGoogleMaps.MapElementFactory({
  mappedProps: {
    'opacity': {}
  },
  props: {
    'source': { type: String },
    'bounds': { type: Object }
  },
  events: ['click', 'dblclick'],
  name: 'groundOverlay',
  ctr: () => window.google.maps.GroundOverlay,
  ctrArgs: (options, { source, bounds }) => [source, bounds, options]
}))
```
it works in my project.

**Comment by bonatoc** [comment]
Thanks @tsworman, 

Works like a charm.
