### ISSUE TITLE
Loader issue with packages

### ISSUE THREAD

**Issue by adrianwang** [xkjyeah/vue-google-maps#138]
error  in ./node_modules/vue2-google-maps/dist/components/map.vue

Module parse failed: /Users/adrian/apps/highschooltutors/node_modules/vue2-google-maps/dist/components/map.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|   <div class="vue-map-container">
|     <div ref="vue-map" class="vue-map"></div>

**Comment by xkjyeah** [comment]
Show me your webpack.config.js

**Comment by adrianwang** [comment]
Actually, thanks for the reply. the issue was with webpack config. Resolved

**Comment by justin-nodeboy** [comment]
How did you resolve this?

**Comment by silvanm** [comment]
My case (using https://github.com/caiobiodere/cordova-template-framework7-vue-webpack) was the following: In `webpack.config.js` had to replace

    {test: /\.vue$/, exclude: /node_modules/, loader: 'vue-loader', options: {loaders: {js: {loader: 'babel-loader', options: {presets: ['env'], plugins: ['transform-object-rest-spread']}}}}},
             
with

    {test: /\.vue$/, loader: 'vue-loader', options: {loaders: {js: {loader: 'babel-loader', options: {presets: ['env'], plugins: ['transform-object-rest-spread']}}}}},
