### ISSUE TITLE
Newbie question: handling marker's z-index?

### ISSUE THREAD

**Issue by Orijinn** [xkjyeah/vue-google-maps#141]
Hi,

How can I alter marker's z-index?

More specificially, I have a map with clusters and markers. When two markers overlap, and one of them is clicked, I want to bring in on front.
I need to call marker.setZIndex() but I cannot find a way to obtain the "real" marker - and I'm not sure I want to since I'd like to stay with Vue objects.

What is the correct solution?

thanks

**Comment by cuongdevjs** [comment]
what's solution? how to set z-index in marker
