### ISSUE TITLE
Expose anchor property of marker class

### ISSUE THREAD

**Issue by Fermain** [xkjyeah/vue-google-maps#143]
Using vanilla google maps API, it is possible to access an anchor property for each marker that allows you to adjust the location of the icon, without changing it's position value. This is very useful in cases where a custom icon does not point downwards directly at the location, but rather surrounds it.

This does not yet seem to be exposed

**Comment by Fermain** [comment]
This is not an issue with the library, but my own ability to read API documentation. For anyone else trying to set a custom anchor point - you can do this within the object passed as the :icon prop.

`icon: {url: '/your-icon.png', anchor: new google.maps.Point(40, 40),}`

**Comment by valeriosillari** [comment]
got the same issue. any possible update? it would be nice to can pass this anchor options without the need to expose the google object
