### ISSUE TITLE
Got an empty map, but removed the style that is worked.

### ISSUE THREAD

**Issue by catchkuo** [xkjyeah/vue-google-maps#145]
HI I follow the readme step to use the vue2-google-maps in vue file, but i always get empty page.
I check html code and find a div element ,which has a "position: relative" in style .
When i remove it. i can see the map, Is there something wrong?

< div class= "vue-map" style=" **position: relative**; overflow: hidden; " >

**Comment by catchkuo** [comment]
Attach my code. Thanks.
< template>

  < gmap-map
    :center="center"
    :zoom="17" >
    < gmap-marker
      :key="index" 
      v-for="(m, index) in markers"
      :position="m.position"
      :clickable="true"
      :draggable="true"
      @click="center=m.position">

< /gmap-marker >
  < /gmap-map >
  
</ template >

< script >


import * as VueGoogleMaps from 'vue2-google-maps/dist/vue-google-maps-stubbed';
  import Vue from 'vue';

  Vue.use(VueGoogleMaps, {
	  installComponents: true,
    load: {
      key: 'AIzaSyDTifMVwJHYlkTcVwUYJpyWhmurC...',
      v: '3.26',
      // libraries: 'places', 
    }
  });


  export default {
	
	components : {
    	VueGoogleMaps
  	},
    data () {
      return {
        center: {lat: 25.026274, lng: 121.523267},
        markers: [{
          position: {lat: 25.026274, lng: 121.523267}
        }],
		
		
      }
    }
  }
< /script>

**Comment by xkjyeah** [comment]
Hi,

Forgot to specify: you should set the width and height of your map element,
e.g.

<GmapMap style="width: 500px; height: 500px">

**Comment by catchkuo** [comment]
HI I tried. it still not worked.The style is displayed above element.
-----------
   < gmap-map
    :center="center"
    :zoom="17"
	style="width: 500px; height: 300px"
  >
-----------
< div class="vue-map-container" style="width: 500px; height: 300px;">
	< div class="vue-map" style="position: relative; overflow: hidden;">

**Comment by catchkuo** [comment]
HI Thx for your answer.i define the css and it worked.
.vue-map-container {
  width: 100%;
  height:100%;
}
.vue-map-container .vue-map {
  width: 100%;
  height:100%;
}

**Comment by petegore** [comment]
Worked for me to into [this ](https://github.com/xkjyeah/vue-google-maps/issues/298) issue. 
Thanks

**Comment by jebarjonet** [comment]
This issue comes from there https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/components/map.vue#L16

The code in `<style>` tag is supposed to be processed by the compiler when exported. Unfortunately it is not, so the very same tag is present even in the `dist` (this is a mistake). Therefore your own transpiler is taking charge of it. Mine is hashing local `<style>` modules classes and are supposed to be used like `:class="$style.myclass"` instead of `class="myclass"`, so it is like no classes were applied at all!

So you are supposed to copy/paste this yourself:
```css
.vue-map-container {
  position: relative;
}

.vue-map-container .vue-map {
  left: 0; right: 0; top: 0; bottom: 0;
  position: absolute;
}

.vue-map-hidden {
  display: none;
}
```

**Comment by afrazahmmad** [comment]
I tried all above solutions but map is still not showing
