### ISSUE TITLE
Google Places Autocomplete - Pick first result on Enter key

### ISSUE THREAD

**Issue by omarma** [xkjyeah/vue-google-maps#147]
Hey !
Thank you for this great package !
I was wondering if there is any way I can select the the first result suggested when I press "enter" key ?

Thank's for your answer

**Comment by adrianwang** [comment]
https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#selectfirstonenter--boolean

**Comment by omarma** [comment]
@adrian999999 thank you !

**Comment by nniicc** [comment]
Hey, is there a way to stop the parent event from being called?

I have a form and the autocomplete inside the form so if i press enter it always submits the form

```html
<form action="search" method="GET">
<gmap-autocomplete
    :types="['(cities)']"
    class="_inputForm--row-input"
    :select-first-on-enter="true"
    @place_changed="setFromPlace">
</gmap-autocomplete>
</form>
```

**Comment by xkjyeah** [comment]
@keypress.enter.stop?

**Comment by vAhyThe** [comment]
@xkjyeah the link dont work anymore :/
