### ISSUE TITLE
Nuxt implementation doesn't seem to be working

### ISSUE THREAD

**Issue by royscheeren** [xkjyeah/vue-google-maps#151]
In my `nuxt.config` I have the following:

```
plugins: [
    { src: '~plugins/vue2-google-maps' }
  ]
```
and in my plugins folder a file vue2-google-maps:
```
import Vue from 'vue'
import * as VueGoogleMaps from 'vue2-google-maps/dist/vue-google-maps-stubbed'

Vue.use(VueGoogleMaps)
```

Yet when loading the page I get the following error:
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

Has anyone been able to actually get it working with Nuxt?

**Comment by arenddeboer** [comment]
The hydration warning could also come from another issue. I had this warning when inserting html with v-html.

You should probably also load an API key:
```
Vue.use(VueGoogleMaps, {
  load: {
    key: 'my-key'
    // libraries: 'places',   // If you want to use places input
  }
})
```

But I don't think a missing API key will give that warning.

**Comment by ImTheDeveloper** [comment]
@royscheeren this will be a client side library only within your plugin you need to set SSR false to stop server side rendering. You will then also need to fix the fact the server doesnt need to reflect the component: https://alligator.io/vuejs/hide-no-ssr/

I wrap my gmap component with the no-ssr tag and voila!

**Comment by xkjyeah** [comment]
Try this solution. In your plugin, write:
```js
import Vue from 'vue'
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'

Vue.use(VueGoogleMaps, {...})
```
