### ISSUE TITLE
How to attach to domready event

### ISSUE THREAD

**Issue by philtim** [xkjyeah/vue-google-maps#155]
Hi,

in order to style the InfoWindow I've extended `InfoWindowImp.js`  by adding this line into the method `createInfoWindow`:

```google.maps.event.addListener(this.$infoWindow, 'domready', function () {...}```

I wonder if that could be solved in smarter way rather than monkey patching you code base?

**Comment by xkjyeah** [comment]
Nope. Probably not, unless you inspect all the classes that are on the info window. The Google Maps API doesn't allow it, so I don't allow it.
