### ISSUE TITLE
Nested <vue-map> height=0.

### ISSUE THREAD

**Issue by PabloCOVES** [xkjyeah/vue-google-maps#157]
Hi!

It's pretty much all in the title.
When using the basic examples the map isn't showing.

By manually setting the `vue-map` tag `height` property to 100% up, the map appears.

Might be a known behavior?
My solution was to put `<style> .vue-map { height:100%; } </style>` in my `index.html` but it's a bit ugly.

**Comment by oppianmatt** [comment]
we put `style="width: 100%; height: 500px; will-change: transform; transform: translateZ(0);"` on our `gmap-map`

i.e.:

```
  <gmap-map
        v-cloak
        :center="center"
        :zoom="zoom"
        :options="{scaleControl: true, scrollwheel: mapScroll}"
        @center_changed="updateCenter"
        @dragend="dragEnd"
        @zoom_changed="zoomChanged"
        ref="desktopmap"
        style="width: 100%; height: 500px; will-change: transform; transform: translateZ(0);"
  >
```

It's what the README examples use. Have you tried that?

**Comment by PabloCOVES** [comment]
Worked well, many thanks!
