### ISSUE TITLE
Include Traffic Layer

### ISSUE THREAD

**Issue by cupin06** [xkjyeah/vue-google-maps#163]
I want to ask how to display traffic on the map. Since this plugin doesn't have traffic layer component for Vue js I tried to initialize manually but got an error.

`Cannot read property 'TrafficLayer' of undefined`

```
    let trafficLayer = new this.$refs.mymap.TrafficLayer;
    trafficLayer.setMap(this.$refs.mymap);
```

**Comment by xkjyeah** [comment]
1. new Google.maps.TrafficLayer
2. <gmap-map ref=hmmm>

**Comment by cupin06** [comment]
I tried code below and not receive any error but the traffic layer didn't appear on map. Also I received this error `"ReferenceError: google is not defined"` when I put the code in the `mounted`. 

```
let trafficLayer = new google.maps.TrafficLayer;

trafficLayer.setMap(this.$refs.dashboardmap.$object);
```

**Comment by xkjyeah** [comment]
Try google with the small g. Sorry, it's because I type the replies on my
phone

**Comment by xkjyeah** [comment]
For the record:

```js
new google.maps.TrafficLayer
```
```html
<GmapMap ref="map">
```
