### ISSUE TITLE
How to add autocomplete location search box

### ISSUE THREAD

**Issue by vaishali-ghayal** [xkjyeah/vue-google-maps#164]
Hi,

I want to add a multiple locations on one map and also need to add autocomplete location search box.
Do you have any example how to do this?

I am using Vue 2.3.3 and vuetify 0.13.1.

**Comment by xkjyeah** [comment]
http://xkjyeah.github.io/vue-google-maps/autocomplete.html

**Comment by vaishali-ghayal** [comment]
@xkjyeah Thanks a lot
