### ISSUE TITLE
delay for google search place 

### ISSUE THREAD

**Issue by iammilaad** [xkjyeah/vue-google-maps#165]
hi xkjyeah,
how can make a delay for google search place ? create a trick for handle OVER_QUERY_LIMIT response

**Comment by xkjyeah** [comment]
unfortunately you cannot use the built-in Google Autocomplete for this.

When querying you could use lodash.throttle / lodash.debounce. Check out
the lodash library

**Comment by iammilaad** [comment]
thank you xkjyeah

**Comment by janein** [comment]
@miladbruce where did you manage to add a throttle? I can't figure out where to put it, as the component triggers the call itself.

**Comment by dkearns15** [comment]
Hey @xkjyeah and @miladbruce 
Just wanted to follow up on this one. How did you manage to add a throttle/debounce for the autocomplete?
Haven't had much luck myself.
Thanks :)
