### ISSUE TITLE
How to get geocode to get user current adress from lat longs

### ISSUE THREAD

**Issue by samrandhawa4** [xkjyeah/vue-google-maps#166]
Hi please help me out i am looking for a code to get user address from lat longs

**Comment by xkjyeah** [comment]
This is a Google Maps API question.

Answer adapted from https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse

```js
        var geocoder = new google.maps.Geocoder;
        var latlng = {lat: 1.39, lng: 103.8};
        geocoder.geocode({'location': latlng}, function(results, status) {
          if (status === 'OK') {
            if (results[1]) {
              alert(results[1].formatted_address);
            } else {
              window.alert('No results found');
            }
          }
        })
```

**Comment by ereztdev** [comment]
I've found out that it would be better to implement this is via a wrapped Promise.
Any this.* you see will be coming from data(){}, as follows:
```
decodeLatLong() {
                let geocoder = new google.maps.Geocoder();
                let theLocation = this.location;
                let latLong = this.latLong;
                return new Promise(function (resolve, reject) {
                    geocoder.geocode({'address': theLocation}, function (results, status) {
                        if (status === google.maps.GeocoderStatus.OK) {
                            latLong.latitude = results[0].geometry.location.lat();
                            latLong.longitude = results[0].geometry.location.lng();
                        } else {
                            reject(status);
                        }
                    });
                });
            }
```

**Comment by lexjwa** [comment]
getTown (lat, lng) {
      var geocoder = new google.maps.Geocoder();
                var latlng = {lat, lng};
                geocoder.geocode({'location': latlng}, (results, status) => {
                    if (status === 'OK') 
                    `{`
                         console.log(results[0].formatted_address);
                         //Share new found location with parent component,
                         this.$parent.restaurant.address = results[0].formatted_address;
                    }
                });
},

**Comment by lexjwa** [comment]
getTown (lat, lng) {
       var geocoder = new google.maps.Geocoder();
                 var latlng = {lat, lng};
                 geocoder.geocode({'location': latlng}, (results, status) => {
                     if (status === 'OK') 
                    {
                         console.log(results[0].formatted_address);
                         //Share new found location with parent component,
                         this.$parent.restaurant.address = results[0].formatted_address;
                    }
                });
},

**Comment by websitevirtuoso** [comment]
I could make it work with native nay without additional request via axios. (In my can we dont use any kind of request ay all)

```
decodeLatLong (position) {
      this.$gmapApiPromiseLazy().then(() => {
        // eslint-disable-next-line no-undef
        const geocoder = new google.maps.Geocoder()

        geocoder.geocode({ location: { lat: position.coords.latitude, lng: position.coords.longitude } }, (results, status) => {
          if (status === 'OK') {
            this.getFromAutocomplete(results[0])
          }
        })
      })
    }
```
