### ISSUE TITLE
Get Client Lat & Lng

### ISSUE THREAD

**Issue by fabienchn-zz** [xkjyeah/vue-google-maps#168]
I didn't find anyway to locate the client in the API ? 

I need to get the Latitude and longitude of the client's position to set a marker on the map at his current position.

Is this possible using this API or not ?

**Comment by xkjyeah** [comment]
This feature is not part of this Library.

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by fabienchn-zz** [comment]
Yes, sorry, I didn't know this, thanks a million !
