### ISSUE TITLE
Its possible to show a popup on an click events of an polygon?

### ISSUE THREAD

**Issue by Jefersonnnn** [xkjyeah/vue-google-maps#179]
I'm doing a college project, and I need to show a popup in the click event of the polygons, I have an array of polygons and in each of them has a description

`<gmap-polygon :paths="paths.paths" :editable="true" @click="showDescPolygon(???????)" ref="polygon"></gmap-polygon>`

`data: {
    paths: {
                    
        desc: "this is description",
        paths: [
            {"lat": -26.380, "lng": -48.800},
            {"lat": -26.380, "lng": -48.810},
            {"lat": -26.390, "lng": -48.810},
            {"lat": -26.390, "lng": -48.800}
        ]
    },
},`

**Comment by xkjyeah** [comment]
Does it not work? It should work

**Comment by Jefersonnnn** [comment]
thanks for answering :D
How my method will know which polygon was clicked. To display the correct message for each polygon?.
Because in the examples I just found the markers using the index to reference.

**Comment by Jefersonnnn** [comment]
The click event works, but i can not tell my method which polygon was clicked and display the correct popup/tooltip of that polygon.

**Comment by Jefersonnnn** [comment]
I solved it this way (Use the **v-for**)

my polygons array:

```
 polygonsList: {
                    "polygons": [{
                        desc: "this is description",
                        paths: [
                            {"lat": -26.380, "lng": -48.800},
                            {"lat": -26.380, "lng": -48.810},
                            {"lat": -26.390, "lng": -48.810},
                            {"lat": -26.390, "lng": -48.800}
                        ],
                    },
                        {
                            desc: "this is description 2",
                            paths: [
                                {"lat": -26.480, "lng": -48.880},
                                {"lat": -26.480, "lng": -48.890},
                                {"lat": -26.490, "lng": -48.890},
                                {"lat": -26.490, "lng": -48.880}
                            ],
                        }
                    ]
                },
```



```
        <gmap-polygon v-for="poly in polygonsList.polygons" :paths="poly.paths" :editable="true" @paths_changed="updateEdited($event)"
                      @click="showDescPolygon($event, poly.desc)" ref="polygon"></gmap-polygon>
```

```
showDescPolygon(event, desc) {

                var contentString = desc;
                
                this.infoWindowPos = event.latLng;
                this.infoContent = contentString;

                this.infoWinOpen = true;
            }
```
