### ISSUE TITLE
how find my location in vue2-google-map

### ISSUE THREAD

**Issue by davodaslanifakor** [xkjyeah/vue-google-maps#181]
## I want use  
![map](https://user-images.githubusercontent.com/14367811/28872326-ef5bb90c-779d-11e7-89a5-c85535678921.png)

for  find 
## location
and as well as
## use 
![map](https://user-images.githubusercontent.com/14367811/28872373-1f2ad2a8-779e-11e7-94ec-6414fd83a619.png)

## Please advise which options should I use...
# Tnx....

**Comment by Adavo** [comment]
For geolocation:

**Comment by Adavo** [comment]
For geolocation
`    <gmap-map :center="{lat:currentLocation.lat, lng:currentLocation.lng}" :zoom="17" :options="{disableDefaultUI:true}">`

```
  data() {
    return {
      currentLocation : { lat : 0, lng : 0},
      searchAddressInput: ''
    }
  }

```
```
mounted : function() {
    this.geolocation();
 }

```

```
methods: {
    geolocation : function() {
      navigator.geolocation.getCurrentPosition((position) => {
        this.currentLocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
      });
    }
}
```

You can after add easily a DIV in your ui, hover the gmaps, to launch your geoloc method

```
  <div class="geolocation" v-on:click="geolocation()">
      <img src="../../static/images/geolocation.png" />
    </div>
```

For search your location, same things. Add an input hover your google map

```
    <div class="search">
      <input type="text" v-model="searchAddressInput" v-on:change="searchLocation()"></input>
    </div>
```

and the following methods:

```
searchLocation: function() {
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({'address': this.searchAddressInput}, (results, status) => {
        if (status === 'OK') {
          this.currentLocation.lat = results[0].geometry.location.lat();
          this.currentLocation.lng = results[0].geometry.location.lng();
        }
      });
    }
```

I didn't manage erros in this code to simplify it but you can add some special error message in callback.

**Comment by davodaslanifakor** [comment]
tnx u for answer i test this and report again..

**Comment by rmNyro** [comment]
Hum, how do you get/inject the `google` object for `new google.maps.Geocoder()` to work? You inject the google script on more time separately? As long as you get access to a `Geocoder` instance it's "easy" because you just need to follow the official API doc. @xkjyeah any suggestion or lead on that? May be I'm thinking wrong about that.

**Comment by victorsilent** [comment]
@Adavo love u man <3

**Comment by noobling** [comment]
Thanks this was nice I think this should be added to the docs as well.

**Comment by AbdurRehman26** [comment]
Does this work as two way binding ? when i drag the pointer it does not update the map location

**Comment by mkantautas** [comment]
Can we please have this updated and added in the docs? :+1:

**Comment by xkjyeah** [comment]
@neorganic  The docs are in the code. You can fork it, and add an example to the code and make a PR. Thank you.

**Comment by jonathanschlitt** [comment]
Hello Everyone, after running the code, I'm getting a "google was not defined" error. Is there an import missing? I ca't fix this Issue, because I'm new to VUE.js Thanks for your answers.

**Comment by akation** [comment]
> Hello Everyone, after running the code, I'm getting a "google was not defined" error. Is there an import missing? I ca't fix this Issue, because I'm new to VUE.js Thanks for your answers.

Did you add the line below? and installed the library of course.

 import { gmapApi } from 'vue2-google-maps';

then use  computed property:

computed: {
    google: gmapApi,
  },
