### ISSUE TITLE
Changing autocomplete input styling to vuetify input or select

### ISSUE THREAD

**Issue by ImTheDeveloper** [xkjyeah/vue-google-maps#182]
Hi 

I'm trying to use the auto complete with vuetify library. I see from the documents that there is a root input field https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#autocomplete-class-mixes-in-mapelementmixin

When including the autocomplete in my Vue file I get regular html input field I would like this to be styled and work using the vuetify select input field as shown here:
https://vuetifyjs.com/components/selects (autocomplete is example 5 I believe)
Am I able to change this? Do I need to create my own component and replace your input with my own?

**Comment by ImTheDeveloper** [comment]
Got this working
```

<template>
    <div>
        <v-text-field label="Destination" placeholder="New York City" class="" v-model="starting_address" id="starting_address"></v-text-field>
        {{ $data }}
    </div>
</template>

<script>
export default {
  mounted: function () {
    /* eslint-disable */
    let self = this
    let starting_address_input = document.getElementById('starting_address')
    let starting_address_autocomplete = new google.maps.places.Autocomplete(starting_address_input)
    starting_address_autocomplete.addListener('place_changed', function() {
      let place = starting_address_autocomplete.getPlace();
      self.starting_address_obj = {
       place
      }
    });
  },
  data () {
    return {
      // Destination data items
      starting_address: '',
      starting_address_obj: {},
    }
  },
  methods: {
    initSearch: function (event) {
      console.log('Shots fired!')
    }
  }
}
</script>        

```

**Comment by janhox** [comment]
thanks for your solution! Exactly what I needed as well.

**Comment by Parkseokje** [comment]
You can just use like this
```
<gmap-autocomplete @place_changed="setPlace" class="form-control" style="width: 100%">
</gmap-autocomplete>
```

**Comment by morgler** [comment]
Is there a solution for this yet? Struggling with this!

@ImTheDeveloper simply avoided using `vue-google-maps` altogether and creates his own component (which is tricky, because `google` might not have loaded when the component is mounted).

@Parkseokje's solution doesn't work for me either in vuetify (`form-control` is not a class that styles an element the vuetify way).

So, any solutions? Maybe you you could just provide a slot to add our own input element?

**Comment by thukuwanjiku** [comment]
Thanks @Parkseokje your snippet helped me.
@morgler try this if you're on bootstrap, though I think should work with any other framework.

**Comment by TitanFighter** [comment]
Bootstrap 4.3.1

```
<div>
  <div class="form-group">
    <label>Your location:</label>
    <div>
      <gmap-autocomplete
        ref="autocomplete"
        :select-first-on-enter="true"
        @place_changed="setPlace('autoComplete', $event)"
        class="w-50"
      ></gmap-autocomplete>
      <small id="autocompleteHelp" class="form-text text-muted">Enter country and city</small>
    </div>
  </div>

  <gmap-map
    :center="center"
    :zoom=zoom
    style="width:100%;  height: 400px;"
    :options="gMapOptions"
    @click="setPlace('setMarkerManually', $event)"
  >
    <gmap-marker
      :key="index"
      v-for="(markerPosition, index) in markers"
      :position="markerPosition"
      :clickable="true"
      :draggable="true"
      @click="center=markerPosition"
      @dragend="setPlace('markerDragged', $event)"
    ></gmap-marker>
  </gmap-map>
</div>
```


![image](https://user-images.githubusercontent.com/12687911/58985505-2126e080-87e4-11e9-97ff-2c726a4f81bd.png)

**Comment by DavidHut13** [comment]
@Parkseokje Your solution worked beautifully, adding class="form-control" assigned all of the desired pre built css to googles input field, even in bootstrapVue.

**Comment by Vicmi13** [comment]
Hi,

I found this module 
[vuetify-google-autocomplete](https://www.npmjs.com/package/vuetify-google-autocomplete) 
it was inspired in  Vue Google Autocomplete. And works awesome

**Comment by divyangsolanki** [comment]
Anyone knows how to implement it for mobile application? @TitanFighter @Vicmi13 @ImTheDeveloper
Because in mobile application when i enter character in text field it shows list of places but when i click on any of them then it won't reflect in text field or i can say i can't select from the list.

**Comment by TrendyTim** [comment]
I added a pull request that adds support for specifying a v-text-field (or possibly any other frameworks  input) using scoped named slots

#659

**Comment by dom-velloso** [comment]
It'd be awesome to have this feature working! Any news?

**Comment by AlejandroBelloIglesias** [comment]
> Got this working
> 
> ```
> 
> <template>
>     <div>
>         <v-text-field label="Destination" placeholder="New York City" class="" v-model="starting_address" id="starting_address"></v-text-field>
>         {{ $data }}
>     </div>
> </template>
> 
> <script>
> export default {
>   mounted: function () {
>     /* eslint-disable */
>     let self = this
>     let starting_address_input = document.getElementById('starting_address')
>     let starting_address_autocomplete = new google.maps.places.Autocomplete(starting_address_input)
>     starting_address_autocomplete.addListener('place_changed', function() {
>       let place = starting_address_autocomplete.getPlace();
>       self.starting_address_obj = {
>        place
>       }
>     });
>   },
>   data () {
>     return {
>       // Destination data items
>       starting_address: '',
>       starting_address_obj: {},
>     }
>   },
>   methods: {
>     initSearch: function (event) {
>       console.log('Shots fired!')
>     }
>   }
> }
> </script>        
> ```

It works visually but this is not displaying autocomplete recomendations which forces the user to write the exact literal string to work

**Comment by rezaansarirad** [comment]
.btn-pre {
  margin-top: 50px;
  width: 30%;
  height: 58px !important;
  background-color: #f6f8fc;
  border: none;
  border-radius: 12px;
  font-size: 18px;
}
.pac-target-input {
  padding: 10px;
  width: 100%;
  background-color: #f6f8fc;
  border: none;
  margin-bottom: 4px;
  border-radius: 7px;
}
