### ISSUE TITLE
[XSS] Info Window Usage Has XSS Vulnerability

### ISSUE THREAD

**Issue by cagataycali** [xkjyeah/vue-google-maps#183]
* What is [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS))

Google Maps info windows is capable of html rendering. If your app getting untrusted data from user you shouldn't use that way.

**If you are use info window like these,**

```javascript
<gmap-info-window  :content="m.infoWindowData" ></gmap-info-window>
```

Payload:

```html 
<img src="xss" onerror=prompt(1) />
```

Result:

<img width="374" alt="screen shot 2017-08-05 at 02 13 21" src="https://user-images.githubusercontent.com/9213230/28990201-b63c340c-7983-11e7-9c30-ebe1cb943a2b.png">

That usage have *XSS vulnerability*.

**Solution**

```javascript
<gmap-info-window> {{ m.infoWindowData }} </gmap-info-window>
```

Ps: I found ":content" usage in example usage.

Thanks,
Çağatay.

**Comment by xkjyeah** [comment]
Thanks for reporting

This option was a holdover from the v1 version. Probably good to delete it.
