### ISSUE TITLE
how to add flight paths between points on map?

### ISSUE THREAD

**Issue by vesper8** [xkjyeah/vue-google-maps#194]
Hi there!

Sorry if this is a little out of scope, I have a new task on my desk and am already using your package. I'm sure this can be done but just want a little guidance on how to do it the "vue way" if possible.

I think I need to be adding polylines between markers basically?

I want to reproduce the effect of this map https://goo.gl/jrK7xh

Any chance I could get a little example code on how to achieve this? Ideally drawing curvy lines like in the link above

Many thanks!

**Comment by xkjyeah** [comment]
Like so?

http://xkjyeah.github.io/vue-google-maps/index-app.html#/03CurvedLine

**Comment by vesper8** [comment]
hell yea!! did you just make that?? that's awesome! thanks a lot!

**Comment by xkjyeah** [comment]
Well thanks! I wanted a similar effect some time ago. I previously had it in a JS fiddle, but thought it  better to publish a demo of it here.

**Comment by vesper8** [comment]
hey @xkjyeah 

I want to revisit this.. I like your example but the line itself is not so nice.. I found other examples where the line is much nicer using quadraticCurveTo

such as this basic example https://www.w3schools.com/tags/canvas_quadraticcurveto.asp

but it seems like you can only make use of this kind of thing if drawing on a canvas

but I inspect the source in the debugger that vue-google-maps produces and I don't see a <canvas> element.. does that mean that I can't make use of nice drawling tools such as quadraticCurveTo ?

would I need to draw a canvas as an overlay to the map as attempted in this thread? Would that work you think? Or is there an easier way

https://stackoverflow.com/questions/5960524/html-canvas-as-overlayview-in-google-maps-that-is-fixed-relative-to-the-map-canv
