### ISSUE TITLE
Autocomplete v-model

### ISSUE THREAD

**Issue by tremendino** [xkjyeah/vue-google-maps#198]
Hi everyone, 
I'm pretty new to Vue (2.*) and I'm stuck with a simple problem.
When I bind (using v-model) my autocomplete component to a parent var (let's call it "googleobj") it won't change even after place_changed event fired. 

Seem to be one way binding (if I set the googleobj var I see the bar value changing).
If it's one way binding how can I access the $event within place_changed to retrieve sender information?

A bit of raw code 

template

```
<a href="#" v-on:click.prevent="addAddress">add address </a> 
 <template v-for="(address, index) in addresses"> 
      <gmap-autocomplete @place_changed="setAddress" v-model="address.google"
</template> 
```

script
```
export default { 
  data: function() { 
    return { 
      addresses: [], 
    } 
}, 
  methods: { 
     addAddress: function() { 
       this.addresses.push({ 
        google: null, 
       }); 
     }, 
    setAddress: function(place){
       console.log(place); //IT WORKS
      //BUT HERE IF I CHECK THE addresses OBJ IT CONTAINS A NEW ADDRESS BUT address.google 
      //is not filled, I was expecting address.google = place
     }
  }
}
```

i'll try to make a working fiddle of this
Thank you all

**Comment by tremendino** [comment]
After few hours of madness I figured it out with

```
<a href="#" v-on:click.prevent="addAddress">add address </a> 
 <template v-for="(address, index) in addresses"> 
      <gmap-autocomplete @place_changed="setAddress($event, index)" v-model="address.google"
</template> 
```

```
    setAddress: function(place, index){
       console.log(place);
       console.log(index);
     }

```

it seems overriding first parameter with $event pick up the event payload itself then I can pass other arguments to my function...

**Comment by Stalinko** [comment]
@blackvalmiki so finally did you make `v-model` work or not? I can't understand how change to `setAddress` call can rely on `v-model`?

**Comment by joedawson** [comment]
@Stalinko did you manage this?

**Comment by Stalinko** [comment]
@JoeDawson, yes, I have switched to https://github.com/ErrorPro/react-google-autocomplete :)

**Comment by Stalinko** [comment]
@JoeDawson , I don't remember what exactly I changed and why does it work.
From my code I see that I made a component-wrapper for gmap-autocomplete:

**MyAddress.vue**
```
<template>
    <gmap-autocomplete :value="value" @place_changed="updateAddress" ref="address" @input.native="updateAddress" />
</template>

<script>
    export default {
        props: {
            value: {
                type: String
            }
        },
        methods: {
            updateAddress: function () {
                this.$emit('input', this.$refs.address.$refs.input.value)
            }
        }
    }
</script>
```

And this is how it is used:

```
<input-address v-model="my_model"></input-address>
...
import inputAddress from 'MyAddress.vue'
...
export default {
    ...
    data() {
        return {
            my_model: ''
        }
    },
    components: {
        inputAddress,
    }
}
```

**Comment by joedawson** [comment]
Thank you @Stalinko, I'll try this tomorrow :)
