### ISSUE TITLE
Geometry Libraries

### ISSUE THREAD

**Issue by bealejd** [xkjyeah/vue-google-maps#200]
Is it possible to import and use the google maps geometry libraries? This is what I've tried:

    import * as VueGoogleMaps from 'vue2-google-maps'
        Vue.use(VueGoogleMaps, {
            load: {key: 'xxxx', libraries: 'geometry'}
    })

    export default {
      methods: {
        testGoogleMaps(){
          var heading = google.maps.geometry.spherical.computeHeading(new google.maps.Point(0, 0), new google.maps.Point(10, 10))
          console.log(heading)
            }
        }
    }

and I get the error "Uncaught TypeError: Cannot read property 'spherical' of undefined". So I guess it's not importing the geometry library? Any idea what I might have missed? 

Thanks!

**Comment by bealejd** [comment]
Ok, I've got it working. I found a comment on a Google Maps Api [question](https://stackoverflow.com/a/10765950/866357) on SO that worked for me! Here's the comment:

> Additional help for searchers where this may not be a complete solution: if you're loading the geometry library and using an API key, you must put the libraries parameter before the key parameter. I was stuck for ages on this point – James Cushing

and this is what my code now looks like:

    Vue.use(VueGoogleMaps, {
      load: { libraries: 'geometry', key: 'xxxx' }
    })

**Comment by nicolaelitvac** [comment]
I've changed places, and put the 'key' after 'libraries', but it didn't help.

```javascript
let distance = google.maps.geometry.spherical.computeDistanceBetween(mapCenter, store.coordinates)
```

I'm getting same error "Cannot read property 'spherical' of undefined""

**Comment by flymke** [comment]
I just had the same issue, if you need more libraries you have to add it as array:

```
import * as VueGoogleMaps from "vue2-google-maps";
Vue.use(VueGoogleMaps, {
  load: {
    key: "xxxx",
    libraries: ['places', 'geometry'] // necessary libraries
  }
});
```

**Comment by ShehryarBytes** [comment]
@flymke did this worked for you? Tried above and your's solution..nothing worked

**Comment by flymke** [comment]
@Shehryar169 yes for me this worked (if you happen to use Laravel / Vue setup, I added it in the app.js file before including the components)
