### ISSUE TITLE
how to call autocomplete for data? using Vuetify

### ISSUE THREAD

**Issue by DanielSmith** [xkjyeah/vue-google-maps#201]
I would love to use autocomplete for places, such as I would get from gmap-autocomplete.. .but, I want to use VText or VSelect w/Vuetify.
Since I am already loading for gmap-map, is there a way I can call into autocomplete, so that I can use the return data with the Vuetify components?

The alternatives would seem to be: 1) force styling of gmap-autocomplete to use Vuetify's stuff, or 2) load google maps api separate, just to get access to autocomplete.  Not fond of those options, if I can help it.

**Comment by vaishali-ghayal** [comment]
I also want to implement the same

**Comment by xkjyeah** [comment]
Nope, unfortunately there aren't many good options.

Autocomplete is part of the Google Maps feature. Since it obviously doesn't
know about vuetify, there's no way to combine the two.

**Comment by DanielSmith** [comment]
What I was asking is pretty simple: is there a way to get at your call of the autocomplete() call within gmap... without having to rewrite part of gmap?...  Yes, I know it is part of the API.  I may have to just use it directly and skip this package.

**Comment by DanielSmith** [comment]
"Autocomplete is part of the Google Maps feature. Since it obviously doesn't know about vuetify, there's no way to combine the two."....

Not a good answer at all.  I'll just do it myself.

**Comment by ijunaid8989** [comment]
@DanielSmith how did you do it?
