### ISSUE TITLE
How save center of map ?

### ISSUE THREAD

**Issue by zelds** [xkjyeah/vue-google-maps#202]
User go from map to another component, but after back to prev page center of return to default. How i can save prev center where user watch ?

**Comment by xkjyeah** [comment]
@center_changed -> update your URL (this.$router.push({params:{lat, lng}})

**Comment by zelds** [comment]
How i can add this when user press back button in browser ? Sorry for dummy question

**Comment by xkjyeah** [comment]
You need to use vue router to pass the lat/lng from the query string to the component.

Then whenever you move the map, update the $route again.

vue-router will automatically handle the pushing of lat/lng onto the browser history

**Comment by zelds** [comment]
Issue is in other. When user change component buy url /test and press "Back" in browser the map return to default position. 

Child component created()
`this.$emit('center_change' [{map_center: {lat:user_data.position.latitude,lng:user_data.position.longitude}}]);

Parent component mounted()
`this.$on('center_change',` function(data_from_child) {this.data.map_center=data_from_child});

**Comment by zelds** [comment]
Try to change do this with vue-bus but it dosent work. 
The starting center of map is in data ()
when i use emit to change map_center to another value, when i press back button i see the same center what was in data() of main component

This dont help.

        VueGoogleMap.loaded.then(function(map) {
           self.map.center = {'lat': this.user_data.position.latitude, 'lng': this.user_data.position.longitude}});

**Comment by xkjyeah** [comment]
Try this:

<GmapMap
   :center="{ lat: parseFloat($route.query.lat) || 0, lng:
parseFloat($route.query.lng) || 0 }"
   @center_changed="updateRouteLatLng"
>

updateRouteLatLng: lodash.debounce(function (e) {
    this.$router.push({
        ...this.$route,
        query: {...this.$route.query, lat: e.latLng.lat(), lng:
e.latLng.lng() }
    })
}, 500)


(obviously, you'll have to change some of the defaults here, and import
some additional libraries)

**Comment by zelds** [comment]
Can i call    updateRouteLatLng from other component ?

**Comment by zelds** [comment]
```    redic: function(i) {
      this.$router.push('/details/' + this.markers[i].uid)
      console.log(this.map_center,' befor')
      this.map_center = {
lat: Number(this.markers[i].position.latitude),
lng: Number(this.markers[i].position.longitude)
}
   console.log(this.map_center,' after')
```
I try change default value in component A when redirect to component B and value changes. 
```
{__ob__: Observer} 'before
lat :21.121156lng: 34.154167

{__ob__: Observer} ' after
lat :21.131156lng: 34.214167
```

But after press "Back" in browser i see same value what was on create component.

---------------------------------------------------------------------------------------------------------------
Try do same using method from parent component 
 ``` 
changeCenter(place) {
      this.center = {
        lat: place.latitude,
       
        lng: place.longitude,
      };
      this.zoom = 14;
    },
```
But after press "Back" loaded default value.
```
      this.$parent.$options.methods.changeCenter(this.markers[i].position)

```
----------------------------------------------------------------------------------------------------------
UPD: When use google autocomplite with places 
   ```
   changeCenter(place) {
          this.center = {
            lat: place.geometry.location.lat(),
            lng:  place.geometry.location.lng(),
          };
          this.zoom = 14;
        },
```
This function change default place value and all works properly. How i can do the same but sending custon lat and lng position. Cant understand that one week :cry:

**Comment by xkjyeah** [comment]
You have got to show me the code for all the components you have talked about. I won't know what you are trying to achieve if you only show me snippets without their context

**Comment by zelds** [comment]
qwe

**Comment by zelds** [comment]
@xkjyeah Two weeks i can`t fix it can u help ?
