### ISSUE TITLE
missing dependency when "npm install"

### ISSUE THREAD

**Issue by Sengchheang** [xkjyeah/vue-google-maps#21]
![screen shot 2016-12-20 at 9 59 23 am](https://cloud.githubusercontent.com/assets/635758/21336899/331399bc-c69b-11e6-8fca-e33b3dca01ff.png)

This is my first fresh install of this package and I encountered the above issue.
(Since this is my first installation, I am sure that the missing package was not take from cache.)

Thank for any hints

**Comment by xkjyeah** [comment]
Yup that's normal. Run:
`npm install marker-clusterer-plus`
and you should be good to go

**Comment by xkjyeah** [comment]
https://nodejs.org/en/blog/npm/peer-dependencies/

Because there may be people who prefer an alternative library to marker-clusterer-plus

**Comment by Sengchheang** [comment]
It is working now!

Awesome and thank you! ;)
