### ISSUE TITLE
Google places autocomplete

### ISSUE THREAD

**Issue by koddr** [xkjyeah/vue-google-maps#219]
Any plans to add support (or integration with https://github.com/olefirenko/vue-google-autocomplete) to autocomplete addresses?

Official docs here: https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by ah017** [comment]
See https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#autocomplete-class-mixes-in-mapelementmixin
