### ISSUE TITLE
Error: Unknown custom element: <gmap-map>

### ISSUE THREAD

**Issue by shvelo** [xkjyeah/vue-google-maps#221]
I'm getting an error when using `<gmap-map>` in my components, I'm importing it in my main file as shown in the readme.

**Comment by xkjyeah** [comment]
Did you call Vue.use(...)?

**Comment by shvelo** [comment]
Yes.

**Comment by shvelo** [comment]
Do I need to import it in every component?

**Comment by jonatasgrosman** [comment]
@shvelo You don't need to import it in every component, just in the main like you did.
The only error in your console is "Unknown custom element"?

**Comment by shvelo** [comment]
Yes. That's the case.

The error goes away if I copy the import code into the component that
directly uses gmap-map in the template

**Comment by shvelo** [comment]
Figured it out, I had put `Vue.use` after `new Vue(...)` so my app was initialized before VueGoogleMaps

**Comment by fulminant** [comment]
@shvelo, thx man, you save my coding evening ;)
