### ISSUE TITLE
How can I load a map after centain event?

### ISSUE THREAD

**Issue by jonatasgrosman** [xkjyeah/vue-google-maps#222]
I'm trying to put a map inside a material dialog (http://vuematerial.io/#/components/dialog), but I'm having some troubles 'cause the creation of dialog element occurs after a "open" event, in other words, when my page loads, the container element that gmaps needs is not there, then the map doesn't load properly. How can I fix it? I think I need some way to load a map only after open the dialog.

**Comment by xkjyeah** [comment]
Just use GmapMap. It always creates the map after the component is
available. After the dialog is open, use the resize bus to trigger a
resize.
http://xkjyeah.github.io/vue-google-maps/resize-bus.html

**Comment by jonatasgrosman** [comment]
Thanks @xkjyeah,
 
I don't know why, but my problem was not about resizing, but about component rendering. I've solved that issue using a "v-if" to prevent map loading before the dialog opening.
