### ISSUE TITLE
Event modifiers not working on markers

### ISSUE THREAD

**Issue by ducdebreme** [xkjyeah/vue-google-maps#225]
I have a gmap marker: if it's getting clicked, I need open a dialog and to stop the further propagation of the event
```
    <gmap-marker
      ...
      @click.stop="openDialog"
    ></gmap-marker>
```
But this results in an javascript error message `$event.stopPropagation is not a function`

Is there something special about the events emitted from gmap-markers?

**Comment by xkjyeah** [comment]
Yes. They are not DOM events, and `GmapMarker` is not bound to any DOM element, so you can't stop propagation from there.

From the Google Maps API reference (https://developers.google.com/maps/documentation/javascript/3.exp/reference#MouseEvent) It seems stopping the propagation is not supported. You can instead try placing a `@click.native.stop` on the `GmapMap` element.

**Comment by barnholdy** [comment]
`@mouseover.native.stop` did not work for me on `GmapMarker` (mouseover is still triggered on the map). Any suggestions?
