### ISSUE TITLE
Implement with OverlappingMarkerSpidifier

### ISSUE THREAD

**Issue by ghazifardhan** [xkjyeah/vue-google-maps#227]
Hi xkjyeah,

I have problem, i want to implement vue2-google-maps with [OverlappingMarkerSpiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier).

I need the map object to fill the paramater in overlapping marker spidifier, i'm using
this.$refs.map.$mapObject, but got null and my map doesnt show up.

Can you give a solution to work with that, thanks.

**Comment by xkjyeah** [comment]
I can't see your private repo. Do you have a snippet of code I can look at?

**Comment by ghazifardhan** [comment]
Sorry, i fix the link, you can take a look now.

**Comment by xkjyeah** [comment]
Could you show me your Vue code?

**Comment by ghazifardhan** [comment]
thank xkjyeah, my problem was solved.
the map object undefined because i call overlapping marker before map is rendered or created.
