### ISSUE TITLE
Exposed 'google' api

### ISSUE THREAD

**Issue by EddyTheDove** [xkjyeah/vue-google-maps#228]
I am trying to do something else with google-maps api that this package does not offer. I'm trying to calculate distances using `google.maps.DistanceMatrixService`, therefore I need to access a global google variable. 

If I add another variable, I have an error saying I included google multiple times. How can I globally expose the `google` variable so other "components" can independently use it?

Probably I missed something from your documentation, don't go hard on me. 
Thanks in advance.

**Comment by xkjyeah** [comment]
https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#loaded--promise

Here's an example where I use `google.maps.Point`
```js
import {loaded} from 'vue2-google-maps'
export default {
    data: {
        apiLoaded: false,
    },
    created () {
        loaded.then(() => this.apiLoaded = true)
    },
    computed: {
        icon () { // This computed property references this.apiLoaded, so reactivity will work correctly
            if (this.apiLoaded) return { url: 'my-image.png', anchor: new google.maps.Point(24,24) }
        },
        badIcon () { // This computed property does not reference any reactive props, so it will never succeed
            if (window.google) return { url: 'my-image.png', anchor: new google.maps.Point(24,24) }
        },
        errorIcon () { // This computed property may be evaluated before google is defined, so it may throw an error
            return { url: 'my-image.png', anchor: new google.maps.Point(24,24) }
        },
    }
}
```

Note: do not put `google` into `data`.
