### ISSUE TITLE
Uncaught ReferenceError: Marker is not defined

### ISSUE THREAD

**Issue by pwnz22** [xkjyeah/vue-google-maps#23]
I'm using this package with Vue integrated to Laravel in bundle files with webpack. And when i'm calling  gmap-map i'm having this error in console. `Uncaught ReferenceError: Marker is not defined`

**Comment by xkjyeah** [comment]
Could you show me the relevant parts of your code?

You should not have to define the Marker component yourself. Just use
<gmap-marker> wherever you need it

**Comment by pwnz22** [comment]
Ohh, understand now. I think that i also should define the component because of this code in README
`components: { gmapMap: Map, gmapMarker: Marker }`

After i delete components defined properties it all worked, but now i'm getting this error: `Uncaught (in promise) TypeError: Cannot read property 'Autocomplete' of undefined`

**Comment by xkjyeah** [comment]
Hmm that's true. I must have forgotten to update the README. Sorry about
that. The same applies to autocomplete. Just... Use it.

**Comment by pwnz22** [comment]
Awesome, everything is working. Thanks.

**Comment by xkjyeah** [comment]
Sorry, keeping it open so I remember to update the README
