### ISSUE TITLE
"TypeError: Cannot read property 'clearMarkers' of undefined"

### ISSUE THREAD

**Issue by letovlive** [xkjyeah/vue-google-maps#232]
I've got next error in cluster component.
[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'clearMarkers' of undefined"
It seems that beforeDestroy called without instantiated $clusterObject as it instantiates in deferredReady function.
beforeDestroy() {
    /* Performance optimization when destroying a large number of markers */
    this.$children.forEach(marker => {
      if (marker.$clusterObject === this.$clusterObject) {
        marker.$clusterObject = null
      }
    })

    this.$clusterObject.clearMarkers();
  },

**Comment by xkjyeah** [comment]
ok published in v0.8.4
