### ISSUE TITLE
Google map not render with library vue2-google-maps

### ISSUE THREAD

**Issue by bpdarlyn** [xkjyeah/vue-google-maps#236]
I am trying render a map using google-maps with vue, I am using a webpackage for transpiler vue js, I have a file main.js this call to all the importations.

## file mains.js

    import Vue from 'vue'
    
    import { load } from 'vue2-google-maps'
    load({
        key: 'my-api',
        v: '3.exp',
        installComponents: false
    });
    
    import App from './components/app.vue'
    new Vue({
        el: '#app-vue',
        render: h => h(App)
    });

## file app.vue

    <template>
            <gmap-map
                    :center="{lat:10, lng:10}"
                    :zoom="7"
                    map-type-id="terrain"
                    style="width: 500px; height: 300px"
            ></gmap-map>
    </template>
    
    <script>
    import { Map } from 'vue2-google-maps'
    export default {
      name: 'app',
        components: {
          'gmap-map': Map
        },
        data () {
            return {
                center: {lat: 10.0, lng: 10.0},
                markers: [{
                    position: {lat: 10.0, lng: 10.0}
                }, {
                    position: {lat: 11.0, lng: 11.0}
                }]
            }
        }
    }
    </script>

but it is not working, the page is empty what am i doing wrong ?

**"vue": "^2.5.2",**

**"vue2-google-maps": "^0.8.4"**

**Comment by jess8bit** [comment]
+1 same issue here.
I have a similar piece of code which worked fine until a recent vue update I guess (I would suspect something got broken when upgrading from 2.4 to 2.5?)

**Comment by bpdarlyn** [comment]
I solved the problem changing my dependecies [
"vue": "2.2.1",
    "vue-loader": "11.1.3",
    "vue-template-compiler": "2.2.1",
    "vue2-google-maps": "0.8.4"](url).

**Comment by xkjyeah** [comment]
@bpdarlyn 
You should be using the `Vue.use({...})` syntax

See the README file

**Comment by bpdarlyn** [comment]
Thanks!! but it doesn't work :(, what could be ?, anyway It solved my problema, I'll close this issues.

**Comment by jess8bit** [comment]
I'm running vue 2.5.2 and I couldn't downgrade, but I found how to fix this in my context:

having the style set up like didn't work anymore for me, for some reason:

```
<gmap-map 
    :options="{styles: styles}"

...

  data() {
    return {
      styles: [{ width: "100%", height: "300px" }],
```

but it worked again by setting inline style or class, like this for example:

```
<gmap-map 
    class="myclass"

...

<style scoped>
.myclass {
  width: 100%; height: 300px;
}
</style>
```

Not sure if this is relevant here, but hope it helps.
