### ISSUE TITLE
Can I hide a marker according to some attribute ?

### ISSUE THREAD

**Issue by bpdarlyn** [xkjyeah/vue-google-maps#239]
I have this code 
``` html
<template >
    <google-marker  :position="position" :icon="icon" v-if="isFree()">
    </google-marker>
</template>
```
I want to hide the marker when the method isFree()  is false or exist the some method than help me!!, or in anyway I'll do it with watchers

**Comment by bpdarlyn** [comment]
ok, excuse me !! my problem was for v-if I was using a method, when I should have use a property computed.

**Comment by TihomirS** [comment]
hi, 
are you find a solution?

I want to do same .. to assign "  :visible=v.show "
and from data to send for different markers different variables .. and allow user to change them..

is this possible?
