### ISSUE TITLE
Set the zIndex

### ISSUE THREAD

**Issue by martinmildner** [xkjyeah/vue-google-maps#24]
Hi all,
I am facing a problem when setting the zIndex for gmap-marker:
`<gmap-marker v-for="m in markers" :position="m.position" :zIndex="m.zIndex" :clickable="true" :draggable="false" @click="center=m.position"> </gmap-marker>`

`markers: [{
position: {lat: 42.3666593, lng: -71.0994817},
				title: "XXX",
				zIndex: 50,
		  	},`

But the zIndex still looks like
> zIndex: undefined prop
All other properties are set correctly...

Any glue? Thanks a lot!
martin

**Comment by xkjyeah** [comment]
As with all vue properties, if they are camel cased in JavaScript, they
should be hyphenated in HTML

**Comment by martinmildner** [comment]
grrr - sorry for that... works just fine...
