### ISSUE TITLE
center_change event value

### ISSUE THREAD

**Issue by usrNotFound** [xkjyeah/vue-google-maps#240]
not able to access center_change event value. 
`<g-map-map @center_change="updateLatLog"></gmap>`
  `updateLatLon(value) {`
    `console.log(value)`
`}`

![screen shot 2017-10-25 at 12 35 07 pm](https://user-images.githubusercontent.com/11272457/31977607-0bbb12ee-b981-11e7-886e-00a1a03917f0.png)

In console I get the empty output

`_.F {lat: ƒ, lng: ƒ}`
`lat: ƒ ()`
`lng:ƒ ()`

**Comment by xkjyeah** [comment]
Center_changed has no argument in the Google Maps API (https://developers.google.com/maps/documentation/javascript/3.exp/reference#Map)

Since this library only aims to be a thin wrappr around the API, this will not be supported.

**Comment by usrNotFound** [comment]
Fair enough but the map component is emitting an event call center_changed. The issue is when I try to access payload it return null. Should you not be able to access payload  from event?  I can access the payload of `bounds_changed` with out any issue though. Any thoughts?

**Comment by xkjyeah** [comment]
Google Maps API does not provide a payload. `bounds_changed` supports it, but it really shouldn't (apologies).

If you need to access the map center, add a ref to the map:
```html
<GmapMap ref="themap">
```

and then access it like so:
```js
this.$refs.themap.$mapObject.getCenter()
```
