### ISSUE TITLE
Disabling gestures and Fullscreen when touch

### ISSUE THREAD

**Issue by luiztsmelo** [xkjyeah/vue-google-maps#246]
There's a way to implement these properties?
- **fullscreenControl**

- **fullscreenControlOptions**

- **gestureHandling**

I want to allow the gesture only in fullscreen mode.

**Comment by xkjyeah** [comment]
Pass these options into :options on the <GmapMap>

**Comment by luiztsmelo** [comment]
Thanks. Great job @xkjyeah
