### ISSUE TITLE
Bug with full screen. Cordova IOS

### ISSUE THREAD

**Issue by dunice-boldirev** [xkjyeah/vue-google-maps#248]
Hello!

I develop mobile application using cordova.
In my app I using [vue2-google-maps](https://www.npmjs.com/package/vue2-google-maps). When I run application on iPhone "Full screen" button not show. In same time an Android device  "full screen" button show and works well.
Could you help me and tell me what could be reason of this problem?
Below I attached code and screenshots

    <gmap-map 
      :center="{ lat: 0, lng: 0 }" 
      :zoom="12" 
      :options="{ draggable: false, zoomControl: true, streetViewControl: false, fullscreenControl: true }">
     </gmap-map>

**IPhone*

![iphone](https://user-images.githubusercontent.com/11989481/32493261-43b128f8-c3ce-11e7-9656-10f33bdb41bd.png)

**Android device*
![2017-11-07 15 03 52](https://user-images.githubusercontent.com/11989481/32493296-604d622e-c3ce-11e7-8f02-a8dd8bd8a518.png)

Let me know If you need more information from me.

Thank you

**Comment by krisztianodor** [comment]
https://developers.google.com/maps/documentation/javascript/controls

> Note: iOS doesn't support the fullscreen feature. The fullscreen control is therefore not visible on iOS devices.
