### ISSUE TITLE
Autocomplete stopPropagation

### ISSUE THREAD

**Issue by nniicc** [xkjyeah/vue-google-maps#252]
Hey,

Im using the autocomplete and trying to stop the parent event (form submit) from being fired with selectFirstOnEnter="true"

my code is like this 
```html
<form action="/search" method="GET">
    <gmap-autocomplete
        :types="['(cities)']"
        class="_inputForm--row-input autocomplete-from"
        :select-first-on-enter="true"
        @place_changed="setFromPlace">
    </gmap-autocomplete>

    <input type="submit" value="Search" />
</form>
```

I have tried to stop the event like `@place_changed.stop="setFromPlace"` but then i get a error 
`Error in event handler for "place_changed": "TypeError: $event.stopPropagation is not a function"`

**Comment by nniicc** [comment]
Okay i found a way by adding `@keydown.native.enter.prevent` into the gmap-autocomplete.

**Comment by zabaat** [comment]
for learning posterity:

another option if you need the enter key you can capture it instead, then stop events and fire your own vue emit (or run another function, etc)

```
<gmap-autocomplete @place_changed="setPlace"
  @keydown.native.capture="catchEnter"/>
```
```js
        catchEnter(event) {
            event.preventDefault()
            event.stopPropagation()
            this.$emit('submitted')
        }
```
