### ISSUE TITLE
Not include google maps

### ISSUE THREAD

**Issue by vanessa-joyce** [xkjyeah/vue-google-maps#257]
We need to include the google maps api in index.html due to usage in other components. But if we include it in index.html and when instancing vue-google-maps, we get the error that google is included twice.

Is there a possiblity to use vue-google-maps without defining the key when instacing to not include it twice?

Vue.use(VueGoogleMaps)

Thank you :)

**Comment by xkjyeah** [comment]
Yes it is...

Refer to

https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/manager.js

Vue2-google-maps creates a global function named vueGoogleMapsInit.

When you are certain that the Maps API has been loaded by your other
components, call this function:

vueGoogleMapsInit()

Omit the "load" parameter when you initialize the plugin.

**Comment by vanessa-joyce** [comment]
It worked! Thank you very much.
