### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jlfenaux** [xkjyeah/vue-google-maps#259]
I'm having trouble setting up vue-google-maps. I try to use it in a very basic component. 

```
<template>
  <div>

    <button @click='refresh'>Refresh</button>
    <gmap-map
      :center="{lat:10.5, lng:10}"
      :zoom="7"
      style="width: 500px; height: 300px"
    ></gmap-map>

  </div>
</template>

<script>
export default {  
  methods: {
    refresh() {this.$gmapDefaultResizeBus.$emit('resize')}
  }
}
</script>
```

VueGoogleMaps is loaded in my javascirpt file 

```
import * as VueGoogleMaps from 'vue2-google-maps';

  Vue.use(VueGoogleMaps, {
    load: {
      key: 'xxxxxx',
      libraries: 'places', // This is required if you use the Autocomplete plugin
      // OR: libraries: 'places,drawing'
      // OR: libraries: 'places,drawing,visualization'
      // (as you require)
    }
  })

```

As a result, the map component is added to the DOM, but not map is displayed. https://imgur.com/S3w7VOu
Clicking on the refresh button doesn't help. 

I must have missed something terribly obvious, but I don't get it. 

Thanks.

**Comment by VerhoevenWout** [comment]
Try adding following code underneath your Vue.use(...) block.

Vue.component('google-map', VueGoogleMaps.Map);

**Comment by xkjyeah** [comment]
Would you have any errors that suggest that the Google Maps library is not
being loaded correctly? e.g. Content security policy violation. Do you have
a screenshot of your JS console?

**Comment by jlfenaux** [comment]
I left the project for a few weeks and now I managed to get it working. Thanks
