### ISSUE TITLE
How do I style marker-clusterer?

### ISSUE THREAD

**Issue by BennieBe** [xkjyeah/vue-google-maps#262]
I am wondering how I can style marker-clusterer. I tried below code, which did not work:

In my html:
  `<gmap-cluster :grid-size="gridSize" :styles="clusterStyles"></gmap-cluster>`

In my vue file:
```
data: {
      /* CLUSTERS */
      gridSize: 50,
      clusterStyles: [
        {
          textColor: 'black',
          url: route('cacheImage', ['general', 'marker-cluster1.png']),
          height: 32.2,
          width: 33
        },
        {
          textColor: 'black',
          url: route('cacheImage', ['general', 'marker-cluster2.png']),
          height: 46,
          width: 46
        },
        {
          textColor: 'black',
          url: route('cacheImage', ['general', 'marker-cluster3.png']),
          height: 64,
          width: 64
        }
      ],
```

**Comment by BennieBe** [comment]
Found solution, case closed, the styling works fine with above code

**Comment by torontochen** [comment]
Hi Bennie,I have the same problem when styling makercluster,how did you solve it?

**Comment by BennieBe** [comment]
Can you provide some code? Above solution works for me, are you sure its an issue with that code part or maybe something else prevents it from showing correctly?

**Comment by torontochen** [comment]
template part, 

` <GmapCluster :grid-size="gridSize"  :styles="clusterStyle"  :maxZoom="zoom"  v-if="clustering" >
         </GmapCluster>
`
script part,
` clusterStyle:[{
        url: 'clusterIcon/conv30.png',
        width: 30,
        height: 27,
        anchorText: [-3, 0],
        anchorIcon: [27, 28],
        textColor: '#ff00ff',
        textSize: 10
      }, {
        url: 'clusterIcon/conv40.png',
        width: 40,
        height: 36,
        anchorText: [-4, 0],
        anchorIcon: [36, 37],
        textColor: '#ff0000',
        textSize: 11
      }, {
        url: 'clusterIcon/conv50.png',
        width: 50,
        height: 45,
        anchorText: [-5, 0],
        anchorIcon: [45, 46],
        textColor: '#0000ff',
        textSize: 12
      }], `
anchor text is rendered,but cluster image doesn't appear
![cluster](https://user-images.githubusercontent.com/31119087/42914386-0d64b03c-8ac8-11e8-8828-5c787f5393fa.PNG)
thank you

**Comment by torontochen** [comment]
Hi Bennie,
what is the route('cacheImage', ['general', 'marker-cluster1.png'])?
How come the function route() doesn't work in my codes

**Comment by BennieBe** [comment]
Hi Torontochen,

CacheImage is internal to my use case. It is not a function of the vue-google-maps package. To me your styles look fine but I assume that the path to the image is not correct. My path for example is: /images/general/marker-cluster.svg. I assume you might have to set the correct default image folder and your image file path

**Comment by torontochen** [comment]
I tried several times to define an absolute path.it is not working. I will figure it out any way,thank you

**Comment by torontochen** [comment]
Hi Bennie,
I really can't find out what is wrong,the url in absolute path is supposed to be correct ,could you check it for me,thanks a lot
![directory](https://user-images.githubusercontent.com/31119087/43028304-1eae2dec-8c4d-11e8-83fc-6e2d3bf1e43e.PNG)
![file](https://user-images.githubusercontent.com/31119087/43028311-28c9a69e-8c4d-11e8-9325-7325722147ac.PNG)

**Comment by zecka** [comment]
@torontochen 
Maybe you can define your url like that (it's work in my case):

```
clusterStyles: [
        {
          textColor: "red",
          url: require("./clusterIcon/conv30.png"),
          height: 50,
          width: 50,
          textSize: 20
        }
 ]
```
