### ISSUE TITLE
setMap: not an instance of Map

### ISSUE THREAD

**Issue by BennieBe** [xkjyeah/vue-google-maps#266]
I understood from the documentation that I can receive the GoogleMaps Object using something like this: 
```
deferredReady(){
    this.map = this.$refs.gmap;
}
```
Where 'gmap' is defined by ref="gmap" on gmap-map component : `<gmap-map ref="gmap"></gmap-map>`
Now, when I try to call the function google.maps.setMap on this object, I receive the following error:

> InvalidValueError: setMap: not an instance of Map

Seems like this object is not the instance of google.maps? Or is there something I am missing?

**Comment by bedakb** [comment]
Use `$mapCreated` where you will get reference to your map like this

```
this.$refs.gmap.$mapCreated.then(map => {
  something.setMap(map);
});
```

**Comment by theara72** [comment]
hello ! how can i use instance in methods ?

**Comment by theara72** [comment]
i do like this but log show nothing
`deferredReady () {
	    	self = this;
	    	this.$refs.gmap.$mapCreated.then(map => {
			  self.googleMap = map;
			});	
	    },
	    beforeMount() {
	      	console.log(this.googleMap);
	    },`

**Comment by BennieBe** [comment]
@bedakb @theara72 example does not work for me either, returns undefined

**Comment by bedakb** [comment]
Well then try to use with the `$nextTick`

```
this.$nextTick(() => {
  this.$refs.gmap.$mapCreated.then(map => {
    something.setMap(map);
  });
})
```

**Comment by BennieBe** [comment]
@bedakb I tried this, too, I do not get the instance that I am using. Is it possible to give sort of an example using a fiddle or something like that to show how it works please or any link for guidance?

**Comment by BennieBe** [comment]
I get the instance with above code, all fine, thanks
