### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by b4dnewz** [xkjyeah/vue-google-maps#267]
Hi, I'm using your project and it works good, but from one machine to another it fails and I can't understand why, I'll try to explain.

I download and import your module:
```js
import * as VueGoogleMaps from 'vue2-google-maps'
Vue.use(VueGoogleMaps, {
  load: {
    key: '<my-key>',
    libraries: 'places'
  }
})
```

I'm using electron-vue which has the vue-loaders (and stuff) setup for webpack and your package sometimes throw this error message while building:

**Uncaught SyntaxError: Unexpected token <**
while trying to produce this:
```js
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
<template> <-- the problem is here
  <div>
    <div ref="flyaway">
      <slot>
      </slot>
    </div>
  </div>
</template>

<script src="./infoWindowImpl.js"></script>

}.call(this, exports, require, module, __filename, __dirname); });
```
during webpack bundle, I'm pretty sure this is not the normal behaviour and i'm pretty sure it's not a specific bug on your project, but it happen only with your project, do you have any idea of what is causing it, or how to debug/fix? Any help is appreciated.

I've tried many times to clear, reinstall, purge, prune and stuff npm modules and now happen all the times, my project has the normal electron-vue dev dependencies all updated to last version.
```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-istanbul": "^4.1.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^1.1.3",
    "chai": "^4.1.2",
    "chalk": "^2.3.0",
    "copy-webpack-plugin": "^4.2.3",
    "cross-env": "^5.1.1",
    "css-loader": "^0.28.7",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^1.7.9",
    "electron-builder": "^19.46.4",
    "electron-debug": "^1.4.0",
    "electron-devtools-installer": "^2.2.1",
    "eslint": "^4.11.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^4.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.30.1",
    "inject-loader": "^3.0.1",
    "karma": "^1.7.1",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.1",
    "karma-electron": "^5.2.2",
    "karma-mocha": "^1.3.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "^0.0.31",
    "karma-webpack": "^2.0.6",
    "mocha": "^4.0.1",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "node-sass": "^4.7.2",
    "require-dir": "^0.3.2",
    "sass-loader": "^6.0.6",
    "spectron": "^3.7.2",
    "style-loader": "^0.19.0",
    "url-loader": "^0.6.2",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^13.5.0",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.8",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4",
    "webpack-hot-middleware": "^2.20.0",
    "webpack-merge": "^4.1.1"
}
```

**Comment by xkjyeah** [comment]
It might be that vue loader is configured to ignore the node_modules folder.

Add another webpack rules entry to build  .Vue files in node_modules and it
should work

**Comment by b4dnewz** [comment]
@xkjyeah In the project I've i'm loading various plugins and .Vue files only your's give this error, I don't know why, so I assume the vue-loader is working properly since it loads all other plugins

**Comment by moeinrahimi** [comment]
did you solve this issue ? I have the exact error

**Comment by b4dnewz** [comment]
@moeinrahimi nop, I changed repo 😀 actually i'm using this: https://github.com/codekraft-studio/vue-google-map which is also a forked version of this: https://github.com/GuillaumeLeclerc/vue-google-maps

**Comment by webafra** [comment]
@b4dnewz : I have the same problem.
Please explain more how you resolved the problem?

i want use vue google map on Electron-vue but not work this package !

**Comment by b4dnewz** [comment]
@m-alinasab I have changed repository, I've posted two links but you have to refactor your code, like in the [example](https://github.com/codekraft-studio/vue-google-map/tree/master/example).

**Comment by webafra** [comment]
thanks .
1 - download your example
2 - replace to vue2-google-maps ?

**Comment by b4dnewz** [comment]
actually there is few things to do in order to fully refactor.. it's hard to explain with github messages..
take a look of how the [simple-map](https://github.com/codekraft-studio/vue-google-map/blob/master/example/components/SimpleMap.vue) example is done, it's pretty straight forward

**Comment by webafra** [comment]
i`m not understand :(
my english language very poor !
