### ISSUE TITLE
How to make a map unclickable

### ISSUE THREAD

**Issue by dortamiguel** [xkjyeah/vue-google-maps#27]
I'm searching in the repo but I can find this.

I don't want the map to scrollable, clickable or draggable with a fixed center and zoom.

 How I can achieve this?

**Comment by xkjyeah** [comment]
Hi,

You should try using Google's Static Maps API.

**Comment by dortamiguel** [comment]
Thanks! I will try it.

But this can be integrated with this plugin?

**Comment by matthewmnewman** [comment]
Alternatively you can use :options to disable the scrollwheel, draggable and zoomControl etc


`      <gmap-map :center="center" :zoom="7" :options="{scrollwheel: scrollwheel,draggable: draggable,zoomControl: zoomControl}">
          </gmap-map>
`

````javascript 
  data () {
     return {
       center: {lat: 10.0, lng: 10.0},
       scrollwheel: false,
       draggable: false,
       zoomControl: false
     }
   }

**Comment by dortamiguel** [comment]
Thanks! Worked perfectly
