### ISSUE TITLE
Styling the Circle region

### ISSUE THREAD

**Issue by ankush981** [xkjyeah/vue-google-maps#270]
Hello, thanks a TON for this awesome plugin. Is there a way to style the circular region marker? Currently it's black circumference with blackish shade inside, and it doesn't go well with our design. Thanks in advance, and you totally rock! :smile:

**Comment by BennieBe** [comment]
Are you talking about the clusterer marker?

**Comment by ankush981** [comment]
@BennieBe Here's what I mean:

![map](https://user-images.githubusercontent.com/4169691/33434091-2fab3446-d604-11e7-8c10-20ea0f973aea.png)

**Comment by bananabreadpr** [comment]
@ankush981 You can simply pass the **:option** in gmap-circle

example:
`<gmap-circle :center="{lat:10, lng:10}" :radius="1000" :options="mapCenterOptions"> </gmap-circle>`
```
data () {
      return {
       mapCenterOptions: {
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000'
        }
   }
} 
```

official docs for more options https://developers.google.com/maps/documentation/javascript/examples/circle-simple

**Comment by ankush981** [comment]
@tealendril Thank you so much! :smile:
