### ISSUE TITLE
getBounds() on mounted is `undefined`

### ISSUE THREAD

**Issue by nicolaelitvac** [xkjyeah/vue-google-maps#275]
I'm trying to get the bounds of the map after it was created. Based on this bounds I make a http query to my DB, so I need it at the very beginning.

``` javascript
    this.$refs.storesMap.$mapCreated.then(() => {
      console.log(this.$refs.storesMap.$mapObject.getBounds()) // undefined
    })
```

**Comment by nicolaelitvac** [comment]
If I manually add the bounds to the object based on added zoom, then it works. But their's should be a better way for doing this.
``` Javascript
// Before the console.log() from above
      // Add bounds object to map earlier
      // eslint-disable-next-line
      this.$refs.storesMap.$mapObject.bounds = new google.maps.LatLngBounds(this.map.center)
```

**Comment by xkjyeah** [comment]
You might want to wait for the 'idle' event before getting the bounds. This
is because Google Maps hasn't yet fully initialized the maps.
