### ISSUE TITLE
Vue props validation error

### ISSUE THREAD

**Issue by LexSwed** [xkjyeah/vue-google-maps#278]
Vue version 2.5.11 complains on "twoWay" prop for a list of objects
vue2-google-maps version is 0.8.4

**Comment by asifm** [comment]
Seeing this in several other plugins. Pretty sure it's related to these changes, as mentioned in https://github.com/vuejs/vue/releases

**Improvements**

warn misspelled keys on prop validation object (#7198) d02bb37, closes https://github.com/vuejs/vue/pull/7198

**Comment by jdriesen** [comment]
Hi All,

Encountering the same problem...
Can smb please tell me how to solve this ?

Thanks in advance,
Johnny

**Comment by Arwany** [comment]
I am also getting a lot of these warnings:

```
[Vue warn]: Invalid key "twoWay" in validation rules object for prop "center".
```

**Comment by asifm** [comment]
Seems it's just warnings. You can safely ignore them until it's fixed here. Or you can go back to the previous version of vuejs (2.5.10).

**Comment by LexSwed** [comment]
@asifm despite it's just warnings, it breaks Vue and app doesn't work.

**Comment by asifm** [comment]
I just went back to vue 2.5.10. Things are fine now. Make sure you downversion the other packages that have to match vue version. In my case they were vue-template-compiler and vue-server-renderer.

**Comment by jdriesen** [comment]
Thanks for this valuase info, @asifm.
If I can ask, which version of vue-template-compiler and vue-server-renderer are you currently using ?
(with vue 2.5.10 ?)

Thanks in advance for your reply.

Johnny

**Comment by asifm** [comment]
They have to always match the vue version. So they'll also be 2.5.10

**Comment by jdriesen** [comment]
Problem solved (running now on 2.5.10)
Thank you, @asifm

**Comment by vesper8** [comment]
so.. are we waiting for vue to fix this or are we waiting for vue-google-maps to fix this? I know it's just a warning.. but I don't like locking my vue version

**Comment by asifm** [comment]
@vesper8 We're waiting for all the libraries to fix and update. Vue has nothing further to do about it. 2.5.11 hasn't brought much change (other than this one), so going back to 2.5.10 seems a good solution for the time being.

**Comment by Arwany** [comment]
I have read somewhere that since Vue has added some spellchecking for props keys, it will always warn.

Here is the [commit link](https://github.com/vuejs/vue/commit/d02bb37efb3c4ee14b8cf9db22d1ab3340ba2c0f)

**Comment by jdriesen** [comment]
Yep, indeed @Arwany ...

It WAS a problem in 2.5.11... 
Though it's solved now in Vue v. 2.5.12 (released since a couple of hrs...)

Grtz,
Johnny

**Comment by asifm** [comment]
Please close the issue. Vue 2.5.12 (and later versions) won't cause this problem.
