### ISSUE TITLE
Addition of Direction service 

### ISSUE THREAD

**Issue by sdzharkov** [xkjyeah/vue-google-maps#28]
I'm wondering if it would be possible to integrate vue-google-maps with GoogleMaps direction service. Would I be able to render the map and then add directions onto it?

**Comment by xkjyeah** [comment]
Yes of course! For instance if you need both an autocomplete and the
directions, write (if I remember correctly):
```js
Vue.use(VueGoogleMaps, {
   libraries: 'places,directions'
   ... (api key, version here)...
})
```

**Comment by sdzharkov** [comment]
Well reason I ask is because the directions/ distance matrix tools aren't libraries like places or geometry library. Directions is categorized under 'services', so it isn't added to the URL used to call the Google Maps API. Would I have to use the direction service separately and then overlay it onto the <gmap>?

**Comment by xkjyeah** [comment]
Refer to
https://developers.google.com/maps/documentation/javascript/reference#DirectionsService

**Comment by sdzharkov** [comment]
I'm pretty sure that still wouldn't work... the object VueGoogleMaps has no such thing as a Directions service, so referencing it is basically useless, unless I'm missing something

**Comment by xkjyeah** [comment]
What are you talking about? The directions service is part of Google Maps.
vue google maps library imports the Google Maps library

**Comment by xkjyeah** [comment]
That said, go to the Google Developers console and enable the directions
API.

**Comment by admicaa** [comment]
Any one was able to solve this, please tell me how?
