### ISSUE TITLE
How to get correct LatLng on dragend marker

### ISSUE THREAD

**Issue by raymayemir** [xkjyeah/vue-google-maps#280]
`<gmap-marker :position="marker.position" :clickable="true" :draggable="true" @click="center=marker.position" @dragend="mapClick" ></gmap-marker>`

on call dragend event return like some

_.qk {latLng: _.D, pixel: _.y, ea: _.y}
ea
:
_.y {x: 182.66268920898438, y: 93.87493896484375}
latLng
:
_.D {lat: ƒ, lng: ƒ}
pixel
:
_.y {x: 139.5, y: 171}
__proto__
:
Object

How to get correct lat, long ?

**Comment by raymayemir** [comment]
vue v2.5 
vue-google-maps 8.4

**Comment by antoniohof** [comment]
mapClick (e) {
      console.log(e.latLng.lat() + ' ' + e.latLng.lng())
    }
