### ISSUE TITLE
Update center and zoom with a buttom

### ISSUE THREAD

**Issue by gepd** [xkjyeah/vue-google-maps#286]
What would be the best way to change the center and zoom of the map at the same time?

I'm trying to update the map after click a buttom, but if I change both objects (zoom and center) at the same time only one is updated. I've to click more than one time to get the effect I want.

I'm doing something like this:

```js
methods: {
        updateMap: function(location){
            this.center = location;
            this.zoom = 18;
        }
}
```
```html
<button @click="updateMap({lat: 10, lng: 10})"></button>
```

**Comment by gepd** [comment]
The solution is to use: `fitBounds`

```js
updateMap: function(location){
    var b = new google.maps.LatLngBounds();
    b.extend(location);
    this.$ref.map.fitBounds(b);
}
```

**Comment by MarouaneSH** [comment]
`
 updateLocation(location) {
     var b = new google.maps.LatLngBounds();
      b.extend(location );
      this.$refs.mapRef.fitBounds(b);
}
`
