### ISSUE TITLE
Removing markers

### ISSUE THREAD

**Issue by redxtech** [xkjyeah/vue-google-maps#290]
How would I go about removing a marker?
I have a computed property that gets the markers based on a condition, and from what I can tell, the only thing that happens when the condition changes is it re-renders the markers within the selection. When you change it again it re-renders the other markers.

If you would be able to put something in the unmounted/destroyed hook to remove the marker from the map that would be great, or if you would be able to tell me how I could accomplish this that would also be great.

Thanks \:)

**Comment by redxtech** [comment]
I have realized my mistake.
I was using a for look, and i was modifying the object that vue was looping through, and it was using the index as a key, so when I changed the key to the ID of the markers I was using it worked a lot better.

**Comment by TihomirS** [comment]
Hi, 
can you share some code?

I want almost the same. With checkbox to hide a group of markers ...

best,
