### ISSUE TITLE
Warnings when using the library with Nuxt

### ISSUE THREAD

**Issue by AlexLomm** [xkjyeah/vue-google-maps#299]
`plugins/vue2-google-maps`:

<img width="794" alt="screen shot 2018-01-25 at 4 03 55 pm" src="https://user-images.githubusercontent.com/11467210/35387495-6b0b47c2-01e9-11e8-8f8d-57a7a49a36f9.png">

`Console`:

<img width="834" alt="screen shot 2018-01-25 at 4 03 06 pm" src="https://user-images.githubusercontent.com/11467210/35387514-7d6ee8e2-01e9-11e8-821d-e2bae0c7a605.png">

Am I doing something wrong?

**Comment by AlexLomm** [comment]
This was caused by me listing `vue2-google-maps` in `nuxt-config` like this:

```
build: {
    vendor: [
        // ...
        'vue2-google-maps'
    ]
}
```

**Comment by ghost** [comment]
Do you happen to have an example repo of how you're using `vue2-google-maps` with Nuxt? I cannot, for the life of me, get it to work.

**Comment by xkjyeah** [comment]
It's in the README. make sure you're using the latest version of thus
library
