### ISSUE TITLE
SSR, potential memory leak

### ISSUE THREAD

**Issue by FranckFreiburger** [xkjyeah/vue-google-maps#300]
On server-side, the following promise: https://github.com/xkjyeah/vue-google-maps/blob/bc82d69cd52af8ac65f7a42bfee211bf2e727a2b/src/manager.js#L5-L11 is never resolved and may cause memory leak.
Maybe `loaded` could be set to `Promise.reject()` or similar.
Thanks.

**Comment by xkjyeah** [comment]
Rejecting the promise doesn't sound like a great idea.

Rejecting the promise can cause other code that depends on the `loaded`
promise to fail and throw unexpected errors.

For example, if I depended on the loaded promise to load the directions API.

I'm afraid this will be a wontfix

**Comment by FranckFreiburger** [comment]
I agree with that, rejecting is not the best solution, but ssr memory leaks may be quite annoying.

**Comment by xkjyeah** [comment]
Unless there is a solution to reject *after* the page has been rendered...

**Comment by xkjyeah** [comment]
A server-side renderer should be smart enough to delete references to the JS context of an already-rendered page. The GC should then clear up the references to the Promise.

This is the same principle with your browser: if you refresh the page, the unresolved Promises on the previous page should just be cleaned up.

If the GC isn't doing it, it is a bug with the SSR.
