### ISSUE TITLE
'google is not defined' when using google maps library extensions

### ISSUE THREAD

**Issue by snow-drop** [xkjyeah/vue-google-maps#301]
Good day. I'm trying to use oms (https://www.npmjs.com/package/overlapping-marker-spiderfier) in vue-google-maps but keep receiving an error that 'google is not defined.'
I've tried this link https://stackoverflow.com/questions/46772291/referenceerror-google-is-not-defined-vue, but still the issue persists. I think the cause is that, when I try to inspect to code of my vue app, it arranged the code this way:
```
<!-- built files will be auto injected -->

<script type="text/javascript" src="/js/app.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=<key>&amp;callback=vueGoogleMapsInit" async="" defer=""></script>
```
With this, oms cannot find the script because app.js executes first before the execution of google maps script. Is there a way to fix this behavior? like declaring the google maps script above the app.js? I don't have any idea if I can control the declaration of the scripts because as stated in the code above, "built files will be auto injected". Thanks in advance. :)

**Comment by snow-drop** [comment]
@xkjyeah 
Edit: I think found the cause after a lot of digging (manager.js:101)

```
googleMapScript.setAttribute('src', url);
googleMapScript.setAttribute('async', '');
googleMapScript.setAttribute('defer', '');
// document.body.appendChild(googleMapScript); <-- the problem
document.body.prepend(googleMapScript); <-- the hack solution
```

I still new in github stuffs, and further researching suggests to fork the github repo if the repo you are using does not fit on what you want. But could this solution be implemented instead in this repo?

**Comment by xkjyeah** [comment]
It is recommended to load google maps asynchronously, according to the
official documentation.

If you need to wait till the maps API has loaded, use the `loaded` promise.

**Comment by snow-drop** [comment]
@xkjyeah Hmmm. I think even if I wait till the maps API has loaded, the gmaps api script tag would still be added after the app.js script declaration because of the 'appendChild' method. So I think I can't use the 'loaded' promise because the library that I use needs the gmaps api script tag be loaded first before the app.js as it displays 'google is not defined' error. Anyway, thanks and good job maintaining this awesome library. :)

**Comment by xkjyeah** [comment]
Are you the maintainer of app.js?

**Comment by snow-drop** [comment]
@xkjyeah yes. why? Btw, Can you give a simple code snippet on how to use the 'loaded' promise? I tried it again today and it seems that the oms library works by using this code on created life cycle hook of vue and reverting the code change I've done above:

```
const options = { legWeight: 3 }
setTimeout(() => {
    const Spiderfier = require('overlapping-marker-spiderfier')
    const oms = new Spiderfier(this.$refs.map.$mapObject, options)
    console.log(oms)
}, 5000)
```

**Comment by xkjyeah** [comment]
Well then you should rewrite app.js to wait for the Google maps library to
be loaded...

**Comment by snow-drop** [comment]
@xkjyeah, I've researched on how to use the 'loaded' promise and come across this statement in https://github.com/GuillaumeLeclerc/vue-google-maps/wiki/Map:

"You will need to import the loaded promise and then do loaded.then(function() { /* the google object is defined now */})"

and tried it:
```
import * as VueGoogleMaps from 'vue2-google-maps'
// vue google maps initialization here...
...

 created () {
      VueGoogleMaps.loaded.then(() => {
        console.log('map loaded')
        const options = { legWeight: 3 }
        const Spiderfier = require('overlapping-marker-spiderfier')
        const oms = new Spiderfier(this.$refs.map.$mapObject, options)
        console.log(oms)
      })
 }
```

but it throws me the following error in browser: 

```
Uncaught (in promise) TypeError: Cannot read property '$mapObject' of undefined
```

Are the steps I've done correct on using the 'loaded' promise or there must be some more ceremonies to do before using the 'loaded' promise? So far I can't find an example on how to use the loaded promise. TIA.

**Comment by snow-drop** [comment]
@xkjyeah Nevermind, it is a problem with the object I'm referencing. In the code above inside the loaded.then(), 'this' seems to point to VueGoogleMaps object instead of the vue instance. Here's what I did:

```
mounted () {
      const vm = this
      VueGoogleMaps.loaded.then(() => {
        console.log('map loaded')
        setTimeout(() => {
          const options = { legWeight: 3 }
          const Spiderfier = require('overlapping-marker-spiderfier')
          const oms = new Spiderfier(vm.$refs.map.$mapObject, options)
          console.log(oms)
        }, 1000)
      })
}
```
I used a 1 second delay before initializing oms to make it work properly. That did it so I'm closing this. Thanks again :)

**Comment by xkjyeah** [comment]
You shouldnt use an arbitrary 1s delay.

Instead of loaded, use the gm.$mapCreated promise to wait until the
gm.$mapObject has been defined.

**Comment by snow-drop** [comment]
@xkjyeah, unfortunately, when I use the $mapCreated promise either on the mounted or created life cycle hook like this:

```
this.$refs.map.$mapCreated.then(() => {
    console.log('map created!')
})
```

I get the following warning/error: 

```
[Vue warn]: Error in created hook: "TypeError: Cannot read property '$mapCreated' of undefined"
```

I suspect that the map object still is not fully initialized during this time. I don't know if there must be more configuration to do before using the $mapCreated.

**Comment by xkjyeah** [comment]
1. Did you have <GmapMap ref="map"> ? (You need to create the reference
first)
2. Did you put the above code in the mounted () {} section? (It must be in
the mounted() section for references to work)

**Comment by snow-drop** [comment]
@xkjyeah Yeah I have ref attribute in may gmap and I am currently putting it on mounted hook but still the error occurs. :)

**Comment by max-schu** [comment]
I can confirm that $mapCreated is not available on $refs.map even though ref is set.
---
using it with nuxt as a plugin and 
`import * as VueGoogleMaps from '~/node_modules/vue2-google-maps/src/main'
`

**Comment by jbucior** [comment]
@snow-drop 
Could you show me your whole implementation of oms with vue-google-maps? I will be grateful.

**Comment by Ten-Taken** [comment]
Also receiving `google is not defined` errors.  In my case, I don't require manipulation of the map object, and the ref works fine (even outside mounted). I am only attempting to access the google object for its methods.

Per documentation, this should be possible with a computed property.

`import {gmapApi} from 'vue2-google-maps'
export default {
  computed: {
    google: gmapApi
  }
}`

When trying it this way, it seems to also return undefined and breaks Vue's ability to render the component containing the map.

**Comment by fofiu** [comment]
Any resolution to this issue? I would also like to find out.

**Comment by HKskn** [comment]
I have same error like Ten-Taken wrote. Any resolution to this issue?

**Comment by Ten-Taken** [comment]
@HKskn - A temporary workaround is to import the API natively, and then access it from the DOM window object. This however won't help you if you need to specifically interact with the GMap components from this module within Vue.

**Comment by fofiu** [comment]
Here's my code and how I got it to work, maybe it'll help someone:

```
<template>
  <div class="columns is-multiline">

    <div class="column is-full has-margin-sides-bottom">
      <div>
        <gmap-autocomplete
          id="location"
          class="input is-pulled-left"
          placeholder="Address or ZIP"
          @place_changed="setPlace"
        />
      </div>
      <div class="select">
        <select
          v-model="distance"
          class="is-rounded"
          name="distance">
          <option value="5">5 Miles</option>
          <option value="10">10 Miles</option>
          <option value="25">25 Miles</option>
          <option value="50">50 Miles</option>
          <option value="75">75 Miles</option>
          <option value="100">100 Miles</option>
        </select>
      </div>
      <a class="button is-primary">Search</a>
    </div>

    <div class="column is-full">
      <GmapMap
        id="map"
        ref="map"
        :center.sync="center"
        :zoom.sync="zoom"
        map-type-id="terrain">

        <div v-if="mapLoaded">
          <GmapMarker
            v-for="(m, index) in markers.data"
            :key="index"
            :position="{lat: m.lat, lng: m.lng}"
            :clickable="true"
            :draggable="true"
          />
        </div>
      </GmapMap>
    </div>
  </div>
</template>

<script>
/* global google */
import axios from 'axios'

export default {
  data: function () {
    return {
      center: { lat: 34.070321, lng: -84.274133 },
      zoom: 11,
      userPosition: null,
      markers: [],
      mapLoaded: false,
      // API Variables
      distance: 25,
      results: 25,
      page: 1,
      place: null
    }
  },

  watch: {
    distance: function (n) {
      this.getMarkers()
    },
    markers: function (newMarkers, o) {
      // Ensure we have markers in the list so that
      if (newMarkers.data.length > 2) {
        const bounds = new google.maps.LatLngBounds()
        for (let m of newMarkers.data) {
          bounds.extend({lat: m.lat, lng: m.lng})
        }
        this.$refs.map.fitBounds(bounds)
      }
    }
  },

  mounted: function () {
    this.getMarkers()
  },

  methods: {
    getMarkers: function () {
      // Only after Google Maps loads...
      this.$refs.map.$mapPromise.then(() => {
        // 1). get the Markers' data from the API
        var url = 'https://<api-server>/locator/v1/locations/' +
                  this.distance +
                  this.place.geometry.location.lat() +
                  '/' +
                  this.place.geometry.location.lng() +
                  this.results +
                  '/' +
                  this.page
        axios.get(url).then(response => {
          this.markers = response.data
        })

        // 2). Set "mapLoad" = true so we can add the Markers
        this.mapLoaded = true
      })
    },

    // Set the location from user's input
    setPlace (place) {
      this.place = place
    }
  }
}
</script>
```

**Comment by Ten-Taken** [comment]
@ccchr - Thanks! I will test this this evening. It looks similar to some of the boolean promise solutions, but you may have picked up on something I missed while trying those.

**Comment by rnenjoy** [comment]
Heres what worked for me, just sharing to help cause it needed alot of googling to come here:

```
mounted() {
    this.$refs.map.$mapPromise.then(() => {   // add ref="map" to the <GmapMap ref="map"> like so
      this.googleMapsInitialized = true   // googleMapsInitalized needs to be in data object to be reactive
    })
  },

  computed: {
    markerSize() {
      if (!this.googleMapsInitialized) return null
      return new window.google.maps.Size(10, 10)
    },
    markerIcon() {
      return {
        url: 'http://10.0.1.8:3000/img/icons/maps-marker.png',
        scaledSize: this.markerSize,
      }
    },
```

**Comment by rcosta-gcare** [comment]
@snow-drop were you able to make overlapping-marker-spiderfier works?

**Comment by josegus** [comment]
I've got this strange issue:

I have two components, one is working normal with autocomplete places, the second one show me this error thread error, but I'm not using anything when the map load (not markers, not polygons, nothing), I'm just showing an empty autocomplete

![image](https://user-images.githubusercontent.com/13947849/83342055-8a86e580-a2b8-11ea-8df7-39de2c217823.png)

**Comment by pmfeo** [comment]
Why is this closed? Any solution fot this? I'm using Gridsome and tried the above solutions provided with no success.
