### ISSUE TITLE
Markers don't show up in latest Vue.js

### ISSUE THREAD

**Issue by itomxi** [xkjyeah/vue-google-maps#31]
The map itself works, but markers just aren't there when using **Vue.js > 2.1.6**.

**Comment by xkjyeah** [comment]
Do you mean you have tried multiple versions of Vue, or only one? Do you
have a test case? E.g. a JSFiddle

**Comment by cj** [comment]
I'm having the same issue with: vue: `2.1.6`

```javascript
<div>
  <gmap-map style="width: 100%; height: 100%; position: absolute; left:0; top:0"
    :center="mapCenter"
    :zoom="12"
  >

    <gmap-marker
      v-for="m in [mapCenter]"
      :position="m.position"
      :clickable="true"
      :draggable="true"
      @click="center=m.position"
      ></gmap-marker>

  </gmap-map>
</div>
```

The marker isn't showing

**Comment by xkjyeah** [comment]
Is this with npm or the web bundle?

**Comment by ashtonzheng** [comment]
When i dynamically changed the markers array value, the marker positions didn't seem to update on the map. Any thoughts what i may be doing wrong ?

`for(var i = 0; i < this.deals.length; i++ )
                  {
                        if(this.deals[i]['positions'])
                        {
                            var tempPositions = JSON.parse(this.deals[i]['positions']);
                            for(var j = 0; j < tempPositions.length; j++)
                            {
    
                                var tempMarker = {position : {lat: parseFloat(tempPositions['lat']), lng: parseFloat(tempPositions['lng'])}}
                                var tempAllMarkers = [];
                                tempAllMarkers.push(tempMarker);
    
                                this.markers = tempAllMarkers;
                            }
    
                        }

                  }`

**Comment by zashton** [comment]
I get these warnings when i try to set an URL string as the marker icon, but it still works correctly though.

vue.js?3de6:525 [Vue warn]: Invalid prop: type check failed for prop "icon". Expected Object, got String. 
(found in component <GmapMarker>)

**Comment by xkjyeah** [comment]
@ashtonzheng Fixed in latest version. Thanks

@itomxi I need a reproduction of the bug in order to fix it. A working version is found [here](http://xkjyeah.github.io/vue-google-maps/basic-marker.html). If there's no repro I'll be closing this bug

**Comment by zashton** [comment]
@xkjyeah 
thanks for the prompt update,  got this error after i gulp when i updated to the latest version though. 

./resources/assets/js/app.js 18:27-64]
  message: './resources/assets/js/app.js\nModule not found: Error: Can\'t resolve \'vue-loader\' in \'

**Comment by xkjyeah** [comment]
Are you building your package with webpack? You need to `npm install vue-loader`

**Comment by zashton** [comment]
@xkjyeah excellent , now it works after i installed vue-loader. Thanks so much 👍
