### ISSUE TITLE
How use PlacesService class and nearbySearch method

### ISSUE THREAD

**Issue by sbstnplcn** [xkjyeah/vue-google-maps#314]
Hello,
How can I use the PlacesService class from Google API to use nearbySearch method to show in my map nearby places with specific types.
https://developers.google.com/maps/documentation/javascript/3.exp/reference#PlacesService
https://developers.google.com/places/supported_types?hl=en

Thanks

**Comment by xkjyeah** [comment]
https://github.com/xkjyeah/vue-google-maps/wiki/vue-google-maps-FAQ
