### ISSUE TITLE
access to other google maps APIs

### ISSUE THREAD

**Issue by apple314159** [xkjyeah/vue-google-maps#32]
I would like to use the google.maps.DirectionsService.
How can I get access to the google.maps object?

**Comment by xkjyeah** [comment]
loaded.then(() => { you can use google.maps here })

**Comment by mickspecial** [comment]
Sorry,

Need some assistance

In my components the only way I have been able to access is via other API's is via

`const directionsService = new window.google.maps.DirectionsService()`

Whats the best approach ? Thanks

**Comment by xkjyeah** [comment]
That is probably the best way, actually. This is because the directions
service will not directly affect HTML UI elements, so there is no need to
wrap it around a Vue component.
