### ISSUE TITLE
How to hide system makers & overwrite custom makers?

### ISSUE THREAD

**Issue by Horzen** [xkjyeah/vue-google-maps#321]
![0c8b56bc-54c1-49f4-9e9d-e148a24900e5](https://user-images.githubusercontent.com/32396611/36071409-bf8abf32-0f48-11e8-95ea-a793f46971b3.png)

My map is above.I have 2 questions:
1.How to hide system makers?
2.How to overwrite custom makers?I wanna  achieve a function just like click system makers and show their details.
Have you have any idea?THX

**Comment by pmochine** [comment]
Hey hey :)

For your first question. I just used the normal style and deactivated some POI etc. Go on: https://mapstyle.withgoogle.com/ and select the Standard and then click on more Options. You can set everything there.

For custom markers go on https://developers.google.com/maps/documentation/javascript/custom-markers

**Comment by Horzen** [comment]
Great.Thank u very much,@pmochine.

**Comment by kps1ny** [comment]
@pmochine Thanks for this hint. How did you actually apply your adjusted style to the Vue map?

I have tried via the Vue.use / load as well as &lt;gmap&gt; options but either I haven't got the syntax right or there's some other place to specify the style changes.

I'm just trying to hide all poi markers: style=feature:poi%7Cvisibility:off

-Ken

**Comment by kps1ny** [comment]
@pmochine Please disregard my previous message, found the answer in #305.
