### ISSUE TITLE
how to use on electron-vue

### ISSUE THREAD

**Issue by webafra** [xkjyeah/vue-google-maps#322]
hi .

i want use this package on electron-vue ( nodejs package ) but after import project not work and reject this error : 

`/Volumes/File Drive/electron-apps/restaurant-application/node_modules/vue2-google-maps/dist/compone…:3 Uncaught SyntaxError: Unexpected token <
    at createScript (vm.js:53)
    at Object.runInThisContext (vm.js:95)
    at Module._compile (module.js:543)
    at Object.Module._extensions..js (module.js:580)
    at Module.load (module.js:488)
    at tryModuleLoad (module.js:447)
    at Function.Module._load (module.js:439)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at Object.<anonymous> (/Volumes/File Drive/electron-apps/restaurant-application/node_modules/vue2-google-maps/dist/main.js:35)`

please help me .

**Comment by xkjyeah** [comment]
Does this suggestion help?

https://github.com/xkjyeah/vue-google-maps/wiki/Developing---Building---Nuxt---ESLint-FAQ

**Comment by xkjyeah** [comment]
Try the recommendation here:

https://github.com/xkjyeah/vue-google-maps/wiki/Developing---Building---Nuxt---ESLint-FAQ

You may also need to adjust webpack configuration to include the node modules folder

**Comment by webafra** [comment]
no , not work : 

`ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/settings/settings.vue
Module not found: Error: Can't resolve '/node_modules/vue2-google-maps/src/main' in '/Volumes/File Drive/electron-apps/restaurant-application/src/renderer/components/settings'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/settings/settings.vue 4:0-73
 @ ./src/renderer/components/settings/settings.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js`

**Comment by xkjyeah** [comment]
How about adding a number of ../ in order to reach the project root
directory?

**Comment by webafra** [comment]
@xkjyeah : Thank You :)
this Code Worked : 

import * as VueGoogleMaps from 'vue2-google-maps/src/main'

**Comment by xkjyeah** [comment]
Hey do you mind adding your solution to the Wiki?

**Comment by webafra** [comment]
My problem has been resolved.
sorry , I'm not familiar with the process.
