### ISSUE TITLE
How to add buttons for controlling inside the map

### ISSUE THREAD

**Issue by abrhambas01** [xkjyeah/vue-google-maps#323]
I tried asking in stackoverflow but there's no label/tag  for this package. So, maybe I can ask some help from you guys. I would like to know how to put a button inside the map. I have my images inside the assets/icons folder in the same directory of the file.

**Comment by xkjyeah** [comment]
You can create a marker and set the icon of the marker to the image that
you have prepared.

**Comment by abrhambas01** [comment]
Just adding a button on the map is simple : 
(https://stackoverflow.com/questions/6037712/how-to-float-a-div-over-google-maps)
