### ISSUE TITLE
Update Map Marker Props

### ISSUE THREAD

**Issue by keithgulbro** [xkjyeah/vue-google-maps#326]
Hi there,

Thanks for creating a great Google Maps package. My issue is as follows: I'd like to change the marker icon of a given marker on change of a select element. I've been able to execute the onChange event for the select element to trigger updating the prop value of the marker. However, while inspecting the map markers props inside vuejs dev tools, it says the marker.icon.url has indeed been updated to my desired path but isn't reflected inside the UI (the marker image doesn't change to reflect the new prop marker.icon.url path)

Any ideas?

**Comment by keithgulbro** [comment]
Never-mind, I figured it out, for anyone looking to do something similar the code I used was:

`this.$refs.markerRefValue.$markerObject.setIcon(icon_path)`

**Comment by anselmobattisti** [comment]
I was looking for other thing but you helped me sir

    updatePosition () {
      this.m.lat = this.$refs.marker.$markerObject.position.lat()
      this.m.lng = this.$refs.marker.$markerObject.position.lng()
    },
