### ISSUE TITLE
Mouseleave does not fire on gmap-marker

### ISSUE THREAD

**Issue by BennieBe** [xkjyeah/vue-google-maps#328]
I have an issue where I try to react to a mousehover on a specific marker on a map.
I want to use 'mouseleave' and 'mouseover' to fire the function exactly once and allow the marker to 
bounce and then to stand still again when leaving the marker bounds.
The mouseover function works just fine. However, the mouseleave function is not fired when I implement it. The mouseout function is, however, but I do not need this one, I need mouseleave. Is that a bug? 

These are my functions in gmap-marker:
`<gmap-marker
      @mouseleave="bounceMarkerOnMapMouseOver(marker.contents.providerID, false)"
      @mouseover="bounceMarkerOnMapMouseOver(marker.contents.providerID, true)"
>`

**Comment by xkjyeah** [comment]
Unfortunately it's not supported by the under API (https://developers.google.com/maps/documentation/javascript/reference#Marker). Won't be able to support.

**Comment by ZeroAuto** [comment]
I know that this issue is closed but I am wondering if anyone found a workaround?

**Comment by danbhala** [comment]
Try using `@mouseout` instead
