### ISSUE TITLE
How to change existing markers?

### ISSUE THREAD

**Issue by mtechoh** [xkjyeah/vue-google-maps#329]
How can I reference an existing marker so I can change the animation state?

I have the map working and a list of markers showing up properly. I also have a side list of details for those markers. On hover of items in the list I'd like the corresponding marker on the map to change animation state to bounce, but I have no idea how to reference the marker.

Can someone point me in the right direction? Thanks.

**Comment by snow-drop** [comment]
use ref on your marker. Then do this if you set ```ref="marker"```:

```this.$refs.marker.$markerObject.setAnimation(google.maps.Animation.BOUNCE)```

**Comment by mtechoh** [comment]
`       <gmap-marker
          :key="i" v-for="(m,i) in paginated('items')"
          :position="m.position"
          :animation="0"
          :clickable="true"
          :title="m.name"
          :label="String(i+1)"
          :zIndex="i+100"
          :ref="marker"
          @click="toggleInfoWindow(m,i)"
        ></gmap-marker>
`

And then as a function on hover of the list item:
`     this.$refs.marker.$markerObject.setAnimation(google.maps.Animation.BOUNCE)
`

Gives: "Uncaught TypeError: Cannot read property '$markerObject' of undefined"

**Comment by snow-drop** [comment]
Remove the ```:``` in ```:ref```

**Comment by mtechoh** [comment]
That changes the error to: "Uncaught TypeError: Cannot read property 'setAnimation' of undefined"

**Comment by snow-drop** [comment]
Oh it seems that you have more than one marker. I just noticed it. to do that, you need to keep track of the index of the marker and do the following:
```this.$refs.markers[markerIndex].$markerObject.setAnimation(google.maps.Animation.BOUNCE)```

I suggest you change the ```ref="marker"``` to ```ref="markers"```

**Comment by mtechoh** [comment]
Thank you! That works.

**Comment by snow-drop** [comment]
Glad to be of help. :)
