### ISSUE TITLE
Why is `vue-loader` a dependency?

### ISSUE THREAD

**Issue by dotboris** [xkjyeah/vue-google-maps#33]
Looking at `package.json`, I see that `vue-loader` is a dependency. My understanding is that `vue-loader` is meant to be a dev dependency used with `webpack`. Shouldn't it be in the `devDependencies` section?

**Comment by xkjyeah** [comment]
Good question, and it's because .vue files are being distributed in the npm
package and require()d from the source. Which makes vue-loader almost
certainly a dependency.

**Comment by dotboris** [comment]
Even if you require `.vue` files in the source, `vue-loader` should still be a development dependency and not a runtime / production dependency.

Any app that uses your lib will need both `webpack` and `vue-loader` for building their bundle. Once the app is built, you don't need `webpack` or `vue-loader` anymore.
