### ISSUE TITLE
Problem with map panning: click-and-drag goes only a few pixels at a time

### ISSUE THREAD

**Issue by kps1ny** [xkjyeah/vue-google-maps#330]
Hi. Thanks very much for this repo. Three weeks ago I set up a web page with a map and it worked great. Using a mouse, I could click the map and drag it all the way across the screen. The center updated and all was well. Very smooth panning.

Yesterday, however, I noticed that when clicking the mouse and starting to drag, the map would pan only a few pixels, then just stop. Console shows no errors. 

This process can be repeated numerous times so the map can be panned slowly, but only with many clicks and tiny drags. Clicking on the map and then pressing the arrow keys does allow the map to be panned that way (the longer the arrow key is pressed, the larger the panning effect).

I'm (now) using the latest version of this repo downloaded earlier today, same result.

Same behavior on Chrome and Firefox on two different computers. They have had no extensions installed during the last few weeks and may or may not be the same versions themselves.

Sounds crazy, no doubt. What advice have you got for troubleshooting this?

-Ken

**Comment by xkjyeah** [comment]
Unfortunately it's a regression that appeared after Google updated the maps API.

See https://github.com/xkjyeah/vue-google-maps/issues/325

The solution is to avoid the second line in code:
```
<GmapMap :center="x"
@center_changed="x=$event">
```

This is because the center_changed event fired while you are panning. This forces an update of the map center because X changed. In the most recent Google maps JS API that would terminate an existing pan

**Comment by kps1ny** [comment]
Ah. My search did not turn up that issue. The solution, then, was to have a temp variable to track the center's change, then on dragend sync it with the main variable and save that.

I never considered that the issue might have arisen from Google changing things on their end.

Thanks for the quick response!

-Ken

**Comment by kaihendry** [comment]
Couldn't this library fix on a particular working version of Google maps? I'm a bit annoyed my App just broke because of a change in an underlying dependency.

**Comment by vesper8** [comment]
@kps1ny can you share your solution on how you were able to get the new value of the map center once the drag end event was triggered?

I don't know how to listen to the drag end event or how to get the new center at that point

**Comment by kps1ny** [comment]
Hi @vesper8,

This is what worked for me, when I posted more than two years ago.


My map instantiation, which includes the @dragend and @center_changed listeners:

`<gmap-map :center="mapCenter" :zoom="mapZoom" map-type-id="terrain" style="width: 99%; height: 600px; border: 1px solid black;" @center_changed="updateMapCenter($refs.gmap.$mapObject.getCenter())" @zoom_changed="updateMapZoom" :options="{streetViewControl: false, scaleControl: true, mapTypeControl: false, scrollwheel: false}" ref="gmap" @rightclick="addMapMarker" @dragend="saveNewMapCenter" >`


In my Vue app data object I set a global temp variable to keep track of the map's center: 

`mapCenterTemp: {lat: game.Meta.MapCenterLat, lng: game.Meta.MapCenterLng}`



That variable is updated when the drag-end occurs via these two methods in my Vue .js file:

```
updateMapCenter(newCenter) {
	this.mapCenterTemp = {
		lat: newCenter.lat(),
		lng: newCenter.lng(),
	}
}

```


The new map center is saved (via an AJAX call, not shown) to the server for next use of the map:

```
saveNewMapCenter() {
	this.ajax({action: "saveMapSettings", centerLat: this.mapCenterTemp.lat, centerLng: this.mapCenterTemp.lng, zoom: this.mapZoom});
}

```


-x-
