### ISSUE TITLE
Lodash is back in my app bundle !

### ISSUE THREAD

**Issue by wmcmurray** [xkjyeah/vue-google-maps#332]
Some past issues has mentioned that this package causes inclusion of the whole lodash library in apps bundle including this project (like this issue https://github.com/xkjyeah/vue-google-maps/issues/89).

It has been fixed in v0.8.6, lodash was not included in my bundle yesterday, but today it is !

I think recent changes has brought back the issue : 

The `babel-plugin-lodash` plugin has been removed : 
https://github.com/xkjyeah/vue-google-maps/commit/491168e675f3893ca038de89f6ef04e0fe00e558#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L29

This too : 
https://github.com/xkjyeah/vue-google-maps/commit/e9173d25dafb03917349ace74f454268897499c6#diff-e56633f72ecc521128b3db6586074d2cL16

Causing (I think) all imports of lodash to be back to their wrong form : https://github.com/xkjyeah/vue-google-maps/commit/22caa52bab7eef3a2426dd7dec426f931bd619f1

**Explanation :**
`import _ from 'lodash'` causes the whole lib to be included,
`import _clone from 'lodash/clone'` include only this function

**Comment by mojereliev** [comment]
Yes, I just now find who adds lodash to the bundle
![image](https://user-images.githubusercontent.com/13470898/36527752-be99996a-17d4-11e8-8c37-045a35838acb.png)

**Comment by rdunk** [comment]
Also seeing 0.8.7 increases bundle size by 100kb+ due to lodash, rolling back to 0.8.6 resolves it.

**Comment by xkjyeah** [comment]
Sorry about the change. I understand it's a big (pun not intended) issue for use cases where bandwidth is a constraint.

I've removed the lodash dependency in 0.8.8. I hope it helps!

For good measure, I've added a simple check to make sure that lodash **never** appears again in the build file.

**Comment by wmcmurray** [comment]
I finally had time to check this,
and I can confirm that lodash is not added to my bundle in `0.8.8`.
Thanks ! :+1:

**Comment by fhusquinet** [comment]
Hi guys!

I don't know if I'm doing something wrong but I can't seem to include vue2-google-maps without lodash...
My build is already quite big as it is and lodash a good 25kB gzipped / 80kB minified to it which is quite a lot.

I'm including it like this:  import * as VueGoogleMaps from 'vue2-google-maps';
Here's two screenshots of my dependencies, one with import and one without.
![screen shot 2018-03-08 at 11 54 18](https://user-images.githubusercontent.com/11152814/37147545-905cd8ac-22c7-11e8-8820-ed0b190a321b.png)
![screen shot 2018-03-08 at 11 54 10](https://user-images.githubusercontent.com/11152814/37147546-90918390-22c7-11e8-8e86-4e743d11179d.png)

Any help would be really nice :)

**Comment by xkjyeah** [comment]
You need to upgrade to the latest bundle I believe. npm install
vue2-google-maps@latest

**Comment by fhusquinet** [comment]
I tried it on a new project just to be sure, once I do:
import * as VueGoogleMaps from 'vue2-google-maps';
Vue.use(VueGoogleMaps);
Lodash is included in my build.

Version seem to be 0.8.11.

**Comment by xkjyeah** [comment]
Hey so I looked into it...

It's not importing the whole lodash, but the parts that this library uses
(clone, pickBy, omit, mapValues, forEach, forIn).

This kinda saved 100kb over the original 140kb of lodash, but yea I guess
it's still pretty heavy.

Sigh... give me some to cut it down further. I guess I might have to
abandon all lodash dependencies altogether :( Damn. I liked that library.

**Comment by fhusquinet** [comment]
Mhhh, this is weird. On my side it seem to include most of lodash. I don't know if something's wrong on my side because I can see in your code that you indeed only include a few parts but I end up with everything at the end somehow. 

I'm using Laravel and Laravel Mix for my project if that's any help.

Anyways, take your time and thanks for the great package :)

<img width="1393" alt="screen shot 2018-03-10 at 10 04 50" src="https://user-images.githubusercontent.com/11152814/37240365-88f3ae18-244a-11e8-8916-b04ab0fb95cc.png">

**Comment by wmcmurray** [comment]
I think everything is ok here, more lodash methods are included because the ones used are dependent on the others, so it needs to include those as well ? :thinking:  (It's just a supposition, I haven't verified that info).

But as we can see in your screenshot, methods are added individually (as wanted) otherwise we would see a big square of more than 500 KB ! :weight_lifting_woman: 

**Also :** I don't care IMO if this lib includes lodash because we already use it in our projects so it'll end up in our bundles anyway. So there is no rush to remove all lodash if you don't want to @xkjyeah aha :slightly_smiling_face:
