### ISSUE TITLE
Hide controls

### ISSUE THREAD

**Issue by Sjoerd** [xkjyeah/vue-google-maps#333]
Hello,
How can I hide all controls?
(full screen, satelite, zoom, streetview)

**Comment by abrhambas01** [comment]
add the property : 
disableDefaultUI : true 
in your mapOptions object. 
```

	<gmap-map :center="center" :zoom="7" id="map"
		:options="mapOptions"
		>
```

**Comment by Sjoerd** [comment]
Thanks!

**Comment by antonioEDER** [comment]
Thanks! You helped me.

**Comment by rohitnairtech** [comment]
Doesn't work for me
