### ISSUE TITLE
Import as plugin in Nuxt Project

### ISSUE THREAD

**Issue by Blemming** [xkjyeah/vue-google-maps#341]
If you are importing vue-google-maps as a plugin in Nuxt I'd recommend importing as
``
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps/dist/main'
``
Instead of the "src" folder.  Importing from "src" will give you a SCRIPT5007 error in IE11 as plugins are apperently not transposed by babel.

**Comment by xkjyeah** [comment]
Hi, please check out the README. I've updated that with instructions for Nuxt.js. Let me know if you still encounter issues

**Comment by Blemming** [comment]
thanks !
