### ISSUE TITLE
paths_changed will goback to mapcenter?

### ISSUE THREAD

**Issue by mythbobo** [xkjyeah/vue-google-maps#349]
hi, your demo:
xkjyeah.github.io/vue-google-maps/polygon-editing.html
When I move a point over the window, will return to the center of the map.
I don't want to do it..
can you help me? thanks!

**Comment by xkjyeah** [comment]
Hey would you be able to try the latest published version (v0.8.10) and let
me know if it fixes the issue?

**Comment by mythbobo** [comment]
Yes! well done
Thanks again
