### ISSUE TITLE
Request feature - Map Controls

### ISSUE THREAD

**Issue by wenxin3262** [xkjyeah/vue-google-maps#35]
Suggesting add control slot for custom controls.
google document on this feature: https://developers.google.com/maps/documentation/javascript/controls

PS I can work on it when I have time, since I am doing a project using your library.

**Comment by xkjyeah** [comment]
Hi,

If you choose to not go with the official API there is an alternative:

See

http://xkjyeah.github.io/vue-google-maps/info-bar.html

**Comment by xkjyeah** [comment]
This method draws components in the "visible" slot over the map

**Comment by awitherow** [comment]
@wenxin3262 have you taken any steps, figured out anything, etc since your question?

**Comment by mercs600** [comment]
@awitherow @wenxin3262 You have access to map controls by refs. 
```js
this.$refs.map.$mapObject.controls
```

**Comment by diegoazh** [comment]
This issue can be close?
