### ISSUE TITLE
Infowindow Html

### ISSUE THREAD

**Issue by Matthewloughton** [xkjyeah/vue-google-maps#390]
Good day,

We have raw HTML that we want to put in an infowindow. If I remember correctly, the google maps API has this support out of the box. How would I do this with the vue-google-maps?

Our code for the InfoWindow:

<gmap-infoWindow :position="infoWindow.position" :opened="infoWindow.opened" @closeclick="infoWindow.opened=false">
                    {{infoWindow.content}}
                </gmap-infoWindow>

where **infoWindow.content** is where we bind the raw html.

Thanks!

**Comment by xkjyeah** [comment]
Create a div with v-html="..."

**Comment by Matthewloughton** [comment]
Working thanks!
