### ISSUE TITLE
Object.entries breaks in IE

### ISSUE THREAD

**Issue by jasonlewis** [xkjyeah/vue-google-maps#393]
IE no longer works due to the use of `Object.entries` in the [`mapElementFactory.js`](https://github.com/xkjyeah/vue-google-maps/blob/v0.9.2/src/components/mapElementFactory.js#L135) file.

Not sure if it's best to polyfill it in my application or if this project should provide the polyfill.

**Comment by xkjyeah** [comment]
Is there an automated way to test for compatibility? I'm open to exploring
restricting the subset of JavaScript used, but only if there's a way to
identify the later features that are being used.

**Comment by jasonlewis** [comment]
Hm, automated, not 100% sure to be completely honest.

I think the best bet for now would to be add a transform for `Object.entries` which can be found here: https://github.com/gas-buddy/babel-plugin-transform-object-entries

**Comment by xkjyeah** [comment]
Try the better-supported plugin: https://stackoverflow.com/questions/35090153/babel-support-for-object-entries

I'm not including transform-runtime because there were previous complaints that babel-runtime was unnecessarily bloating up the library.
