### ISSUE TITLE
Issue in IE 11 with supporting property or method 'assign'

### ISSUE THREAD

**Issue by Oksana13** [xkjyeah/vue-google-maps#397]
Hello,

Everything works fine in Chrome, Safari, Mozila, Edge, but I ran into issue in Internet Explorer 11 "SCRIPT438: Object doesn't support property or method 'assign'". It refers to this row in js file:

![image](https://user-images.githubusercontent.com/14080083/39246309-d3661b16-489e-11e8-8b32-6908c9d8eff4.png)

Could you help with resolving it?

**Comment by xidedix** [comment]
similar for `Object.entries` here

**Comment by xkjyeah** [comment]
Please use babel-polyfill
