### ISSUE TITLE
Cannot show autocomplete suggestion on dialog window

### ISSUE THREAD

**Issue by evanRoberto** [xkjyeah/vue-google-maps#398]
Hi I have a problem when applying autocomplete function on a dialog window. Generally the user click a button that will open a dialog window, later in there the user can use the auto complete function. But although it shows the input box, it doesn't show any suggestion address.

For reference I use this window dialog http://element.eleme.io/#/en-US/component/dialog#dialog

**Comment by evanRoberto** [comment]
manually set the z-index solve the problem

**Comment by saefulloh** [comment]
where we set z-index ? please any example about this ?

**Comment by Soul244** [comment]
I was troubling same problem when i use modal. I set z-index for auto suggestion div class:

```
.pac-container {
    z-index: 9999;
}
```
