### ISSUE TITLE
bounds_changed not triggered when the map initialized

### ISSUE THREAD

**Issue by xdimension** [xkjyeah/vue-google-maps#40]
Hi,

I found the `bounds_changed` event is not triggered when the map is initialized. After taking a look into the code in *mapImpl.js*, I see the following lines:
```javascript
      // manually trigger center and zoom
      this.$mapObject.addListener('center_changed', () => {
        this.$emit('center_changed', this.$mapObject.getCenter())
        this.$emit('bounds_changed', this.$mapObject.getBounds())
      })
      this.$mapObject.addListener('zoom_changed', () => {
        this.$emit('zoom_changed', this.$mapObject.getZoom())
        this.$emit('bounds_changed', this.$mapObject.getBounds())
      })
```
I'm not sure why `center_changed` isn't triggered, but anyway changing that code to below seems to resolve the issue (it works well also on `center_changed` and `zoom_changed`).
```javascript
      this.$mapObject.addListener('center_changed', () => {
        this.$emit('center_changed', this.$mapObject.getCenter())
      })
      this.$mapObject.addListener('zoom_changed', () => {
        this.$emit('zoom_changed', this.$mapObject.getZoom())
      })
      this.$mapObject.addListener('bounds_changed', () => {
        this.$emit('bounds_changed', this.$mapObject.getBounds())
      })
```
Could you please review it? Thanks!

**Comment by awitherow** [comment]
@xdimension could you open up a PR with the changes working and perhaps use something like now.sh to show an example of it working?

@xkjyeah are we doing any tests for such things?

**Comment by xkjyeah** [comment]
@awitherow I would love to have (automated) tests! Currently all tests are manually done by going through the examples one-by-one. I get a huge sense of trepidation with every minor version update to Vue. Do you have an idea of how to integrated Google Maps into automated tests?

**Comment by xkjyeah** [comment]
@awitherow  The changes have already been made. If the map bounds appears in the [example](http://xkjyeah.github.io/vue-google-maps/all-components.html) then it should be working

**Comment by awitherow** [comment]
@xkjyeah on the tests subject, no idea where to get started to be honest 🤷‍♂️
