### ISSUE TITLE
How to stylize the maps? 

### ISSUE THREAD

**Issue by arpowers** [xkjyeah/vue-google-maps#41]
Can't seem to figure it out and the API docs are a bit vague. 

Whats the appropriate way to add something like https://snazzymaps.com/  to the maps? 

Other styling information?

**Comment by xkjyeah** [comment]
Unfortunately I'm not very clear about this myself. The most stylized maps I've used is based on the example by Guillaume Leclerc (http://xkjyeah.github.io/vue-google-maps/all-components.html). You could consult the source code, perhaps?

**Comment by arpowers** [comment]
Ya i got it worked out... works like this: 

`<gmap-map  :options="{styles: styles}" ></gmap-map>`

`<script>
export default {
  data () {
    return {
      styles: [ // styles here ]
    }
  }
}
</script>`

**Comment by awitherow** [comment]
@arpowers could you maybe open up a quick PR, editing the docs to show how you figured this out? 👍

**Comment by shayneo** [comment]
added a PR https://github.com/xkjyeah/vue-google-maps/pull/85

**Comment by kodekrendel** [comment]
@arpowers thanks mate!!!
