### ISSUE TITLE
Autocomplete, Places, restrictions ??

### ISSUE THREAD

**Issue by vAhyThe** [xkjyeah/vue-google-maps#413]
Hi,
 how i setup restrictions to search by autocomplete in places.
Because i want to search on small size, like country not whole world :)

thx

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries

**Comment by AdrienCasta** [comment]
Hello @vAhyThe, here is my solution to search addresses only in France. You just  have to add [ISO ALPHA-2 Code](http://www.nationsonline.org/oneworld/country_code_list.htm) from list.

```javascript
<template>
    <gmap-autocomplete
      :options="autocompleteOptions" />
</template>

export default {
  data() {
    return {
      autocompleteOptions: {
        componentRestrictions: {
          country: [
            'fr',
          ],
        },
      },
    };
  }
}
```

**Comment by vAhyThe** [comment]
Hi @AdrienCasta,
I will try it,
thx

**Comment by vAhyThe** [comment]
@AdrienCasta it works THX!!!

**Comment by dharmdeep** [comment]
Hello @AdrienCasta,  @vAhyThe 

Thanks for posting this useful info. Do you have any idea about how to restrict particular  **city** with in country.

Thanks in advance
