### ISSUE TITLE
Polygon paths not changed in data when edited on map

### ISSUE THREAD

**Issue by reinzor** [xkjyeah/vue-google-maps#42]
Two way binding does not seem to work for polygons, is this observation correct?

If so, is there a way to get the modified polygon?

**Comment by xkjyeah** [comment]
By "not changed" do you mean the path_changed event was not triggered?

**Comment by xkjyeah** [comment]
Hi,

Tested it and discovered it was indeed not firing. I've pushed v0.5.3 out. Would you care to try it?

Here's the online example: http://xkjyeah.github.io/vue-google-maps/polygon-editing.html

**Comment by reinzor** [comment]
Hi xkjyea, thanks for your quick fix! I verified that the event is fired now. Thanks! 

I got it to work now based on the sample code you provided; however, don't we want the model to update, e.g. paths when editing this path in the maps view? 

Thanks again for this awesome package!
