### ISSUE TITLE
autocomplete not working 

### ISSUE THREAD

**Issue by rockyshukla** [xkjyeah/vue-google-maps#420]
hello guys thanks for such wonderfully template but now i stuck in situation and don't know how to use  as per you instruction in document i had code like 

 
        Vue.use(VueGoogleMaps, {
              load: {
                     key: 'YOUR_API_TOKEN',
                   libraries: 'places', // This is required if you use the Autocomplete plugin
           },
i had call libraries places but still autocomplete not working since i had not found much detail on libraries places in document so i posted here

**Comment by SimonDesautels** [comment]
Your settings seems fine to me.
What does your vue component template and script section file looks like ?

**Comment by rockyshukla** [comment]
@SimonDesautels i found my issue it because of modal autocomplete value showing behind the modal
here is solution
  .pac-container.pac-logo { z-index: 999999; }
