### ISSUE TITLE
Bug - Autocomplete: 'location' of undefined when pressing "enter"

### ISSUE THREAD

**Issue by pmochine** [xkjyeah/vue-google-maps#426]
**Describe the bug:**
When you click on Input and then Enter you get the error in Console:

`Uncaught TypeError: Cannot read property 'location' of undefined
    at Vue$3.setPlace (basic-autocomplete.html:60)`

**Demo Link**
https://xkjyeah.github.io/vue-google-maps/basic-autocomplete.html

**Steps to reproduce the behavior:**

1. Click on Demo Link or use AutoComplete.
2. Set Focus on Input
3. Press Enter
4. See Console Log.

**Expected behavior**
Nothing or chose the first from list.

**Comment by xkjyeah** [comment]
Hi thanks for reporting this bug.

This is a bug in the demo. If you set `:select-first-on-enter="true"` the first option will automatically be selected when you press "Enter".

I've updated the demo to reflect the use of this option.

**Comment by ghost** [comment]
what if there are no any options? it shows the error if there is no option
