### ISSUE TITLE
Help: Open Info Window

### ISSUE THREAD

**Issue by Marmiz** [xkjyeah/vue-google-maps#43]
Hello,

I'm fully aware that this question was already asked [here](https://github.com/xkjyeah/vue-google-maps/issues/9) and as you suggested the solution to toggle the Info Window visibility is by

>You have to listen for the marker_clicked event and then toggle
the marker's opened property.

But I'm having trouble by toggling the visibility only of the clicked marker.

So far I have my markers that looks like:

```html
<gmap-marker 
       v-for="m in pushMarkers"
       :position="{lat: m.lat, lng: m.lon}" 
       @click="showInfoWindow()" >

        <gmap-info-window :content="m.name" :opened="visInfoWindow"></gmap-info-window>
 </gmap-marker>
```

Then In my data:
```javascript
visInfoWindow: false,
```

And the `showInfoWindow` methods
```javascript
showInfoWindow(){
        this.visInfoWindow = this.visInfoWindow ? false :true;
}
```

Unfortunately by doing so all the InfoWindow will be toggled when one marker is clicked.
Is there a way to reference only the one clicked? 
For custom inputs I often listen for the `$events.target`; Is there an equivalent for the marker?

Thanks a lot for your help :)

**Comment by zashton** [comment]
maybe you could try this @Marmiz 

```
<gmap-marker 
       v-for="m in pushMarkers"
       :position="{lat: m.lat, lng: m.lon}" 
       @click="showInfoWindow(m)" >

        <gmap-info-window :content="m.name" :opened="m.customInfo"></gmap-info-window>
 </gmap-marker>

showInfoWindow(marker){
        marker.customInfo = marker.customInfo ? false :true;
}
```

**Comment by Marmiz** [comment]
Thanks for the reply @ashtonzheng,

I have managed to obtain the show on/off on marker click by doing a couple of twerks that may be useful in case someone else is looking for this kind of feature.

---

**1:** I've added the info window visibility (`ifw`) directly inside the marker array so that when looping in the gmap-marker component every instance will have that property.
Before I was just declaring a global value inside data.

---

**2:** Since I want every info window to open/close on click, but also to close any open one if a new marker is clicked (ie: only one Info Window open at a time) I could not use a ternary operation; instead I had to use a  for loop with an index on the `v-for` like so:
warning: there may be more elegant ways to do this :)

```html
<gmap-marker v-for="(m,i) in markers" :position="m.position" @click="showInfoWindow(i)">
                 <gmap-info-window :content="m.name" :opened="m.ifw"></gmap-info-window>
</gmap-marker>
```

```javascript
showInfoWindow(m){
     for(var i=0; i<this.markers.length; i++) {
            if ( i == m ) {
              this.markers[i].ifw = this.markers[i].ifw ? false : true;
            }
            else {
                this.markers[i].ifw = false;
            }
   },
```


Lastly, everything started working properly when I stoped using a generic array to store the values, and use one named markers.
I've tried doing the exact same procedure with a "random" array, but only with one named `markers:[]` everything worked as expected.

Perhaps that's a required name for Google to work with? Or just mere coincidence and I messed up something somewhere else 👍

**Comment by zashton** [comment]
@Marmiz if you want only 1 infoWindow to be shown you could have declared the infowindow outside of the markers and change the position of the infowindow when clicking on the markers.

```
<gmap-info-window :position="infoWindowPos" :opened="infoWinOpen" :content="infoContent" >

 </gmap-info-window>

<gmap-marker
                        v-for="m in markers"
                        :position="m.position"
                        :icon="icon"
                        @click="showInfoWindow(m)">
</gmap-marker>
```

```
 infoWinOpen:false,
 infoContent:'',
 infoWindowPos: {lat:0,lng:0},
```

```
showInfoWindow: function (marker){

                    this.infoWindowPos = {lat:marker.position.lat, lng:marker.position.lng} ;
                    this.infoContent = marker.customInfo;
                    this.infoWinOpen = true;

},
```

**Comment by Marmiz** [comment]
That's also a valid solution @ashtonzheng; the only drawback is that the position will be the same as the marker one making the info window pop up have an ugly positioning.
&nbsp;
<img width="132" alt="iw-marker" src="https://cloud.githubusercontent.com/assets/16669241/22914241/07f8f582-f2a2-11e6-8b7a-6b77875b56f9.png">
&nbsp;
On the other hand rendering the `info-window` component inside `marker` won't; perhaps in this case the info window is anchored to marker.
comparison image:
<img width="103" alt="iw-marker-anchor" src="https://cloud.githubusercontent.com/assets/16669241/22914714/a51c14e6-f2a4-11e6-90ec-0e46455115ea.png">

**Comment by xkjyeah** [comment]
The offset of the info window relative to the marker is a configuration
option. See Google maps reference Api

**Comment by zashton** [comment]
@Marmiz @xkjyeah 

maybe you could try this, not sure whether theres a better way to do this

```
<gmap-info-window :options="infoOptions" :position="infoWindowPos" :opened="infoWinOpen" :content="infoContent" >

</gmap-info-window>
```

```
 infoWinOpen:false,
 infoContent:'',
 infoWindowPos: {lat:0,lng:0},
 infoOptions:{}
```

```
showInfoWindow: function (marker){

                    this.infoWindowPos = {lat:marker.position.lat, lng:marker.position.lng} ;
                    this.infoContent = marker.customInfo;
                    this.infoWinOpen = true;

                   // offset the infoWindow upwards
                    var offSet = new google.maps.Size(0,-45);
                    this.infoOptions = { pixelOffset: offSet};

},

```

**Comment by Marmiz** [comment]
Thanks for your reply @ashtonzheng  and @xkjyeah.

I can simply declare the `pixelOffset` property as follow:
```html
<gmap-info-window :content="iwContent" :opened="iwOpen"
    :position="iwPosition" :options="iwOptions" @closeclick="updateiwOpen()">
</gmap-info-window>
```

```javascript
iwOptions: {
    pixelOffset: {width: 0, height: -35}
     },
```
Without the need of calling a new Google methods.
&nbsp;
Thanks to your suggestions I finally have only one `GmapInfoWindow` component that renders dynamically based on the marker clicked, while before I had rendered an `info window` component for each marker.

Since my map sometimes can render thousands of markers at a time I feel this should relief some weight and hopefully speed up my App.


I feel this can be added as an example in the library page, so maybe can help some other who will have the same necessities that I had.

**Comment by zashton** [comment]
@Marmiz @xkjyeah

edit: Ok found the issue
`@closeclick="iwOpen=false"`
gotta update this otherwise the infoWindow doesn't show even when you set it to iwOpen=true

**Comment by Marmiz** [comment]
@ashtonzheng @xkjyeah that's why my  function  is a bit more complex.

I basically pass an ID data to the `info window` and each marker will have its own ID.
Every time a marker is clicked it updates the info window id.

This means that if the marker ID and the InfoWindow ID are the same I have clicked again on the same marker --> close it.

Otherwise I've clicked on a different one so I close the previous InfoWindow and open the "new" one above the clicked marker.

```html
<gmap-marker v-for="(m,i) in markers" :position="m.position" @click="showInfoWindow(m, m.id)" :icon="customMarker(m.type)">
</gmap-marker>
```

```javascript
showInfoWindow(marker, id) {
            this.iwPosition = {lat: marker.position.lat, lng: marker.position.lng};
            this.iwContent = marker.content;
            // same -> toggle between visibility
            if ( this.iwID == id) {
              this.iwOpen = this.iwOpen ? false : true;
              this.iwID = marker.id;
            // not same -> open the new one
            }else{
              this.iwOpen = true;
              this.iwID = marker.id;
            }
        },
```

And then of course I listen for the `closeclick` event fired by the Info Window when the `x` is clicked to update the visibility, so that the previous function will behave as expected:

```html
<gmap-info-window :content="iwContent"  :id="iwID" :opened="iwOpen"
       :position="iwPosition" :options="iwOptions" @closeclick="updateiwOpen()">
</gmap-info-window>
```
```javascript
// close info window when default 'x' is clicked
        updateiwOpen() {
          this.iwOpen = false;
        },
```

I do this "complex" methods because I want to clearly set the InfoWindow visibility by clicking on the markers, but also I have other components outside the map that on specific action will toggle the visibility as well, so I want the `iwOpen` to always follow the same "pattern"

**Comment by zashton** [comment]
@Marmiz 

Nice and comprehensive , mimics how it will behave like as if the infowindow is in the marker itself and without the need of creating each infowindow for each marker. 👍

**Comment by awitherow** [comment]
@Marmiz @ashtonzheng @xkjyeah could we close up this issue with a good documented example of this specific type of question (since it was asked twice already)?

**Comment by Marmiz** [comment]
@awitherow I'll be happy to help writing a guide, document or example on how to create functional markers like the one I have commented above.

I feel this is such a common feature that many coders looking in this library would benefit from.

**Comment by zashton** [comment]
@Marmiz @xkjyeah @awitherow 

Sure , I would love to help contribute. Let me know how I can help with the Wiki page.

**Comment by awitherow** [comment]
awesome! @Marmiz @ashtonzheng go ahead and either one of you can open up a PR, reference it here and then hopefully @xkjyeah can give it a good reviewing 🎉
