### ISSUE TITLE
Browserify doesn't seem to be supported

### ISSUE THREAD

**Issue by paltman** [xkjyeah/vue-google-maps#434]
I have a browserify setup instead of webpack and it works with other third party vue libraries (e.g. BootstrapVue, I believe because the file referenced there is pre-built).  When I import vue2-google-maps, I get errors that look like the Vue isn't being processed. Are there any plans to support browserify?

**Comment by paltman** [comment]
I try to: 

```js
import * as VueGoogleMaps from 'vue2-google-maps/dist/vue-google-maps.js';
```

However, it complains that `MarkerClusterer` isn't available.

**Comment by xkjyeah** [comment]
Sorry, I'm not familiar with browserify. You also need to import one of the
marker-clusterer / marker-clusterer-plus modules.

**Comment by paltman** [comment]
I don't need to import the marker-cluster if i include http://xkjyeah.github.io/vue-google-maps/vue-google-maps.js.  Is that built differently?

**Comment by sirdiego** [comment]
Hey @xkjyeah,

we had a similar problem using vue2-google-maps. It's fixed if you reintroduce the _browserify_ configuration part in the _package.json_ again. It was there before you removed it here:
* https://github.com/xkjyeah/vue-google-maps/commit/491168e675f3893ca038de89f6ef04e0fe00e558#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L79

Can we reintroduce this config? We added it to a fork an used that one and it works.

Should I create a PR?

Thanks!

**Comment by xkjyeah** [comment]
Sure, please create a PR. I wasn't too sure how browserify was being used
and so it got eliminated as part of a cleanup. Sorry about that.

**Comment by xkjyeah** [comment]
Hi I've published a new version. LMK if it doesn't work for you.

**Comment by sirdiego** [comment]
Hi @xkjyeah,

works perfect. Thank you very much!

Here is my test case, first with 0.10.4 and then with 0.10.5. I was thinking about how this could be automated into the CI pipeline, to assure that browserify works in the future :thinking: 

> ➜  ~/T/vue2-gulp-example git:(master) **npm i vue2-google-maps@0.10.4**
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN vue2-gulp-vueify-browserify@1.0.0 No repository field.
> 
> + vue2-google-maps@0.10.4
> added 4 packages from 3 contributors and audited 4 packages in 1.089s
> found 0 vulnerabilities
> 
> ➜  ~/T/vue2-gulp-example git:(master) **npm start**
> 
> > vue2-gulp-vueify-browserify@1.0.0 start vue2-gulp-example
> > gulp && http-server ./public/
> 
> [11:20:05] Using gulpfile gulpfile.js
> [11:20:05] Starting 'default'...
> [11:20:05] Finished 'default' after 7.53 ms
> 
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> Error: Parsing file vue2-gulp-example/node_modules/vue2-google-maps/dist/components/infoWindow.vue: Line 5: Unexpected token !
>     at Deps.parseDeps (vue2-gulp-example/node_modules/module-deps/index.js:339:28)
>     at vue2-gulp-example/node_modules/module-deps/index.js:282:29
>     at ConcatStream.<anonymous> (vue2-gulp-example/node_modules/concat-stream/index.js:36:43)
>     at emitNone (events.js:111:20)
>     at ConcatStream.emit (events.js:208:7)
>     at finishMaybe (vue2-gulp-example/node_modules/readable-stream/lib/_stream_writable.js:460:14)
>     at endWritable (vue2-gulp-example/node_modules/readable-stream/lib/_stream_writable.js:469:3)
>     at ConcatStream.Writable.end (vue2-gulp-example/node_modules/readable-stream/lib/_stream_writable.js:436:5)
>     at DuplexWrapper.onend (vue2-gulp-example/node_modules/readable-stream/lib/_stream_readable.js:537:10)
>     at Object.onceWrapper (events.js:313:30)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vue2-gulp-vueify-browserify@1.0.0 start: `gulp && http-server ./public/`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue2-gulp-vueify-browserify@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     .npm/_logs/2018-11-30T10_20_06_820Z-debug.log
>
> ➜  ~/T/vue2-gulp-example git:(master) **npm i vue2-google-maps@0.10.5**
> npm WARN vue2-gulp-vueify-browserify@1.0.0 No repository field.
> 
> + vue2-google-maps@0.10.5
> updated 1 package and audited 4171 packages in 4.411s
> found 11 vulnerabilities (4 low, 1 moderate, 5 high, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details
> 
> ➜  ~/T/vue2-gulp-example git:(master) **npm start**                    
> 
> > vue2-gulp-vueify-browserify@1.0.0 start vue2-gulp-example
> > gulp && http-server ./public/
> 
> [11:20:27] Using gulpfile gulpfile.js
> [11:20:27] Starting 'default'...
> [11:20:27] Finished 'default' after 7.39 ms
> Starting up http-server, serving ./public/
> Available on:
>   http://127.0.0.1:8080
> Hit CTRL-C to stop the server
>
