### ISSUE TITLE
Unable to do panBy() method

### ISSUE THREAD

**Issue by smhutch** [xkjyeah/vue-google-maps#45]
Hi, sorry if I am overseeing something here. I have been trying to move my map using the panBy method, but cannot get it to work. 

I have followed the advice on the vue-google-maps wiki "You can do it either by calling them on the map vue instance or sending an event g-methodName", but am unsure how to do this. Any advice would be appreciated.

**Comment by xkjyeah** [comment]
The wiki is for another package. Follow the API.md or one of the examples
at HTTPS://xkjyeah.github.io/vue-google-mapd

**Comment by awitherow** [comment]
@smhutch did you get this working or is the issue still open?

**Comment by smhutch** [comment]
@xkjyeah @awitherow thank you I managed to get this working after seeing API. I did find this API documentation a little hard to find within the readme though.

**Comment by awitherow** [comment]
@smhutch could you open up a PR and clarify it within the API?

**Comment by smhutch** [comment]
@awitherow I have opened a PR for this difficulty now, I hope this is useful. https://github.com/xkjyeah/vue-google-maps/pull/55
