### ISSUE TITLE
'loaded' promisse does not exist in v0.10.x

### ISSUE THREAD

**Issue by JoseGoncalves** [xkjyeah/vue-google-maps#450]
The loaded promisse was removed from the code on 0.10.x.
Is this on purpose or was a mistake?
The solution shown in FAQ [Where is my google?](https://github.com/xkjyeah/vue-google-maps/wiki/vue-google-maps-FAQ#where-is-my-google) does not work anymore, because loaded resolves to `undefined`.

**Comment by JoseGoncalves** [comment]
I've found what needs to be changed when migrating from 0.9.x to 0.10.x.

Instead of:
```javascript
import {loaded} from 'vue2-google-maps'

loaded.then(() => { var bounds = new google.maps.LatLngBounds() /* etc */ })
```
you shoud now define a ref to your map:
```html
<gmap-map ref="gmap"></gmap-map>
```
and use `$gmapApiPromiseLazy()` on it: 
```javascript
this.$refs.gmap.$gmapApiPromiseLazy().then(() => { var bounds = new google.maps.LatLngBounds() /* etc */ })
```

It would be better to update the documentation to indicate this change.

**Comment by JoseGoncalves** [comment]
I've updated the wiki taken in consideration the comments made on #475

**Comment by xkjyeah** [comment]
Thanks Jose!
