### ISSUE TITLE
Google Maps Direction Service not showing result

### ISSUE THREAD

**Issue by irhamhqm** [xkjyeah/vue-google-maps#46]
Hi,
so I've been trying to use google maps direction service with this package, but it doesn't show the result(route) even though it gives the response status 'OK', and it doesn't throw any error.

Here is what I've tried so far: https://jsfiddle.net/irhamkim/20pegws2/

**Comment by xkjyeah** [comment]
You need to reference the $mapObject on the map component.

Hence,

1) <gmap-map ref="XYZ" ...></gmap-map>
2) something.setMap(this.$refs.XYZ.$mapObject)

**Comment by irhamhqm** [comment]
It's working now. Thank you for your quick response @xkjyeah
