### ISSUE TITLE
An issue with first autocomplete with clusters

### ISSUE THREAD

**Issue by Krystus** [xkjyeah/vue-google-maps#460]
I have input with autocomplete, map and markers with a cluster.

![screen shot 2018-08-06 at 15 34 20](https://user-images.githubusercontent.com/15039636/43719522-3c6c86b4-998e-11e8-834f-8d98dbf92c5b.png)

After map init I see clusters, and upon place update... after autocomplete (map center change to that place and zoom) I don't see any markers.

![screen shot 2018-08-06 at 15 35 07](https://user-images.githubusercontent.com/15039636/43719558-5321f452-998e-11e8-996c-daac8b7da5c6.png)

When I click + or - markers appear again.

![screen shot 2018-08-06 at 15 35 23](https://user-images.githubusercontent.com/15039636/43719573-596d0c48-998e-11e8-8109-0d5d0bbe0e16.png)

Also, I've disabled clusters. Then markers appear properly after that steps.

Clusters somehow make problem after first autocomplete. When I type another city... markers with clusters appear just normal.

**Comment by Krystus** [comment]
@xkjyeah can I count on you?

**Comment by xkjyeah** [comment]
Uh... This depends on the underlying Google Maps and MarkerClusterer libraries. I'm only providing a glue between them. Perhaps you can try writing the clustering /autocomplete in vanilla Google maps JS API and see if it works? Because if it does, then it's a glue problem. Otherwise it's an upstream problem

**Comment by Krystus** [comment]
@xkjyeah after several tests... I've noticed that problem occur only after zoom change from 5 to bigger then 9 after autocompleate. No idea why it's happening but zoom 9 is ok for me so problem is solved.
