### ISSUE TITLE
Retrieve gmapApi from main instance

### ISSUE THREAD

**Issue by KonstantinKudelko** [xkjyeah/vue-google-maps#462]
If it's possible to get access `gmapApi` if I'm don't use npm for install that package?

**Comment by fabianmossberg** [comment]
Did you manage to find a way?

**Comment by stevendesu** [comment]
I'm experiencing a similar issue. I included VueGoogleMaps as a script on the page:

```html
...
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.0/vue.js"></script>
	<script src="/vue-google-maps.js"></script>
...
```

I then tried to access the Google API object:

```js
console.log(window.VueGoogleMaps.gmapApi());
// Outputs: null
```
