### ISSUE TITLE
Polyline symbols 

### ISSUE THREAD

**Issue by aw-vm** [xkjyeah/vue-google-maps#464]
Hello, 
is it possible to add arrow or custom symbol to the polyline?
How can this be done?

I have tried this but wont work:

`<GmapPolyline
  v-if="selectedRoute!==null"
  ref="selectedPolyline"
          :options="{
            strokeColor: staticColor,
            strokeOpacity: 1.0,
            strokeWeight: 6,
            icons: [{
              icon: {path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW},
              offset: '100%',
              repeat: '20px'
            }]
           }"
          deepWatch
          :path="selectedRoute.path"/>`

**Comment by aw-vm** [comment]
I solved it like this:
`        <GmapPolyline
          v-if="selectedRoute!==null"
          ref="selectedPolyline"
          :options="{
            strokeColor: staticColor,
            strokeOpacity: 1.0,
            strokeWeight: 4,
            icons: [{
                icon: {path: lineSymbol,
                scale: 2,
                 fillColor: '#22bf15',
                },
                offset: '0',
                repeat: '100px'
            }]
           }"
          deepWatch
          :path="selectedRoute.path"/>`

**Comment by Gujionsen** [comment]
@valerymadiedo could you show how did you set the lineSymbol. 
I have the same problem, showing google's predefined shapes.

Thanks.

**Comment by aw-vm** [comment]
@elguja as I said in my response you have to put it on the options of the tag. In the `<GmapPolyline` tag place this code:

```
:options = {
    icons: [{
        icon: {
            path: yourPath,
            scale: 2,
            fillColor: '#22bf15'
        },
        offset: '0',
        repeat: '100px'
   }]
}
```

**Comment by jrk997** [comment]
@valerymadiedo can you show how you defined icon.path? Im also wondering in what element are icons wrapped

**Comment by cakesforfree** [comment]
> @elguja as I said in my response you have to put it on the options of the tag. In the `<GmapPolyline` tag place this code:
> 
> ```
> :options = {
>     icons: [{
>         icon: {
>             path: yourPath,
>             scale: 2,
>             fillColor: '#22bf15'
>         },
>         offset: '0',
>         repeat: '100px'
>    }]



> }"yourPath" to what? which one did you use? how did you set your path to "google.maps.SymbolPath.FORWARD_CLOSED_ARROW" ¿?

**Comment by msayubi76** [comment]
> Hello,
> is it possible to add arrow or custom symbol to the polyline?
> How can this be done?
> 
> I have tried this but wont work:
> 
> `<GmapPolyline v-if="selectedRoute!==null" ref="selectedPolyline" :options="{ strokeColor: staticColor, strokeOpacity: 1.0, strokeWeight: 6, icons: [{ icon: {path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW}, offset: '100%', repeat: '20px' }] }" deepWatch :path="selectedRoute.path"/>`

I'm facing issye in drawing Polyline between two points. could you please help me??? I have start and destination points but when i try to draw Polyline a straight line appear

 `<gmap-polyline v-bind:path.sync="path" v-bind:options="{ strokeColor:'#008000'}">`
 `customer:{lat:33.516913, lng:73.106768},`
 `driver:{lat:33.518318, lng:73.106146},`
 `this.path = [this.customer, this.driver]`

**Comment by JockChiang** [comment]
How to custom icon with my PNG image?

**Comment by ycldz** [comment]
google.maps.SymbolPath.FORWARD_CLOSED_ARROW not working how did you define
