### ISSUE TITLE
Cannot get $mapObject

### ISSUE THREAD

**Issue by pwnz22** [xkjyeah/vue-google-maps#48]
```
this.$refs.gmap.mapCreated.then((gmapObject) => {
    console.log(gmapObject)
})
```
I want to get the $mapObject and running the above code in `mounted() { } ` but i wont work. Also i want to `getCenter()` or `getBounds()`
`this.$refs.gmap.$mapObject.getCenter()` - I have tried for 2 hourse, i cant get the center or even bounds in mehtods. Events like bounds_changed and center_changed working. But i need **mapObject** to get or set center. Pls help!

**Comment by xkjyeah** [comment]
Why don't you try console.log(this.$refs.gmap.$mapObject)?
Did you set <gmap-map ref="gmap-map">?

**Comment by xkjyeah** [comment]
Oh, do try this.$refs.gmap.$mapCreated

**Comment by pwnz22** [comment]
<gmap-map ref="gmap"> now i have this. I need to set it to gmap-map?)

**Comment by xkjyeah** [comment]
Oops sorry autocorrect problems.
I meant:

<gmap-map ref="gmap">

**Comment by pwnz22** [comment]
Now im getting something there in console.log. 
But can i getBounds() in this closure? 
I mean console.log(gmapObject.getBounds()) or console.log(gmapObject.getCenter()). I'm doing this but there an strange object. There is no values for lat and lng

**Comment by xkjyeah** [comment]
If you need to setCenter you should just have:

<Gmap-map :center="{...}">

You can call getBounds, but maybe it won't return a thing if Google Maps
has not fully initialized it. Your best bet is to wait for the
bounds_changed event to fire.:
@bounds_changed="doSomethingWith($event")"

$event will be set to the value of getBounds()

**Comment by pwnz22** [comment]
Thanks for the fast response)

I'm also using this event. 
And the last question is it good practice to watch the bounds 
when i'm listenin to the event @bounds_changed="bounds = $event"
and then run method there like: 
```
watch: {
            'bounds': function (bounds) {
                this.boundsChanged(bounds)
            }
        }
```

**Comment by xkjyeah** [comment]
Why would you do that???? Why not just @bounds_changed="boundsChanged"?

On 22 Feb 2017 19:40, "Valijon" <notifications@github.com> wrote:

Thanks for the fast response)

I'm also using this event.
And the last question is it good practice to watch the bounds
when i'm listenin to the event @bounds_changed="bounds = $event"
and then run method there like:

watch: {
            'bounds': function (bounds) {
                this.boundsChanged(bounds)
            }
        }

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/48#issuecomment-281646182>,
or mute the thread

**Comment by pwnz22** [comment]
Because i'm doing ajax request and need also use lodash.debounce to not make 100 requests at once when user dragging the map)

I deleted the watch and did something like this : `@bounds_changed="boundsChanged($event)"`

**Comment by xkjyeah** [comment]
methods: {
    boundsChanged: _.debounce(()=>{...}, ....)
}

**Comment by xkjyeah** [comment]
Oops my bad. You can't use arrow functions with debounce. Use a standard
function(){}

**Comment by pwnz22** [comment]
I also deed that. Thanks a lot :) 
I will close the issue.
