### ISSUE TITLE
feature request:  autocomplete session tokens

### ISSUE THREAD

**Issue by altordwm** [xkjyeah/vue-google-maps#491]
My apologies if this is already included.

Would it be possible for somebody to add Autocomplete session functionality to this project?
https://developers.google.com/places/web-service/usage-and-billing#about-autocomplete-sessions

**Comment by ShadowsBeneaths** [comment]
I would really love to know if this is supported or not. If it isn't, could we be able to have that included?

**Comment by xkjyeah** [comment]
If you are using the widget (as this API is) sessions are handled automatically

**Comment by xkjyeah** [comment]
https://developers.google.com/maps/documentation/javascript/places-autocomplete
