### ISSUE TITLE
<template> error with Nuxt 2.0.0 on run dev

### ISSUE THREAD

**Issue by Krystus** [xkjyeah/vue-google-maps#493]
✖ error /Users/krystus/test-app/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
  <template>
  ^
  
  SyntaxError: Unexpected token <
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:617:28)
  at Object.Module._extensions..js (module.js:664:10)
  at Module.load (module.js:566:32)
  at tryModuleLoad (module.js:506:12)
  at Function.Module._load (module.js:498:3)
  at Module.require (module.js:597:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/krystus/test-app/node_modules/vue2-google-maps/dist/main.js:42:19)
  at Module._compile (module.js:653:30)
  at Object.Module._extensions..js (module.js:664:10)
  at Module.load (module.js:566:32)
  at tryModuleLoad (module.js:506:12)
  at Function.Module._load (module.js:498:3)
  at Module.require (module.js:597:17)

![screen shot 2018-09-22 at 23 58 00](https://user-images.githubusercontent.com/15039636/45922099-5e03af00-bec3-11e8-802e-26f436e8b161.png)

**Comment by Krystus** [comment]
@xkjyeah any idea what's wrong?

**Comment by adekoyejoakinhanmi** [comment]
@Krystus You can get round that by defining the plugin like so in nuxt.config -
```
plugins: [
  { src: '~/plugins/vue2-google-maps', ssr: false}
]
```

**Comment by Krystus** [comment]
@adekoyejoakinhanmi thanks but it's that way already. I've dig deeper and map is working ok but problem occour when I import gmapApi in one of my components.

```
import { gmapApi } from 'vue2-google-maps'
(..)
computed: {
    google: gmapApi,
}
```

Later I use it like that for example in GmapMarker:

`:position="google && new google.maps.LatLng(marker.latitude, marker.longitude)"`

That is causes error with unexpected token.

**Comment by Krystus** [comment]
Fixed by deleting import { gmapApi } and changing :position to:

`:position="{ lat: parseFloat(marker.latitude), lng: parseFloat(marker.longitude) }"`

Works good after that.

**Comment by hadyanq** [comment]
Hey @Krystus, I am experiencing the exact problem and removing ```import { gmapApi }``` does the trick. But then it raised another problem: how would you access the ```google``` object that supposed to be defined in the computed?

**Comment by syed-haroon** [comment]
Do this guys and things will work.

in your `./plugins/google-maps.js`
```
import Vue from 'vue';
import * as VueGoogleMaps from 'vue2-google-maps';

Vue.use(VueGoogleMaps, {
  load: {
    key: 'YOUR-KEY',
    libraries: 'places',
  },
});
```

and in you `./nuxt.config.js`
```
module.exports = {
  plugins: [
    { src: '~plugins/google-maps.js' },
  ],

  // As per below url things should work but for me it did not work.
  // https://github.com/nuxt/nuxt.js/issues/3874#issuecomment-420289531
  build: {
    transpile: [ 'vue2-google-maps']
  }

  // But, this WORKED :)
  build: {
    transpile: [/^vue2-google-maps($|\/)/],
  },
};
```
