### ISSUE TITLE
Cannot get map center

### ISSUE THREAD

**Issue by jumangitjs** [xkjyeah/vue-google-maps#495]
Hello,
i am in dire need of the value of the center. earlier this day, i have used the emit value of the center_changed, but a few hours later, the return is now a function

![image](https://user-images.githubusercontent.com/28138385/46152250-36399000-c2a3-11e8-8ec7-99b0a9a87922.png)

i have tried using
![image](https://user-images.githubusercontent.com/28138385/46152024-b90e1b00-c2a2-11e8-8ab5-2add76fb2198.png)

yet the value is still null

![image](https://user-images.githubusercontent.com/28138385/46152274-43ef1580-c2a3-11e8-8841-630ed7702d9d.png)

**Comment by fhusquinet** [comment]
The getCenter() function returns two functions called lat and lng.

You can access the latitude and longitude using getCenter().lat() and getCenter.lng() respectively.

**Comment by ghost** [comment]
I guess this thread can be closed
