### ISSUE TITLE
Webpack Configuration with Nuxt 2: Unexpected token < 

### ISSUE THREAD

**Issue by hadyanq** [xkjyeah/vue-google-maps#498]
Hello, thank you very much for the amazing project.
I've been using vue2-google-maps for a while and it worked great.
Today I'm trying to upgrade my Nuxt to the 2.0 and I've been getting errors.

I suspect it has something to do with the webpack configuration, seeing how the new Nuxt release uses Webpack 4. So I tried editing this code in nuxt.config.js:
```javascript
config.externals.splice(0, 0, function (context, request, callback) {
  if (/^vue2-google-maps($|\/)/.test(request)) {
    callback(null, false)
  } else {
    callback()
  }
})
```
This returns the error that ```splice``` failed because ```config.externals``` is undefined.
So I changed that into:

```javascript
config.externals = [
   function(context, request, callback) {
     if (/^vue2-google-maps($|\/)/.test(request)) callback(null, false)
     else callback()
   }
]
```
The build success, even though honestly I am still not sure whether this part of the code works as intended or not. However, I run into another error when I access the page:
```
SyntaxError
Unexpected token <
```

And also from the Nuxt build console:
```
✖ error /home/hadyanq/Projects/foodgasm-v2/webview-vuetify/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
  <template>
  ^
  
  SyntaxError: Unexpected token <
  at new Script (vm.js:79:7)
  at createScript (vm.js:251:10)
  at Object.runInThisContext (vm.js:303:10)
  at Module._compile (internal/modules/cjs/loader.js:657:28)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (/home/hadyanq/Projects/foodgasm-v2/webview-vuetify/node_modules/vue2-google-maps/dist/main.js:38:19)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

This time I have no idea what went wrong and I really appreciate any help anyone can give.
So, has anyone ever attempted to use this plugin with Nuxt 2?
Thanks in advance.

**Comment by Georgian** [comment]
I've tried:

1. The instructions in the README file of this project
2. [Extending the build and including a rule](https://github.com/xkjyeah/vue-google-maps/issues/206#issuecomment-338689932)
3. [Preventing the gmap js file from being excluded](https://github.com/xkjyeah/vue-google-maps/issues/206#issuecomment-338997271)

Neither work. Getting the same "Unexpected token" error.

**Comment by aknguyen11906** [comment]
I have the same issue when building my Vuepress project which uses this component.
Note:  I'm using webpack 4 and It works well in develop mode

**Comment by sebolek** [comment]
Same issue when using with Nuxt 2.0.0~2.1.0 which comes with webpack 4

**Comment by Codefa** [comment]
#501

**Comment by FransTwisk** [comment]
Can't get this to work either, same results.

**Comment by supermarioim** [comment]
same result, any news on this? thanks

**Comment by Codefa** [comment]
for me it works fine just create a plugin called **vue2-google-maps.js** 
code for vue2-google-maps.js
```
import` Vue from 'vue'
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: process.env.gAPIKey,
    libraries: 'places'
  }
})
```

then add it to the **nuxt.confi.js**

`~/plugins/vue2-google-maps'`

if its not working add vendor file vendor: ['babel-polyfill']
and install babel-polyfill

here i my devDependencies list
```
"devDependencies": {
    "@babel/polyfill": "^7.0.0",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-config-standard": "^12.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.6",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.11.0"
  }
```

**Comment by supermarioim** [comment]
i have same setup, keep getting

`SyntaxError: Unexpected token <`

error

**Comment by Codefa** [comment]
> i have same setup, keep getting
> 
> `SyntaxError: Unexpected token <`
> 
> error
@supermarioim 
if you have the files in github i will try to fix it I can make a pull request

**Comment by supermarioim** [comment]
@Codefa not really, it's private project, can't share code because of NDA

**Comment by Codefa** [comment]
> @Codefa not really, it's private project, can't share code because of NDA

no problem @supermarioim try to fix it agian

**Comment by supermarioim** [comment]
@Codefa this can maybe help you, when I'm on some page other then one that has map on it everything works fine and when I navigate to page that has map on it, it also works fine, but when I try refreshing page that has map on it I get this error

**Comment by Codefa** [comment]
> @Codefa this can maybe help you, when I'm on some page other then one that has map on it everything works fine and when I navigate to page that has map on it, it also works fine, but when I try refreshing page that has map on it I get this error

@supermarioim put the map code in The no-ssr Component
check it [](url)https://nuxtjs.org/api/components-no-ssr/
```
<no-ssr>
map code
</no-ssr>

**Comment by supermarioim** [comment]
> > @Codefa this can maybe help you, when I'm on some page other then one that has map on it everything works fine and when I navigate to page that has map on it, it also works fine, but when I try refreshing page that has map on it I get this error
> 
> @supermarioim put the map code in The no-ssr Component
> check it https://nuxtjs.org/api/components-no-ssr/
> 
> ```
> <no-ssr>
> map code
> </no-ssr>
> ```

it didn't help. as I can see, after some more research, each time i make a change in code and webpack rebuilds all, first time I make refresh I get this error

**Comment by supermarioim** [comment]
ok, some more stuff, each other refresh throws next exception:

`NuxtServerError
render function or template not defined in component: anonymous`

**Comment by TheAlexLichter** [comment]
Just created a working example: https://codesandbox.io/s/31j9l75xjm

(Working = it displays the map but no API key included :D)

**Comment by supermarioim** [comment]
`build: {
    transpile: [/^vue2-google-maps($|\/)/],
}`

this helped, thanks!

**Comment by TheAlexLichter** [comment]
@supermarioim You are welcome! That's the new best practice(which does similar things like the `config.externals` workaround in `extends` for Nuxt 1)

**Comment by hadyanq** [comment]
Hi everyone, thank you for all of your responses. The `transpile` key also does the trick for me, however there's still problem with it that I haven't been able to figure out.

In my project I also need to expose `gmapApi` in my computed property:
```javascript
import { gmapApi } from "vue2-google-maps"

export default {
  computed: {
    google: gmapApi
  } 
}
```
This causes the error `gmapApi is undefined`, but everything works well without the `google` computed property. I tried the `no-ssr` and still no luck. Any other ideas?

**Comment by TheAlexLichter** [comment]
@hadyanq You can't assign it to `computed` that easily because it leverages `window`

https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/main.js#L122-L124

Try to assign it in beforeMount ☺️

**Comment by Codefa** [comment]
Reading this post will help everyone facing problems with Third party plugins
[](url)https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422

@hadyanq You'll have to use mounted() or a later hook for gmapApi

**Comment by TheAlexLichter** [comment]
@Codefa `beforeMount` or `mounted`, to be precise. But that's a nice article! Thanks for sharing ☺️

**Comment by hadyanq** [comment]
@manniL @Codefa Thank you very much for your help, putting it on ```mounted``` solves my problem.
