### ISSUE TITLE
Not working with Nuxt2

### ISSUE THREAD

**Issue by valeriosillari** [xkjyeah/vue-google-maps#501]
Hi, I am using this plugin with Nuxt and it's great!

But lately Nuxt is updated to version 2, with a lot of new changes.

So I try to update Nuxt2 and the map does not work anymore.

I am using Nuxt2 v2.1.0 and I got this error:

`
ERROR  Failed to compile with 5 errors

These dependencies were not found:

* core-js/modules/es6.regexp.to-string in ./.nuxt/client.js, ./.nuxt/utils.js
* core-js/modules/es7.promise.finally in ./.nuxt/client.js
* core-js/modules/es7.symbol.async-iterator in ./.nuxt/client.js, ./.nuxt/middleware.js

Could be that the plugin for maps have some issue with the new Nuxt2?
`

Please let me know if anybody got the same issue.

Best

Valerio

**Comment by xkjyeah** [comment]
Thanks for reporting this issue. at work I'm not currently working on
front end development. Therefore I have limited time to maintain this
Library. If you have the capacity to investigate this issue and fix the bug
and I'll be happy to accept your pull request

**Comment by valeriosillari** [comment]
Ok I am not sure if I will also get time and even if I could achieve but I will try.
@all : if anybody want to join you are more than welcome :)

**Comment by hashinteractive** [comment]
@valeriosillari I'm having this issue too. After investigating:

@xkjyeah I think we need to replace the `babel-core: v6.26.0` with `@babel/polyfill` as it should pollyfill for the es6.regexp.to-string

Might be related to this PR: https://github.com/xkjyeah/vue-google-maps/pull/468

**Comment by Codefa** [comment]
for me it works fine just create a plugin called **vue2-google-maps.js** 
code for vue2-google-maps.js
```
import Vue from 'vue'
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: process.env.gAPIKey,
    libraries: 'places'
  }
})
```

then add it to the **nuxt.confi.js**

`~/plugins/vue2-google-maps'`

if its not working add vendor file vendor: ['babel-polyfill']
and install babel-polyfill

here i my devDependencies list
```
"devDependencies": {
    "@babel/polyfill": "^7.0.0",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-config-standard": "^12.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.6",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.11.0"
  }
```

**Comment by Codefa** [comment]
#498

**Comment by valeriosillari** [comment]
I found a solution, thanks to another PR by https://github.com/Richard1984/vue-google-maps

Here my PR to him, with all code working.
https://github.com/Richard1984/vue-google-maps/pull/2

Keypoints:
- update babel packages (Richard1984 code)
- update Readme File with instructions for adding correct code on Nuxt2 (based on another solution in issue #498)

I set a test repo with working code as test. You just need to set your API key
https://github.com/valeriosillari/nuxt2-map

Suggestions: we can try to merge the code from Richard1984 into the repo, plus the changes in Readme File added by me :)

**Comment by vkatsar** [comment]
Just install @babel/polyfill with yarn or npm.

`yarn add @babel/polyfill --dev`
