### ISSUE TITLE
get coordinates from address

### ISSUE THREAD

**Issue by MR-Shegby** [xkjyeah/vue-google-maps#509]
How to get coordinates to set a marker if I got addresses like "louvre, paris, france" ?  Is there a special method?

**Comment by micardona96** [comment]
Hello,
Have you used the <gmap-autocomplete> component?
with an @place_changed props, this event returns an object with the location data,
I'm sorry my English is not very good I hope it helps you

**Comment by mydnic** [comment]
Did you find a way to do this ?

**Comment by marncz** [comment]
@MRShegby 

```
<gmap-autocomplete
    @place_changed="getPlace"
</gmap-autocomplete>
```

Then this function:

```
methods: {

...
getPlace(place) {
  console.log(place);
}
...

}
```

**Comment by MR-Shegby** [comment]
Thanks to all. For now I'm a bit out of this. But I think I'll return soon to google maps and check solutions. Thanks again
