### ISSUE TITLE
"Cannot read property 'maps' of null" on cluster click event

### ISSUE THREAD

**Issue by devWaleed** [xkjyeah/vue-google-maps#513]
I have bind a simple cluster click event:

        <GmapCluster
                :maxZoom="10"
                :gridSize="50"
                :minimumClusterSize="3"
                :zoomOnClick="true"
                @click="cluster_click"
        >

and this is giving me error on page load:

> Cannot read property 'maps' of null
>     at eval (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules\\.cache\\vue-loader","cacheIdentifier":"331490a4-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/MapComponent.vue?vue&type=template&id=5567ea9e&scoped=true& (app.js:1296), <anonymous>:42:44)
>     at Proxy.renderList (vue.runtime.esm.js?2b0e:3701)
>     at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules\\.cache\\vue-loader","cacheIdentifier":"331490a4-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/MapComponent.vue?vue&type=template&id=5567ea9e&scoped=true& (app.js:1296), <anonymous>:32:13)
>     at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:4540)
>     at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:2784)
>     at Watcher.get (vue.runtime.esm.js?2b0e:3138)
>     at Watcher.run (vue.runtime.esm.js?2b0e:3215)
>     at flushSchedulerQueue (vue.runtime.esm.js?2b0e:2977)
>     at Array.eval (vue.runtime.esm.js?2b0e:1833)
>     at flushCallbacks (vue.runtime.esm.js?2b0e:1754)

**Comment by devWaleed** [comment]
After page app is loaded completed. Cluster click event doesn't not generate any more errors and everything runs fine.

**Comment by amstrad** [comment]
Please, anyone can help with this? having this issue and can´t find a way out...

This also didn´t help, and doesn´t make it any clear:
https://github.com/xkjyeah/vue-google-maps/issues/72 

Edit:
Ok, fixed it using "**$event**" in the method param

```
             <gmap-cluster
                            :key=""
                            :gridSize="50"
                            :options="{ ignoreHidden: false }"
                            @click="zoomCluster($event)"
                            :zoomOnClick="true"
                    >
                        <GmapMarker v-for="(marker, index) in markers"
                                    :key="index"
                                    :animation="3"
                                    :icon="{url : '/assets/admin/images/mapmarker.png'}"
                                    :title=String(index)
                                    :clickable="true"
                                    :position="{lat: parseFloat(marker.latitude), lng: parseFloat(marker.longitude) }"
                                    @click="showSingleCup(marker)"
                        />
                    </gmap-cluster>
```

Now i can do getMarkers in my zoomCluster function

**Comment by cingh-jasdeep** [comment]
this helped!!
Thanks waheguru
