### ISSUE TITLE
Marker Cluster - ignore hidden

### ISSUE THREAD

**Issue by Yearhouse** [xkjyeah/vue-google-maps#523]
How can I use the marker cluster IgnoreHidden setting as 
described here https://github.com/googlemaps/v3-utility-library/blob/master/markerclustererplus/src/markerclusterer.js

**Comment by Yearhouse** [comment]
Figured it out.
You can use  this.$refs.cluster.$clusterObject.setIgnoreHidden( true );

**Comment by xkjyeah** [comment]
You should be able to do this with the previous API by passing in:
```html
<gmap-cluster
:options="{ ignoreHidden: true }"
>
```

Nevertheless, I'll be adding the `ignoreHidden` option to the `Cluster` class so that you can write:
```html
<gmap-cluster :ignoreHidden="true">
```
