### ISSUE TITLE
Trying to change control size

### ISSUE THREAD

**Issue by TheWrongAlice** [xkjyeah/vue-google-maps#524]
I want to make the controls smaller, as described here: https://developers.google.com/maps/documentation/javascript/examples/control-replacement

How can I do it with this plugin? The css class names used in Google's examples don't seem to apply here.

**Comment by dalexander-trc** [comment]
Google added the controlSize option after deciding to increase the default icon size to better support touch devices.

https://developers.google.com/maps/documentation/javascript/releases#336

**Comment by TheWrongAlice** [comment]
Thanks! :)
