### ISSUE TITLE
Marker mouseover event gives undefined values

### ISSUE THREAD

**Issue by gileneusz** [xkjyeah/vue-google-maps#526]
I'm trying to access event from
`<GmapMarker v-for=":key="index" (m, index) in markers" @mouseover="show"/>`
so inside function I have just:
`show(e) { console.log(e) }`
and this is working, giving properly values at first try, but when I update markers, change position and zoom out, zoom in map, it's giving me undefined values of every `e` properties

What is the reason of such behaviour? How to fix it?

This is such a pity that this project is not no longer growing :disappointed:

**Comment by gileneusz** [comment]
I managed to fix this by 
`show(e) { console.log(event) }`
not sure why 
`show(e) { console.log(e) }`
does not work...

**Comment by xkjyeah** [comment]
Are you able to reproduce this on a JSFiddle? This might be a Google Maps
JS API bug, since this library simply hands over the mouse event to the
event handler
