### ISSUE TITLE
Unknown plugin "transform-inline-environment-variables" (trying to install autocomplete manually)

### ISSUE THREAD

**Issue by pmochine** [xkjyeah/vue-google-maps#529]
Hi :)

because of google prices, I transitioned over to osm with leaflet. However, I would still love to use autocomplete.

Unfortunately, I'm not able to install it manually. It does not matter how I'm doing it, I'm alway getting the error:

`Module build failed: ReferenceError: Unknown plugin "transform-inline-environment-variables" specified in "my_path/node_modules/vue2-google-maps/src/.babelrc" at 1`

I'm not sure. Shouldn't the plugin come automatically?

I'm loading autocomplete like:

```
Vue.use(VueGoogleMaps, {
  load: {
    key: 'my-key',
    libraries: 'places', 
  },
  installComponents: false,
})
```

And in my local vue component:

`import {GmapAutocomplete} from 'vue2-google-maps/src/components/autocomplete'
`
But somehow it just fails.

What am I doing wrong?

Thank you!

**Comment by xkjyeah** [comment]
Try importing from `dist` instead of from `src`.

The difference is that `dist` is transpiled, and does not specify a .babelrc, whereas `src` does.
