### ISSUE TITLE
InfoWindow Arrow/Triangle misaligned?

### ISSUE THREAD

**Issue by joedawson** [xkjyeah/vue-google-maps#530]
Hello,

I recently setup InfoWindow for my markers and the arrow/triangle at the bottom of the window is misaligned with the window itself?

![infowindow-arrow](https://user-images.githubusercontent.com/1009696/48898521-e14e6c00-ee44-11e8-88da-87f1ea6d5e7c.jpg)

Here's my usage:

```vue
<google-map-info
  :options="infoOptions"
  :opened="infoOpen"
  :position="infoPos"
  @closeclick="infoOpen=false">
  <!-- my content -->
</google-map-info>
```

My `infoOptions` are:

```js
infoOptions: {
  pixelOffset: {
    width: 0,
    height: -60
  }
},
```

Any ideas why this might be happening? There isn't an identifier for me to grab the triangle and move it myself via CSS.

Thanks in advance.

**Comment by xkjyeah** [comment]
This seems to be a Maps JS API issue. Is the issue still there when you revert to an older API version?

**Comment by joedawson** [comment]
Hey @xkjyeah,

I'll give that a try in a moment and get back to you :)

**Comment by tuhin-cn** [comment]
@JoeDawson Are you using any CSS framework? I was having the same problem while using tailwindcss in my app. I have solved the problem by wrapping the gmap component in a div with class say my-map and adding the following CSS:
`.my-map * {
  border-style: none;
}`

**Comment by joedawson** [comment]
That’s exactly the framework I’m using! I’ll try this today. Didn’t get a chance yesterday :)

Will let you know in a few hours, thanks!

**Comment by joedawson** [comment]
@tuhin-cn thanks! that worked perfectly.

![fixed](https://user-images.githubusercontent.com/1009696/49139173-02053e80-f2e9-11e8-8383-a6f0cfaaa772.jpg)
