### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by GabMic** [xkjyeah/vue-google-maps#537]
I am trying to integrate this with Nuxt.js, and i get **Unexpected token <** issue for some reason.

I have done it like so:

1. Register the plugin in **plugins/vue2-google-maps.js**
```
import Vue from 'vue'
import * as VueGoogleMaps from 'vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: 'My-Key',
    libraries: 'places',
  },
})
```
2. In my pages directory i made a **map** page, and in it, like so:
```
   <no-ssr>
      <div>
          <GmapMap
          :center="{lat:10, lng:10}"
          :zoom="7"
          map-type-id="terrain"
          style="width: 500px; height: 300px"
          >
      <GmapMarker
          :key="index"
          v-for="(m, index) in markers"
          :position="m.position"
          :clickable="true"
          :draggable="true"
          @click="center=m.position"
        />
    </GmapMap>
      </div>
  </no-ssr>
```
3. In my nuxt config file, in the plugins array, i added it:
```
  plugins: [
    '~/plugins/vue2-google-maps',
  ],
```
After all that, i run _npm run dev_ and get the above issue of **Unexpected token <**
What am i missing/doing wrong?
Thanks for the help.

**Comment by shmarts** [comment]
Did you solve this? if so how?

**Comment by jayrchamp** [comment]
I have also run into this issue after updating Nuxt from 1.4.0  to  2.0+

Everything was working fine w/ Nuxt 1.4.0

I didn't investigated yet

**Comment by jayrchamp** [comment]
@shmarts If you are using Nuxt 2.0, you need to change the nuxt config file and add the `build.transpile` property like so:

nuxt.config.js
```js
module.exports = {
    // ...
    build: {
        // ...
        transpile: [/^vue2-google-maps($|\/)/],
        // ...
    }
    // ...
}
```
You will find more info about that fix here #522 
And this is nuxt's documentation about the `transpile` option: https://nuxtjs.org/api/configuration-build/#transpile

**Comment by dfsq** [comment]
And what needs to be configured if one doesn't use Nuxt? How to configure webpack in this case?

**Comment by jayrchamp** [comment]
@dfsq The transpile option in nuxt config file is in fact only an `Array<string | RegExp>` that will be passed to Babel to transpile specific dependencies. Set up Babel in your webpack config and see if it helps. 

Maybe you should open a new thread with more information about your issue. Cheers

**Comment by mikaelkarlsson-se** [comment]
@dfsq I had a similar problem when using my own Webpack build environment with Webpack 4 and Vue-loader 15. After a lot of research and cursing I [found some info in the Vue-loader docs](https://vue-loader.vuejs.org/guide/pre-processors.html#excluding-node-modules) and manged to get it working by including .vue files living in the node_modules folder in the Babel transpilation.
I also had to add vue-style-loader as I didn't handle any CSS related stuff with Webpack.

My webpack rules now looks like this:

        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            {
                test: /\.js$/,
                exclude: file => (
                    /node_modules/.test(file) &&
                    !/\.vue\.js/.test(file)
                ),
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.css$/,
                use: [
                    'vue-style-loader',
                    {
                        loader: 'css-loader',
                        options: { importLoaders: 1 }
                    }
                ]
            }
        ]

A couple of Babel packages used by the maps package was needed to be installed as well:
```
npm install babel-plugin-minify-dead-code-elimination --save-dev
npm install babel-plugin-transform-inline-environment-variables --save-dev
```

There might be other and better ways of getting it working but hope it helps! :)
