### ISSUE TITLE
Get autocomplete location name from a specific country or area

### ISSUE THREAD

**Issue by akr4m** [xkjyeah/vue-google-maps#538]
I used bounds. But can you know me the exact country area locations only in autocomplete input box? And how can I found the bounds of a specific area in a country?

Thanking You

**Comment by amstrad** [comment]
For getting the bounds i assign a ref to the map. Then i do this.$refs.YOURREF.$mapObject.getBounds() in your method, like this.


```
<gmap-map style="width: 100%; min-height: 650px;"
                          ref="YOUR_REF"
                          :draggable="true"
                          @bounds_changed="boundsChanged($event)"
                          :options="{
                            scrollwheel: true,
                         }"
                >
```


      boundsChanged() {

                this.page = 1;

                this.bounds = this.$refs.YOUR_REF.$mapObject.getBounds();

                this.changingZoom = this.$refs.YOUR_REF.$mapObject.getZoom();

                var ne = this.bounds.getNorthEast(); // LatLng of the north-east corner
                var sw = this.bounds.getSouthWest(); // LatLng of the south-west corder

                var nw = (ne.lat(), sw.lng());
                var se = (sw.lat(), ne.lng());

                this.lat1 = sw.lat();
                this.lat2 = ne.lat();
                this.long1 = sw.lng();
                this.long2 = ne.lng();

            },

**Comment by akr4m** [comment]
> For getting the bounds i assign a ref to the map. Then i do this.$refs.YOURREF.$mapObject.getBounds() in your method, like this.
> 
> ```
> <gmap-map style="width: 100%; min-height: 650px;"
>                           ref="YOUR_REF"
>                           :draggable="true"
>                           @bounds_changed="boundsChanged($event)"
>                           :options="{
>                             scrollwheel: true,
>                          }"
>                 >
> ```
> ```
>   boundsChanged() {
> 
>             this.page = 1;
> 
>             this.bounds = this.$refs.YOUR_REF.$mapObject.getBounds();
> 
>             this.changingZoom = this.$refs.YOUR_REF.$mapObject.getZoom();
> 
>             var ne = this.bounds.getNorthEast(); // LatLng of the north-east corner
>             var sw = this.bounds.getSouthWest(); // LatLng of the south-west corder
> 
>             var nw = (ne.lat(), sw.lng());
>             var se = (sw.lat(), ne.lng());
> 
>             this.lat1 = sw.lat();
>             this.lat2 = ne.lat();
>             this.long1 = sw.lng();
>             this.long2 = ne.lng();
> 
>         },
> ```

But how can I restrict names excluding a specific country name or area name?

**Comment by amstrad** [comment]
> But how can I restrict names excluding a specific country name or area name?

My solution is just for getting the bounds from the current visible area.
for the autocomplete map, maybe take a look at something like this?

https://github.com/xkjyeah/vue-google-maps/issues/504
