### ISSUE TITLE
What is the proper way to display a popup instead of the window info?

### ISSUE THREAD

**Issue by GabMic** [xkjyeah/vue-google-maps#544]
Hi.
I was wondering how can i show a popup instead of the info window. I want to customize it.
Please, anyone who has done it correctly, need some help here.
Thanks.

**Comment by amstrad** [comment]
i do the following with vue-snotify, might be similar with your modal

>      <GmapMarker v-for="(marker, index) in markers"
>                                     :key="marker.id"
>                                     :animation="3"
>                                     :icon="{url : '/assets/admin/images/mapmarker.png'}"
>                                     :clickable="true"
>                                     :position="{lat: parseFloat(marker.latitude), lng: parseFloat(marker.longitude) }"
>                                     @click="toggleInfoWindow(marker)"
>                         />

then you can do something like this in your "methods" section: 

```

 toggleInfoWindow(marker) {
                //console.log(marker);

                this.$snotify.remove();

                let marker_info = '<a target="_blank" href="/admin/leads/single/' + marker.id + '"><b>' + marker.name + '</b></a><br>';
                marker_info += '<small>' + marker.raw_address + '</small><br>'; //or whatever property from your marker intem
             

                this.$snotify.html(
                    `<div class="snotifyToast__title"><b>marker.name</b></div>
                    <div class="snotifyToast__body">` + marker_info + `</div> `
                    ,
                    {
                        buttons: [
                            {
                                text: 'OK', action: (toast) => {
                                    this.$snotify.remove(toast.id);
                                },
                                bold: true
                            }
                        ],
                        timeout: 9999999,
                        position: 'rightCenter',
                        showProgressBar: false,
                        closeOnClick: false,
                        pauseOnHover: true,
                        id: 'notify_map' + marker.id
                    }
                );
            },

```
