### ISSUE TITLE
Is there a way to hide the [Map, Satelite] buttons especifically?

### ISSUE THREAD

**Issue by 0xLuz** [xkjyeah/vue-google-maps#549]
I went through the existing issues and the closest one I fount was https://github.com/xkjyeah/vue-google-maps/issues/333, however I would like to hide only the `[Map, Satelite]` buttons specifically. Is that possible by any way?

**Comment by MrKriegler** [comment]
@JoabMendes you can control it in the options prop specifically  `mapTypeControl: false` and   `streetViewControl: false`.

```
<GmapMap
      :options="{
        zoomControl: true,
        mapTypeControl: false,
        scaleControl: false,
        streetViewControl: false,
        rotateControl: false,
        fullscreenControl: true,
        disableDefaultUi: false,
      }"
    >
```

**Comment by 0xLuz** [comment]
Thanks, @MrKriegler !!
