### ISSUE TITLE
Proper way of making gmap-cluster to work?

### ISSUE THREAD

**Issue by GabMic** [xkjyeah/vue-google-maps#553]
Hi, all.
I want to show my markers in clusters.
I have wrapped the marker component with the `gmap-cluster` component, and imported it at the bottom  of the plugin(am using Nuxt.js).
`Vue.component('gmap-cluster', VueGoogleMaps.Cluster);`
But still getting `Unknown custom element: <gmap-cluster>`.

Please can anyone show me the correct steps to add marker cluster to my map? 
Thanks.

**Comment by GabMic** [comment]
The solution to this problem is the import method i used.
Import it like this:

`import GoogleMapCluster from 'vue2-google-maps/dist/components/cluster'`

And wrap the `GmapMarker` component with `google-map-cluster`.

**Comment by wowxoxo** [comment]
@GabMic i had same problem. Thank you for your solution

**Comment by GabMic** [comment]
Glad i could  help. :)

**Comment by ultrono** [comment]
Spot on, just saved my sanity.
