### ISSUE TITLE
How can i get the current zoom level of the map?

### ISSUE THREAD

**Issue by GabMic** [xkjyeah/vue-google-maps#555]
I know there is a function of `getZoom()`, but how can i get the google or map objects successfully in order to access it?

**Comment by Zafermushtaha97** [comment]
How can solve it , can you help me @GabMic ??

**Comment by GabMic** [comment]
I did not solve it

**Comment by seifrached** [comment]
@GabMic @Zafermushtaha97 

<gmap-map @zoom_changed="GetCurrentZoom"></gmap-map>

**Add this function in methods**

`methods{

GetCurrentZoom(zoom){
    console.log(zoom)
   // this.options.zoom = zoom
},

} `

**Comment by seifrached** [comment]
`<gmap-map @zoom_changed="GetCurrentZoom">`
**Add this function in methods**

`methods{
    GetCurrentZoom(zoom){
          console.log(zoom)
       // this.options.zoom = zoom
},

}`
