### ISSUE TITLE
Cannot read property '$mapPromise' of undefined

### ISSUE THREAD

**Issue by GabMic** [xkjyeah/vue-google-maps#556]
I am trying to get the current zoom level of the map.
```
           <GmapMap ref="googleMap">

              this.$refs.googleMap.$mapPromise.then((map) => {
              var zoom = map.getZoom();
              console.log(zoom);
```
and also like this: 
```
    this.$nextTick(() => {
              this.$refs.googleMap.$mapPromise.then((map) => {
              var zoom = map.getZoom();
              console.log(zoom);
    })
```

I have tried all kind of methods, but for some reason always getting this:

`Cannot read property '$mapPromise' of undefined
`
How can i successfully get the `Map` and `google` objects so i can work with them?

Thanks.

**Comment by vinayakkulkarni** [comment]
How did you solve this?

**Comment by LukeXF** [comment]
I would also like to know `Cannot read property '$mapPromise' of undefined`

**Comment by ryntab** [comment]
For anyone looking for an answer you can defer the call back and then check if the ref exists. Hope this helps!
```
this.$nextTick(() => {
          if (this.$refs.googleMap) {
                this.$refs.googleMap.$mapPromise.then(() => {
                    this.$refs.googleMap.$mapObject.fitBounds(this.googleMapBounds);
                })
          }
 })
