### ISSUE TITLE
Place the pac-container where I want // Incorrect width

### ISSUE THREAD

**Issue by oguilleux** [xkjyeah/vue-google-maps#558]
The pac-container ends up just before the close of body tag. How I can place it somewhere else ?

![2018-12-14_0939](https://user-images.githubusercontent.com/5804006/49992434-616b7b80-ff84-11e8-99c7-33d1a9e7d301.png)

I'm asking this because the width of pac-container is incorrect.

Thanks for your help

**Comment by xkjyeah** [comment]
I believe this is a design decision in the Google Maps library. Because the drop down list of suggestions needs to float over all elements instead of possibly being clipped by a bounding box

**Comment by oguilleux** [comment]
Thanks for your reply. I don't know why but the pac-container is smaller than my input which leads to unbalanced aesthetic. Also I need to wrap it up in fake dropdown I created for UI purposes.

The workaround I found was to prepend the pac-container in a wrapper around my input, just after the input.

**Comment by xkjyeah** [comment]
Unfortunately that's the implementation detail of Google Maps JS API. This library is just the glue between the two.
