### ISSUE TITLE
Zoom level is being overwritten somehow

### ISSUE THREAD

**Issue by iamrajput** [xkjyeah/vue-google-maps#561]
Somehow the zoom level is being overwritten somehow, `Gmap` is not accepting the zoom level passed via props. This is how I am using it,
```
        <GmapMap
            :center="{lat:0, lng:0}"
            :scrollwheel="false"
            ref="map_view"
            :zoom="12"
            map-type-id="terrain"
            style="height: 200px; width: 100%;"
        >
            <GmapMarker
                :position="position"
                :clickable="true"
                :label="{color: '#fff', fontSize: '14px', fontWeight: '600', text: '1'}"
                :icon="'/unselect-location.png'"
            >
            </GmapMarker>
        </GmapMap>
```

But the map is not rendering the zoom level I am passing, its overwriting the zoom. Here is the events log. 
![map_zoom_issue](https://user-images.githubusercontent.com/13258459/50223625-c9292880-03c1-11e9-8cbd-8e2b4604d133.png)

I don't know how this trigger is happening.

**Comment by xkjyeah** [comment]
Hm. Could you first confirm that you're using the latest versions of the
library? 0.10.x. is the zoom being changed while you're interacting with
the map?

**Comment by ATUL1995** [comment]
My versions is "0.9.8".

**Comment by ATUL1995** [comment]
another thing I should mention that I am changing the map bounds when its container component mounts.
```
       setTimeout(() => {
            const bounds = new google.maps.LatLngBounds();
            bounds.extend(_this.position)

            _this.$refs.map_view.fitBounds(bounds);
        }, 600);
```

Is it interfering with the zoom level somehow?

**Comment by iamrajput** [comment]
Thank you problem is solve.
