### ISSUE TITLE
options loadCN= true, almost request to maps.google.cn,but have some requset to maps.googleapis.com

### ISSUE THREAD

**Issue by mocker12345** [xkjyeah/vue-google-maps#564]
<img width="1082" alt="wx20181224-104731 2x" src="https://user-images.githubusercontent.com/13307672/50389826-06970880-076a-11e9-9dbb-ab73577e52e2.png">
<img width="1082" alt="wx20181224-104731 2x" src="https://user-images.githubusercontent.com/13307672/50389846-3c3bf180-076a-11e9-9a4f-9029c33152c8.png">

please help me

**Comment by xkjyeah** [comment]
I can't fix this.
非常抱歉，但我無能爲力。這是谷歌提供的庫的問題。

https://issuetracker.google.com/issues/35825956
