### ISSUE TITLE
google.maps.places.PlacesService.getDetails is not a function

### ISSUE THREAD

**Issue by syonip** [xkjyeah/vue-google-maps#568]
Hi,
It seems the [getDetails](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails) method is missing on the PlacesService class.

The PlacesService class does exist:
```
google.maps.places.PlacesService
ƒ (a){var b=this;this.j=null;_.U("places_impl").then(function(c){b.j=c.l(a)})}
```

Thanks.

**Comment by xkjyeah** [comment]
You'll have to lodge a bug report with Google. I'm only providing a glue library
