### ISSUE TITLE
Huge Data-Sets ( Inquiry Not Bug )

### ISSUE THREAD

**Issue by admcfajn** [xkjyeah/vue-google-maps#57]
Any recommendations on how to plot lots of pins. 10,000 - I'd like the map to load, then start adding the pins (instead of waiting for all the pins to be placed, then loading). 

I'll dig through your examples and see what I come up with - Just curious if anyone has a technique for this kind of thing. Thanks!

**Comment by zashton** [comment]
Maybe you could try

loaded.then(() => { http get to fetch marker coordinates / initialize markers } 
…

**Comment by admcfajn** [comment]
Thanks @ashtonzheng 

Limiting the set-size helped, anything over 1,500 was crashing spectacularly. Removing clustering didn't seem to help.

Moving the markers from one object to another was useful enough. 
`
for ( let m in this.data ){
  this.markers.push(this.data[m]);
}
`

_Could_ have used a callback with a delay, but didn't end up needing to.

I was also thinking of filtering the markers by map-bounds to help buffer things.
