### ISSUE TITLE
mousemove for GmapMarker

### ISSUE THREAD

**Issue by barnholdy** [xkjyeah/vue-google-maps#572]
https://github.com/xkjyeah/vue-google-maps/blob/6c20ad62191c2800f006a840b7f8d26cd22bdbda/src/components/marker.js#L62

I would like to prevent `mousemove` events on the map when hovering `GmapMarker` using stopPropagation. But it seems `GmapMarker` is not registered for `mousemove` events. Is there a reason not to have it?

**Comment by xkjyeah** [comment]
Because it's not supported by Google Maps: https://developers.google.com/maps/documentation/javascript/reference/marker#Marker
