### ISSUE TITLE
Display problems under various dpi

### ISSUE THREAD

**Issue by skyzfdance** [xkjyeah/vue-google-maps#574]
Hello, I am a developer from China, thank you for making such a good program.
Sorry, my English is not particularly good, I try to make the problem clear.
I am referring to a google map, just the most basic features
`<gmap-map 
          :center="{lat:22.29913, lng:114.1728369}" 
          :zoom="20"
          style="width: 100%; height: 100%" 
          :options="{disableDefaultUI: true}">
          <gmap-marker 
            v-for="(item,index) in marker" 
            :key="index" 
            :position="{lat:item.lat,lng:item.lng}"
            :icon="icon"
          ></gmap-marker>
        </gmap-map>`
But I found that this view, under different dpi, will show inconsistencies，When dpi = 1, the view is normal, but when dpi > 1, the view is reduced, and the text in the view cannot be seen.
`http://yingon-wap.photon.com.hk/#/zh-tw/contactus`
Please help me to see, how to deal with it, thank you

**Comment by xkjyeah** [comment]
请问你直接把google maps嵌入网页的时候（不使用vue），是否也出现同样问题？

**Comment by skyzfdance** [comment]
> 请问你直接把google maps嵌入网页的时候（不使用vue），是否也出现同样问题？

这和 vue  应该没什么关系，在dpi=1 的情况下，是正常的，只是到了高清屏幕下，会出现显示文本过小的情况，

**Comment by xkjyeah** [comment]
既然不是vue-google-maps的问题，我把这issue关了

**Comment by skyzfdance** [comment]
> 既然不是vue-google-maps的问题，我把这issue关了

麻烦您了 ，祝您新年快乐
