### ISSUE TITLE
Question: How to add image instead use icon ?

### ISSUE THREAD

**Issue by kristoff2016** [xkjyeah/vue-google-maps#576]
Hi there,
is there any way that I can apply use profile instead using icon ? and I want to add class to image ?

```
<GmapMap
        :center="center"
        :zoom="15"
        style="width: 100%; height: 350px"
        map-type-id="terrain"
      >
        <GmapMarker
          v-for="(marker, index) in markers"
          :key="index"
          :clickable="true"
          :position="marker"
          :icon="image here"
        ></GmapMarker>
      </GmapMap>
```

Here image that I want to do it 
[https://lh3.googleusercontent.com/XyWeyOX-SBA03Bzxthm3Hn7iQmCJFdnIcj4eJTj6439V-rn7BXxnQh4c9qOQq-3A4_uSEsDaMwZ6C4DfEZJDWU62INNchsVqbourADXazeWVwaRYEh8_9bXQQzbgtTUH_5lagQS6MfoY4ZSWGFRkS1bCDQqBWqUfBf59P0ZnPxgtMf9mhhD3N9XePdlM7G9NRP9ItGoix5jfRLuIcsx-dhku6W81bbCr9sg1wY2m_xer5wl35IFHi10qdxX2pdLMt34HJ13OeA9hVVSJtKKaO2gOvwZLNY43yY8AdiNp5eFK4PhS5OXqtR2bHqfXLcsGVJqcL-P3eY4RJWlGy5aAaC8RG32OoTOBLK8BhGVXv0210ri-sGfmspo37fuVKPNdsHCoz7GM4ZwVSCkgjJwiqALBc686Q30g9-uD0leuqxOcYcWdiJ4SbZnGlx8En1pgM2jcccqnmOSBV6UUbzCMqRvAzR9DdWq-nEITy3XOhmEurVoVnPSEG6MPnJtOa8zwV3LjpLDKjUFCPb-s5rGrPE9gCe-5dFz1xNZMoYedYRhFVYCnDg_hiDW8DlwpmnZltKaV8zaGYT0dEoe7t3MqmFRQ6coblwlIUQtol79F9_XaV0vtZK7x6BYisGL9suIsdx_IKO6XGcJpPxSdPtg9IS4cQA=w464-h220-no](https://lh3.googleusercontent.com/XyWeyOX-SBA03Bzxthm3Hn7iQmCJFdnIcj4eJTj6439V-rn7BXxnQh4c9qOQq-3A4_uSEsDaMwZ6C4DfEZJDWU62INNchsVqbourADXazeWVwaRYEh8_9bXQQzbgtTUH_5lagQS6MfoY4ZSWGFRkS1bCDQqBWqUfBf59P0ZnPxgtMf9mhhD3N9XePdlM7G9NRP9ItGoix5jfRLuIcsx-dhku6W81bbCr9sg1wY2m_xer5wl35IFHi10qdxX2pdLMt34HJ13OeA9hVVSJtKKaO2gOvwZLNY43yY8AdiNp5eFK4PhS5OXqtR2bHqfXLcsGVJqcL-P3eY4RJWlGy5aAaC8RG32OoTOBLK8BhGVXv0210ri-sGfmspo37fuVKPNdsHCoz7GM4ZwVSCkgjJwiqALBc686Q30g9-uD0leuqxOcYcWdiJ4SbZnGlx8En1pgM2jcccqnmOSBV6UUbzCMqRvAzR9DdWq-nEITy3XOhmEurVoVnPSEG6MPnJtOa8zwV3LjpLDKjUFCPb-s5rGrPE9gCe-5dFz1xNZMoYedYRhFVYCnDg_hiDW8DlwpmnZltKaV8zaGYT0dEoe7t3MqmFRQ6coblwlIUQtol79F9_XaV0vtZK7x6BYisGL9suIsdx_IKO6XGcJpPxSdPtg9IS4cQA=w464-h220-no)

thank you for help.

**Comment by antoinematyja** [comment]
Try:
```
:icon="{ url: 'your_image_url.png' }"
``` 

To resize it, use `scaledSize`:
```
:icon="{ url: 'your_image_url.png', scaledSize: { width: 25, height: 50 } }"
```

**Comment by kristoff2016** [comment]
@antoinematyja thank you so much for help. is there any way that I can apply my own class into icon this ? thank you again

**Comment by kristoff2016** [comment]
I really want to do in image above

**Comment by antoinematyja** [comment]
Behind the scenes, this vue component calls javascript methods from Google maps js library.
The google maps library itself generates a bunch of html elements to render your icon on the map, but you will not have one element with a specific class.
Best you can do is tweak these options:
https://developers.google.com/maps/documentation/javascript/reference/marker#Icon

**Comment by kristoff2016** [comment]
I found best solution.
