### ISSUE TITLE
Styled Maps - Night Mode

### ISSUE THREAD

**Issue by kristoff2016** [xkjyeah/vue-google-maps#579]
Hello there, 
is there any way that possible ?

thank you

**Comment by kristoff2016** [comment]
For anyone else who stumbles upon this, I found this helpful.
https://mapstyle.withgoogle.com/

**Comment by marncz** [comment]
You can apply styles like so:
```
 <gmap-map
                :center="center"
                :zoom="zoom"
                v-bind:options="mapStyle">
```

And then in your data array return:

```
data() { 
    return {
         mapStyle: {styles: <your-styles-array-here>}
    }
}

```

**Comment by j-wil** [comment]
For anyone else who stumbles upon this, I found this helpful. 

https://mapstyle.withgoogle.com/
