### ISSUE TITLE
Disable Street View on Map

### ISSUE THREAD

**Issue by admcfajn** [xkjyeah/vue-google-maps#58]
Is there a quick way to do this? Hoping someone's had to do it before.

these didn't work...
`<gmap-map street-view-control="false"></gmap-map>`

`<gmap-map streetViewControl="false"></gmap-map>`

**Comment by noevidenz** [comment]
You can use the :options prop for this.

`<gmap-map :options="{streetViewControl: false}"></gmap-map>`

**Comment by admcfajn** [comment]
#facepalm Thank you! That should do the trick for removing other items, such as business listings too. Thanks @noevidenz
