### ISSUE TITLE
show/hide markers

### ISSUE THREAD

**Issue by TihomirS** [xkjyeah/vue-google-maps#586]
hi,

can I use visible in this way? 

`<gmap-marker :key="i" v-for="(m,i) in markers" :visible="m.visible" :title="m.infoText" :position="m.position" :icon="m.icon" :clickable="true" @click="toggleInfoWindow(m,i)"></gmap-marker>`

and set in data:
`  markers: [{
            position: {
              lat: 47.376332,
              lng: 8.547511
            },
            icon: {url : 'img/check.png'},
            infoText: 'Marker M',
            visible: show_m
          }, {
            position: {
              lat: 47.374592,
              lng: 8.548867
            },
            icon: {url : 'img/check.png'},
            infoText: 'Marker C',
            visible: show_c
          }, .......`

and then allow the user to change show_m and show_c - true/false and hide/show markers from map ?
is this posible?
or my other option .. to post to /api and generate new markers array with 'visible: false' on chosen markers?

best,

**Comment by TihomirS** [comment]
I found my way :)

**Comment by aneesshameed** [comment]
If anyone else is looking for a solution then there is a props called 'visible' in GmapMarker. You can set it to true or false to control the visibility.

``` vue
<GmapMarker v-for="(m, index) in markers" 
              :key="index"
              :position="m.position" 
              :visible="m.visibility"
             @click="toggleInfo(m, index)" />
```

If you need to hide all the pins from the map then 

```js
hideAllMarkers() {
for(let i=0;i<this.markers.length;i++){
          this.markers[i]["visibility"] = false;
        }
}
```

**Comment by dkoether** [comment]
@aneesshameed Your solution works well, thanks! Do you or anybody else know how to update the GmapMarkerCluster if wrapped around? The markers got updated correctly if I switch the visibility but this does not work for cluster icons. :(
