### ISSUE TITLE
gmapApi returns null

### ISSUE THREAD

**Issue by razbakov** [xkjyeah/vue-google-maps#606]
### Steps to reproduce

In documentation states:

If you need to gain access to the `google` object:

```html
<script>
import { gmapApi } from 'vue2-google-maps'

export default {
  computed: {
    google: gmapApi
  }
}
</script>
```

### Actual result

`google` returns null

### Expected result

`google` is an object

### Environment

Version: 0.10.6

**Comment by razbakov** [comment]
I am also a little bit confused about branching. What is `master` branch stands for?

**Comment by Solant** [comment]
@razbakov `gmapApi` is lazy initialized, you should instantiate map in your template to get this value

**Comment by mornir** [comment]
https://github.com/xkjyeah/vue-google-maps/wiki/vue-google-maps-FAQ#where-is-my-google
