### ISSUE TITLE
Getting a diamond shape watermark on the map

### ISSUE THREAD

**Issue by jsd219** [xkjyeah/vue-google-maps#608]
I am getting these diamond shaped watermarks on my map. I checked with google support and they confirmed it is not them. see screen shot.

<img width="915" alt="Screen Shot 2019-04-17 at 11 48 44 AM" src="https://user-images.githubusercontent.com/842940/56306531-4d897f00-6108-11e9-86d3-b9d77e0a33b6.png">

**Comment by jsd219** [comment]
found the issue. It was my css. Sorry

**Comment by postolovski** [comment]
What was your issue with Css? I am having same problem also google support could not help me.

**Comment by silaswint** [comment]
Solution:

```
#google-maps-container img {
    border-radius: 0;
}
```

Replace google-maps-container with your actual container element id
