### ISSUE TITLE
How is API call count calculated?

### ISSUE THREAD

**Issue by hifall** [xkjyeah/vue-google-maps#610]
I have a SPA dashboard which uses this nice plugin to display maps to users. After the dashboard loads, the user is free to click through a list of items, with each of which having its own location info, and check the Google map associated.

In such a scenario, how is the Google Maps API call count calculated? Is it just 1 or the number of clicks throughout the entire user session? For example, say the user clicks 10 items in the list, and the plugin renders 10 times for the locations (10 different longs/lats).

My common sense tells me it's 1 instead of 10. This happens when it calls Google to create the Maps instance, instead of swapping longs/lats. I just need to understand this well since Google Maps API is expensive to use once it goes beyond the free quota.

**Comment by Blackcell** [comment]
This question is about Google Maps API, not vue-google-maps. 

The cost is per map **load** and pricing can be found [here](https://developers.google.com/maps/faq?__utma=236542612.1398248387.1558635349.1558635544.1558635544.1&__utmb=236542612.0.10.1558635544&__utmc=236542612&__utmx=-&__utmz=236542612.1558635544.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&__utmv=-&__utmk=60539118&_ga=2.69598672.-1398248387.1558635349#usage_mapload).

The definition of map load can be found [here](https://developers.google.com/maps/faq?__utma=236542612.1398248387.1558635349.1558635544.1558635544.1&__utmb=236542612.0.10.1558635544&__utmc=236542612&__utmx=-&__utmz=236542612.1558635544.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&__utmv=-&__utmk=60539118&_ga=2.69598672.-1398248387.1558635349#usage_mapload).

**Comment by diegoazh** [comment]
Close because this question is not related to vue-gogle-maps.
