### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by m-weeks** [xkjyeah/vue-google-maps#613]
I just installed this plugin and am attempting to render a map on my page, but everything I try results in a div that doesn't contain anything.

I've imported the components, but not the API as I already have it loaded on the page for use elsewhere.
```
import * as VueGoogleMaps from 'vue2-google-maps'

Vue.use(VueGoogleMaps);
```

`<script src="https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places"</script>`

So I've put the component on my page and it gives me no errors, but it doesn't appear to render a map.
```
<gmap-map
                    :center="{ lat: latitude, lng: longitude }"
                    :zoom="7"
                    style="height:300px; width: 500px;"
                >
</gmap-map>
```

![image](https://user-images.githubusercontent.com/37918120/57875869-2f7b7100-77d1-11e9-9b57-f06597a72d0e.png)
![image](https://user-images.githubusercontent.com/37918120/57875896-3dc98d00-77d1-11e9-8c89-b892eac9b0f9.png)

I've seen the other issues on this repo that just say to add CSS like so:
```
.vue-map-container {
    width: 100%;
    height:100%;
}
.vue-map-container .vue-map {
    width: 100%;
    height:100%;
}
```
Or similar variants, but even doing this my map will not display.

I've also tried removing my instance of google maps and letting the module load it, but it still does not work.

Any ideas?

**Comment by m-weeks** [comment]
Turns out the issue was I was not calling `vueGoogleMapsInit();` when I loaded google maps externally

**Comment by asiz15** [comment]
Hey, can you tell me more about the solution? I have the same problem, I dont understand your answer

**Comment by hunterbit** [comment]
I have the same problem
