### ISSUE TITLE
Marker shape not working

### ISSUE THREAD

**Issue by janwirth** [xkjyeah/vue-google-maps#62]
```
          shape: {
            coords: [1, 1, 1, 20, 18, 20, 18, 1],
            type: 'poly'
          }
```
results in default marker.

**Comment by janwirth** [comment]
Why was this closed? I am paying this prop to the marker directive and the icon remains the same.

**Comment by xkjyeah** [comment]
Example: http://xkjyeah.github.io/vue-google-maps/basic-marker-shape.html

(The icon remains the same, but the clickable area has changed -- if you need custom shape icons, you pass that in through the `icon` property`)

If you need this feature, run `npm install vue2-google-maps@latest`

**Comment by janwirth** [comment]
Ah I'm sorry... Thank you for pointing me in the right direction
