### ISSUE TITLE
Remove map from tabbing order

### ISSUE THREAD

**Issue by bhaskar-nair2** [xkjyeah/vue-google-maps#630]
Hi, I'm using the map component in a form to display a pin drop, but would like to remove it from the  tabbing order. I have removed the basic UI but the focus still moves to the google terms of use or report error buttons. 

These are the options added to the map
```
	mapOptions: {
				scrollwheel: false,
				zoomControl: false,
				mapTypeControl: false,
				scaleControl: false,
				streetViewControl: false,
				rotateControl: false,
				fullscreenControl: false,
				disableDefaultUi: true,
			}
```

This is the template
``` 
<GmapMap tabIndex="-1" class="map" :zoom="zoom" :center="center" :options='mapOptions'>
        <GmapMarker v-for="(marker, index) in markers" :key="index" :position="marker.position" />
        <GmapMarker v-if="this.place" label="★" :position="{
          lat: this.place.geometry.location.lat(),
          lng: this.place.geometry.location.lng(),
        }" />
      </GmapMap>
```

Have added tabIndex in the form control as well, but can't seem to remove focus from the Google button or the Report an Error button. I don't want to remove those buttons altogether, just want to remove from the tabbing order.

**Comment by AllanOcelot** [comment]
@bhaskar-nair2 this is most likely a google maps core feature, and not a bug nor issue with this Repo sadly.

Your best bet will be to reach out to google maps support.

**Comment by bhaskar-nair2** [comment]
@AllanOcelot Have put this as an issue in google maps repo.
