### ISSUE TITLE
0.11.0

### ISSUE THREAD

**Issue by xkjyeah** [xkjyeah/vue-google-maps#632]
Hi Diego,

Thanks for managing all the PRs and bugfixes. That's really helpful!

However, AFAICT the examples generator is currently broken. If you run the following steps:
1. npm run build-examples
2. Visit examples/infowindow.html

Firstly, the site is broken.
Secondly, it's encouraging a code style that could potentially lead to XSS (HTML in the `content` option).

Could you fix these issues before I publish a release?

**Comment by diegoazh** [comment]
Ok @xkjyeah. I will review this.

**Comment by diegoazh** [comment]
@xkjyeah I create a new [PR #636](https://github.com/xkjyeah/vue-google-maps/pull/636) with the fixes for version 0.11.0. Please review this. Thanks.

**Comment by diegoazh** [comment]
Fixed.
