### ISSUE TITLE
How to set zIndex in marker ?

### ISSUE THREAD

**Issue by cuongdevjs** [xkjyeah/vue-google-maps#633]
i have 2 marker in chart. It close each other. so marker 1 override marker 2. How to set marker2 override marker 1 when i click in marker 2 and vice versa
<img width="552" alt="Screen Shot 2019-07-15 at 3 24 40 PM" src="https://user-images.githubusercontent.com/33604446/61203503-c0f55980-a714-11e9-98df-fdde36795136.png">

**Comment by kps1ny** [comment]
Hello @cuongdevjs  - how were you able to do this? I have tried gmap-info-window with :style="'z-index: ' + m.InfoZ + ' !important'" but it seems to have no effect, when setting a marker's InfoZ value.
