### ISSUE TITLE
Possible to draw polyline along road?

### ISSUE THREAD

**Issue by cuongdevjs** [xkjyeah/vue-google-maps#638]
Can anyone help me?

**Comment by diegoazh** [comment]
Its possible but I not remember if its required other plugin. In a few days I will have an answer.

**Comment by cuongdevjs** [comment]
Thank you. Hope your answer.

**Comment by PabloZanek** [comment]
Hi, @CuongStf. It's possible to do what are you asking for
First you have to enable Google Direction Services: https://developers.google.com/maps/documentation/javascript/directions#GetStarted
Then you can draw polylines using the direction service like the documentations suggest
https://developers.google.com/maps/documentation/javascript/examples/directions-simple

This is what I did:
```javascript 
let directionsService = new google.maps.DirectionsService()
let directionsDisplay = new google.maps.DirectionsRenderer()
  this.$nextTick(() => {
    directionsDisplay.setMap(YOUR_MAP_REF)
  })
  directionsService.route({
    origin: LatLang or {lat, lng},
    destination: LatLang or {lat, lng},
    travelMode: 'DRIVING'
//see https://developers.google.com/maps/documentation/javascript/directions#TravelModes for all modes
  }, function(response, status) {
    if (status === 'OK') {
      directionsDisplay.setDirections(response)
    } else {
      window.alert('Directions request failed due to ' + status')
    }
  })
```

If you need you can add waypoints to the route also. For doing that you have to use Waypoints
https://developers.google.com/maps/documentation/javascript/directions#Waypoints
https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints

Hope you find it helpful.

**Comment by diegoazh** [comment]
Thank you @PabloZanek, I hope this answer helps you @CuongStf.
Please let us know if this solves your issue in order to close it or close it your self.
Regards.

**Comment by cuongdevjs** [comment]
I tries, but not work.
@PabloZanek 
Can you give me your code? Many thanks.

**Comment by cuongdevjs** [comment]
Can I use google directions without fill billing methods?

**Comment by PabloZanek** [comment]
Unfortunatelly no, Directions is a paid service.

Answering the other question, the code that I passed you is what I'm using rigth now. Show me how are you implement it, we can find a solution together

**Comment by cuongdevjs** [comment]
Thanks for your help?  But i am stuck in denied status due to i don't have key. So can i ask you later? Thanks

**Comment by PabloZanek** [comment]
Of course, let me know when you need help.
Regards

**Comment by jrk997** [comment]
Hello @PabloZanek ,
I am interested in how i could display the data on a map in the most effective way so that the line would stick to the road. I managed to partially solve the problem with Google Directives, but the waypoints limit is 25 and its quite expensive

Regards
