### ISSUE TITLE
Which service have I to select ?

### ISSUE THREAD

**Issue by PetroGromovo** [xkjyeah/vue-google-maps#643]
Hello!
I want to show google map by coordinates in my  Laravel 5/vuejs 2.6 app and I found https://github.com/xkjyeah/vue-google-maps 
plugin and it has link to https://developers.google.com/maps/documentation/javascript/get-api-key url and following I opened
page with noumerous choice : https://prnt.sc/otflf9
Have I select Maps Jacascript API or something else ?

Thanks!

**Comment by unguul** [comment]
@PetroGromovo Yes. The API key you get from Google should be enabled for JavaScript usage.
