### ISSUE TITLE
@dragend callback returns undefined on gmap-map component

### ISSUE THREAD

**Issue by onurgultekin** [xkjyeah/vue-google-maps#650]
I want to use dragend event on <gmap-map /> component like below in my Nuxt powered project:
```javascript
<gmap-map
          :center="center"
          :map-type-id="mapTypeId"
          :zoom="17"
          :options="{disableDefaultUI : true}"
          @dragend="dragEnd"
        />
methods: {
dragEnd(event) {
      console.log(event)
    }
}
```
console.log gives me undefined.
I tried to use it like
```javascript
@dragend="dragEnd($event)"
```
but result is undefined again.

**Comment by JGRusty404** [comment]
Also getting the same issue in a standard Vue template

**Comment by xkjyeah** [comment]
The JS API does not pass any arguments to the `dragend` event handler: https://developers.google.com/maps/documentation/javascript/reference/map#Map.dragend

Therefore this library does not pass any arguments to the event handler either
