### ISSUE TITLE
VueGoogleMaps is not defined.. using Standalone 

### ISSUE THREAD

**Issue by devsyams** [xkjyeah/vue-google-maps#66]
i tried using vuegooglemaps with standalone..
my code is actualy the same like u did in documentation..

but i got this error.. 

![error](https://cloud.githubusercontent.com/assets/24582309/23846791/b1abbe42-0801-11e7-9174-8466f5b8ec9c.JPG)

what happened?

**Comment by xkjyeah** [comment]
Hi,

Sorry for the difficulty, but the naming is rather inconsistent at the
moment. Try VueGoogleMap (without the s at the end)

**Comment by devsyams** [comment]
thanks daniell... it works..
keep it up

**Comment by smarttvdev** [comment]
Hi, xkjyeah.
Thanks for your good work.
But I can't still get this working.
It gives me VueGoogleMap is not defined.
