### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement with gmap-autocomplete

### ISSUE THREAD

**Issue by yamenshahin** [xkjyeah/vue-google-maps#663]
I got error `InvalidValueError: not an instance of HTMLInputElement` with gmap-autocomplete.

This happened only when I refresh the page that contains  gmap-autocomplete or access the page directly by typing it's URL in the browser address.

When I inspect the element with dev tools I found  gmap-autocomplete was not rendered yet.

```HTML
        <b-form-group>
                    <gmap-autocomplete
                      class="form-control"
                      placeholder="Delivery Address"
                      :value="deliveryPlaceObject.address"
                      required
                      @place_changed="setDeliveryPlace"
                    ></gmap-autocomplete>
           </b-form-group>
```

Also I use Nuxt.js like this:
```JSON
//nuxt.config.js
plugins: [
   { ssr: false, src: '~plugins/google-maps.js'  },
]
```
And google-maps.js
```JavaScript
import Vue from 'vue'

import * as VueGoogleMaps from 'vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: 'realKeyHere',
    libraries: 'places,directions'
  }
})

```

**Comment by yamenshahin** [comment]
It's not an issue with `vue-google-maps`,`Nuxtjs` requires wrapping this component in `<no-ssr>` tag.

**Comment by alvinotienokelly** [comment]
> It's not an issue with `vue-google-maps`,`Nuxtjs` requires wrapping this component in `<no-ssr>` tag.
Awesome this solution worked very well
