### ISSUE TITLE
Is it possible to remove the markers?

### ISSUE THREAD

**Issue by Marinsan** [xkjyeah/vue-google-maps#676]
Hello everyone, my question is, is there a way to remove default Google markers? Thanks

**Comment by EMILO9** [comment]
Had the same question as you, found this solution. is this what you where looking for?
```
data () {
    return {
      mapStyle: [{
          "featureType": "poi",
          "elementType": "labels",
          "stylers": [
                { "visibility": "off" }
          ]
      }]
    }
  }

<GmapMap :options="mapStyle"></GmapMap>
```
This is just an example, the better way to do it would be to store all your styles + settings in  a JSON file.

**Comment by Marinsan** [comment]
Hi, I forgot to close and comment on the solution I found. I had to pass the suppressmarkers inside the options to the DirectionsRender. Tan simple como esto. Thanks for your response.
```
data () {
    return {
      options: {
          suppressMarkers: true
      }
    }
  }

 <DirectionsRenderer :directions="directions" :options="options" />
```
