### ISSUE TITLE
utc_offset is deprecated as of November 2019 and will beturned off in November 2020. Use utc_offset_minutes instead.

### ISSUE THREAD

**Issue by albay13** [xkjyeah/vue-google-maps#685]
Still hoping for update regarding with this error. Thanks

**Comment by GiusWhite** [comment]
Hi @albay13,
I saw this your old issue https://github.com/xkjyeah/vue-google-maps/issues/675

Probably is not a good idea to open a new issue for the same problem. Let's wait an answer or good news on the old issue (https://github.com/xkjyeah/vue-google-maps/issues/675) 🙂
