### ISSUE TITLE
Uncaught Error: Cannot find module "marker-clusterer-plus"

### ISSUE THREAD

**Issue by ethanclevenger91** [xkjyeah/vue-google-maps#7]
The library is called `markerclustererplus` but the `require` is looking for it with hyphens. Should this be updated?

**Comment by vanderlin** [comment]
same...

**Comment by vanderlin** [comment]
Just add this...
`npm i marker-clusterer-plus --save`

**Comment by xkjyeah** [comment]
Oops my bad. I've updated API.md to match.
