### ISSUE TITLE
Help Centering Map

### ISSUE THREAD

**Issue by shayneo** [xkjyeah/vue-google-maps#70]
Hoping someone might be able to provide some guidance on how I can re-center a map. I'm getting coordinates through an API call, and then updating a data property, `latestCoordinates`. I then bind latest coordinates to center on the map, like `:center="latestCoordinates"`.

This doesn't seem to work. I think [this example](https://github.com/xkjyeah/vue-google-maps/blob/vue2/examples/basic-map-functions.html#L53) is similar to what I need to do... but can't seem to get it working by following similar logic in the example.

Halp?

**Comment by xkjyeah** [comment]
Here's an example that might do what you are trying to do:

http://xkjyeah.github.io/vue-google-maps/test-map-center.html

View source code for the code

**Comment by shayneo** [comment]
Thank you @xkjyeah I got it working 👍
