### ISSUE TITLE
TypeError: e.$get is not a function when setting Panorama :pov

### ISSUE THREAD

**Issue by tadasmajeris** [xkjyeah/vue-google-maps#75]
When I try to set :pov properties on `<gmap-street-view-panorama>`, I get this error:
```
vue-google-maps.js:1 Uncaught (in promise) TypeError: e.$get is not a function
    at VueComponent.e.$watch.immediate (http://localhost/js/vue-google-maps.js:1:1739)
    at VueComponent.Vue.$watch (eval at <anonymous> (http://localhost/js/app.js:133:1), <anonymous>:2869:10)
```

If I dont specify, there is no error.

**Comment by xkjyeah** [comment]
Hi,

Have you referred to the example at http://xkjyeah.github.io/vue-google-maps/street-view-pano.html?

If you have and you still get the error, could you  show me the code that led to the error?

Thanks

**Comment by Akryum** [comment]
There is a migration issue from Vue 1.x to Vue 2.x [here](https://github.com/xkjyeah/vue-google-maps/blob/vue2/src/utils/propsBinder.js#L60). `$get` was removed in Vue 2.0.0 and later, it should use standard Javascript, for example:

```javascript
vueElement[attributeTrackerRoot][attributeTrackerName] + 1);
```

**Comment by Akryum** [comment]
BTW, this causes the [vue-meteor-demo](https://github.com/Akryum/vue-meteor-demo) to fail on the Google Maps page with the following error:

```
Uncaught (in promise) TypeError: e.$get is not a function
    at VueComponent.e.$watch.immediate (http://localhost:4040/packages/modules.js?hash=188adae0a21ecb6c371ef5808bbf8b8d566cf701:25827:1434)
```

On this code:

![image](https://cloud.githubusercontent.com/assets/2798204/26726274/9db984ce-47a2-11e7-8b5d-eb823a093306.png)

**Comment by xkjyeah** [comment]
That's bizarre.. The _changeIndicators is not my code! EDIT: oops it is. my bad. Let me figure this out
