### ISSUE TITLE
info-window issues

### ISSUE THREAD

**Issue by Profile** [xkjyeah/vue-google-maps#77]
info-map is not open after closing

**Comment by xkjyeah** [comment]
Add @closeclick="infowindowIsOpen=false" :opened="infowindowIsOpen"

Or similar

**Comment by Profile** [comment]
nothing is changed
  	<gmap-info-window  @closeclick="infowindowIsOpen=false" :opened="infowindowIsOpen">
 			{{m.content}}
  	</gmap-info-window>


 Property or method "infowindowIsOpen" is not defined

**Comment by Profile** [comment]
i am also trying : 
     <gmap-marker
      v-for="(m,index) in markers"
      :position="m.position"
      :clickable="true"   
      @click="center=m.position"
      @mousedown="m.visible=true">

  	<gmap-info-window  @closeclick="m.visible=false" :opened="infowindowIsOpen">
 			{{m.type}}
  	</gmap-info-window>
    </gmap-marker>

**Comment by Profile** [comment]
i solved Thanks you 👍

**Comment by Profile** [comment]
this way works:

    <gmap-marker
      v-for="(m,index) in markers"
      :position="m.position"
      :clickable="true"   
      @click="center=m.position"
      @mousedown="m.visible=true">

  	<gmap-info-window  :opened="m.visible" @closeclick="m.visible=false">
 			{{m.visible}}
  	</gmap-info-window>
    </gmap-marker>

 export default{
 	 markers: [{
          position: {lat:40.385840, lng: 49.844778},
          content: {title:' is worked'},
          type:'event',
          visible:false,
        }, {
          position: {lat: 40.401439, lng: 49.852060},
           content: {title:' is worked2'},
           type:'travel',
           visible:false,
    }]
 }

 but after this data will come backend  and there is`t have visible filed 
 How i close or open specific info-map
