### ISSUE TITLE
There doesn't seem to be anyway to add an event listener to the map that allows marker placement based on a user's click event

### ISSUE THREAD

**Issue by GraplnMonkey** [xkjyeah/vue-google-maps#787]
I might be using this wrong, but most of the point of using Google Maps is the ability to capture user interactions and transfer that event object to functions that use features like Markers. If this doesn't work this package is pretty useless...

<template>
  <div>
    <GmapMap
  :center="center"
  :zoom="7"
  map-type-id="terrain"
  style="width: 90%; height: 400px"
  @click="mark(event)"
  :options="{
    
  }"
>
  <GmapMarker
    :key="index"
    v-for="(m, index) in markers"
    :position="m.position"
    :clickable="true"
    :draggable="true"
    @click="center=m.position"
  />
</GmapMap>
  </div>
</template>

<script>
import {gmapApi} from 'vue2-google-maps'
export default {
  computed: {
    google: gmapApi
  },
  data() {
    return {
      center: {lat: 40.66058758, lng: -111.8364045},
      markers: [],
      currentPlace: null
    };
  },
  mounted() {
    this.mark($event),
    this.$refs.mapRef.$mapPromise.then((map) => {
      
    })
  },
  name: 'Google Map',
  methods: {
    setPlace(place) {
      this.currentPlace = place;
    },
    mark(event) {
      this.markers = [
          {
              lat: event.target.lat,
              lng: event.target.lng,
              label: 'Marker'
          },
      ]
    }
  }
}
</script>

<style scoped>

</style>

**Comment by zeke8402** [comment]
Can you be more specific with what you're trying to do? The `GmapMap` component emits events already, so you can do `<GmapMap @click=mapAction>`, `mapAction` will receive lat/lng data relative to where the user clicked on the map.

**Comment by GraplnMonkey** [comment]
We're good. What I needed to do was add an event listener to the map for clicks:

google.maps.event.addListener(this.map, "click", (e) => {
       new window.google.maps.Marker({
      position: {lat: e.latLng.lat(), lng: e.latLng.lng()},
      map: this.map
