### ISSUE TITLE
Autocomplete region not wroking

### ISSUE THREAD

**Issue by digiignas** [xkjyeah/vue-google-maps#794]
Hello,
I have problem with region, after changing it nothing happens.
It still search address in region 'LT',  but i want other region. Maybe there is some restrictions from Google API? Or something else can cause this?
Language parameter working good.

My code:
Vue.use(VueGoogleMaps, {
    load: {
      key: '****',
      libraries: 'places',
      region: 'VI',
      language: 'lt',
    },
  })

**Comment by digiignas** [comment]
My fault

**Comment by Furqan2** [comment]
what's your fault in it ?? @digiignas
