### ISSUE TITLE
Cannot read property '$mapCreated' of undefined

### ISSUE THREAD

**Issue by shayneo** [xkjyeah/vue-google-maps#80]
I'm doing this (see below) but get an error on initial page load 
```
mounted () {
  this.$refs.tMap.$mapCreated.then(() => this.setBounds());
}
```
`TypeError: Cannot read property '$mapCreated' of undefined`

it seems like my component, `tMap` doesn't exist on `mounted`? which is weird...

**Comment by shayneo** [comment]
Still stuck on this, I'm realizing that my `gmap-map` has a `v-if` directive on it, so perhaps the `v-if` is not evaluated before `mounted`?

**Comment by xkjyeah** [comment]
Yes that's possible.

$watch the v-if condition, and the perform the operation that you need in a
$nextTick

**Comment by vwasteels** [comment]
for information : ```$mapCreated``` became ```$mapPromise```
