### ISSUE TITLE
2000+ clustered markers prevent navigating away ?

### ISSUE THREAD

**Issue by onekiloparsec** [xkjyeah/vue-google-maps#81]
Hi. I'm rather new to Vue, but I easily managed to include your great plugin in my project.

However, I have clusters of more than 2000 markers spread worldwide. When I select one of the associated place in the table beside it (see screenshot), URL changes, but it takes ages – like 2 or 3 minutes – to actually navigate away from that page with map (and CPU goes up!). 

I've tried many things: `v-if`, routeur's `beforeRouteLeave` and `beforeRouteUpdate`, the component's `beforeDestroy`, dynamic markers as one of the `methods`, or fixed ones stored in the `vuex` store. To no avail so far. I have no error message though. 

I noticed however that when I zoom towards the selected position, the map update quite well, I end up with a map with a single visible marker, and then I can easily navigate away.

Any idea? I don't know if this is related to #65 ?

P.S. The page that I navigate *to* also has a map (with a much closer zoom). 

![screen shot 2017-04-01 at 14 42 15](https://cloud.githubusercontent.com/assets/226224/24578824/6bd54cde-16e9-11e7-8b15-591b2b5cfc2b.png)

**Comment by xkjyeah** [comment]
Hi Cedric,

Unfortunately due to the way the markers are implemented at the moment,
they manipulate invisible DOM elements, and that makes it slower than
without the Vue binding.

Moreover, Google Maps isn't the fastest Maps library around. I cannot be
certain whether it is 'vue-google-maps' or the Google Maps API that is the
culprit, but if you need 2000+ markers you will probably have better luck
with Mapbox GL

**Comment by onekiloparsec** [comment]
Hi. Thanks for the quick reply, and the interesting hints. What surprises me is that markers are created and displayed in a very efficient manner, as far as I can tell. I just can't remove them easily. Does the lib has a "removeAll" method or similar I can test before moving to another lib?

**Comment by onekiloparsec** [comment]
I just made additional extensive tests. The problem lies with the clusters. If I remove the clustering of markers, everything works fine, it seems.

**Comment by xkjyeah** [comment]
v0.7.10 fixed this
