### ISSUE TITLE
Couldn't find preset "es2015" relative to directory "node_modules/vue2-google-maps"

### ISSUE THREAD

**Issue by ali5h** [xkjyeah/vue-google-maps#82]
Having `babel-preset-env` instead of `babel-preset-latest` on the main project, will result in a build error when using `vue-google-maps`. I guess the reason is the existence of `.babelrc` in the root of this project, since removing it fixes the problem.

**Comment by Youdaman** [comment]
Another solution is to: `npm install babel-preset-es2015` which also fixes the problem (in case deleting `.babelrc` causes other problems.

**Comment by xkjyeah** [comment]
I'll add a .babelrc to the dist folder. This should allow the package to be
built as usual but not affect imports.

**Comment by alvinhochun** [comment]
I am having this problem using webpack 2 with the latest version of `vue2-google-maps` (0.7.9).

I suspect this is due to the `babel-runtime` 5.8.0 dependency. If I remove it and use `babel-runtime` 6.23.0 on the root project instead the problem would go away.

**Comment by xkjyeah** [comment]
if you are having problems, could you open a new issue with steps to reproduce?
