### ISSUE TITLE
Webpack 2.2.1 is have trouble resolving "_" and "MarkerClusterer"

### ISSUE THREAD

**Issue by 7seven7lst** [xkjyeah/vue-google-maps#83]
Yes I know this issue is prolly caused by webpack 2. What's your suggestion of temporarily suppressing this bug? revert to webpack 1?

**Comment by xkjyeah** [comment]
How are you trying to use the package?

When importing, use:
1. `import VueGoogleMaps from 'vue2-google-maps'` if you are using npm
2. `<script src="<SOME_DIR>/vue2-google-maps/dist/vue-google-maps.js"></script>`  if you are embedding the map directly in a web page

**Comment by 7seven7lst** [comment]
Here's my repo: https://github.com/Fantastic4Career/CareerFantastic_v2
1. I tried 1) npm, and neither the 3 commented code works. https://github.com/Fantastic4Career/CareerFantastic_v2/blob/master/public/assets/es2015/searchBar.es6#L6-L11
The relavent webpack config is here: https://github.com/Fantastic4Career/CareerFantastic_v2/blob/master/webpack.config.js

2. I tried 2) but also it gives syntax error: https://github.com/Fantastic4Career/CareerFantastic_v2/blob/master/public/index.html#L232

**Comment by xkjyeah** [comment]
Do you have the console output? What does the error say?

**Comment by 7seven7lst** [comment]
1) npm way: the error is: 
Uncaught Error: Cannot find module "_"
    at webpackMissingModule (bundle.js:38178)
    at n (bundle.js:38178)
    at Object.module.exports.module.deprecate (bundle.js:38178)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:37245)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:37393)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:66
    at bundle.js:69

(i have changed the lodash require to "global._ = require("lodash") " still give same error. )

2) the `\<script\>` tab way: the error is: 
Uncaught SyntaxError: Unexpected token <    <!DOCTYPE html>  
(pretty sure it's the script tag of vue google maps that i have inserted.

**Comment by anselmobattisti** [comment]
Probably lodash is not loaded https://lodash.com/
