### ISSUE TITLE
How to style?

### ISSUE THREAD

**Issue by kodekrendel** [xkjyeah/vue-google-maps#88]
How to style Map?

I have the code from https://mapstyle.withgoogle.com/

When I put it in   `data () { return { styles: [] }}` nothing changes.

**Comment by kodekrendel** [comment]
Find an answer:
Need to add:
```
<gmap-map
        :options="{styles: styles}"
      ></gmap-map>
```

You should update Documantation, guys!

**Comment by awitherow** [comment]
Maybe you should read into the documentation, guy!

The search function on repositories is really difficult to use, I know...

https://github.com/xkjyeah/vue-google-maps/pull/85/files#diff-88333ba11114e014e87198d04680144d

https://github.com/xkjyeah/vue-google-maps/blob/vue2/API.md#styling-the-map

**Comment by kodekrendel** [comment]
@awitherow maybe you should suck my balls, guy!

**Comment by xkjyeah** [comment]
Hi kodekrendel,

I use this package at work, which is why I maintain it, but not 100% of the
time, which is why I am not able to maintain it in perfect condition.

You could make a pull request to update the documentation. That help will
be much better appreciated than offensive remarks.

**Comment by kodekrendel** [comment]
@xkjyeah well, my remarks was concerning the tone of that **guy**. It doesn't intent to offend anyone. Your documentation is good, but it's HUGE, so no wonder first I didn't find my answer. That doesn't mean that some smart **guy** can speak to me with that tone. I see this insulting.

**Comment by awitherow** [comment]
@kodekrendel  Don't get so easily triggered. I just simply repeated a sentence you said to me, and then recommended the search function ❤️

**Comment by kodekrendel** [comment]
@awitherow well, you are right at some point, I guess. Also, I read your ost in 5 in the morning and was already pissed. So I guess, I own apology. Anyway, I am planning definitely to use vue-google-maps in future, so will be happy to contribute. Cheers. 

@xkjyeah sorry for the little mess I made.

**Comment by awitherow** [comment]
@kodekrendel It's okay bro, we all have been there 👍 I might have also been trolling a little 😉 

It is a good library, I am just starting to use it at https://github.com/openrefuge/openrefuge and have good plans for it. It looks like it will be a breeze to implement more stuff I have planned.
