### ISSUE TITLE
Newbie Question: Inserting lat/lng from database value

### ISSUE THREAD

**Issue by adavie1** [xkjyeah/vue-google-maps#99]
I appreciate that my question is more of a lack of knowledge of Vue but I've tried all the different approaches that work in other components and I'm stuck on how to pass the values from an existing set of data:

In `rowData` I have two properties: `latitude` and `longitude`. They are decimal values.

**1st Try:**
`<gmap-map :center="{lat: rowData.latitude lng: rowData.longitude}" ...`

**2nd Try:**
`<gmap-map :center="{{{lat: rowData.latitude lng: rowData.longitude}}}" ...`

**3rd Try:**
`<gmap-map :center="{lat: {{rowData.latitude}} lng: {{rowData.longitude}}}" ...`

All of which cause errors.

Any pointers would be much appreciated.
Thanks in advance.
Anthony

**Comment by caiquecastro** [comment]
Try `:center={lat: rowData.latitude, lng: rowData.longitude}`

**Comment by adavie1** [comment]
Thanks **solved**! The one obvious thing I didn't try! :+1:
